#+SETUPFILE: ../theme-rose.setup
#+DATE: <2020-06-19 Fri 12：29>
#+TITLE: CS Classes

** 计算机科学
*** 计算机辅助设计技术基础

i.e. Fundamentals of Computer Aided Design

3 学分 48 学时

本课程坚持基础知识与实践相结合的指导思想，在学习计算机辅助设计的基础知识的同时，学习三维动画软件的操作与使用。

基础知识包括：图形变换、自由曲线曲面造型技术、三维几何造型、真实感图形。应用软件：3DSMAX 2013 软件的操作。这两部分内容是有机联系的，基础知识对理解 3DSMAX 软件中的基本概念提供帮助；通过 3DSMAX 软件的操作与实践，能够更好地理解有关基本概念并学习到一门很实用的技术（三维造型与动画）。

课程的基础知识包括：
- 二维图形变换：主要讲授图形的基本变换（平移、旋转、缩放等）及组合变换。简介自由曲线曲面造型技术的基本思想和技术，该技术主要应用在非规则几何模型建模。
- 三维几何造型：主要讲授规则三维模型的几种表示方法，介绍当前主流的三维造型方法，最后介绍自然景物的造型方法。
- 真实感图形：介绍计算机生成真实感图形的绘制流程：局部光照模型、全局光照模型、纹理映射技术、图形绘制技术等。

课程的 3DSMAX 软件内容包括：
- 操作界面及对象控制命令，学习凉亭制作等；
- 二维、三维建模与修改器，学习手机、床等制作；
- 材质与贴图：具体学习材质编辑器的使用；
- 三维动画制作，学习弹跳小球动画制作；
- 摄影机与灯光：学习摄影机的建立与修改，摄影机动画制作，学习灯光的布局和使用；
- 粒子特效与环境效果，学习雪、消防栓喷射等特效制作，学习雾、火等环境效果制作。

*** 软件工程

i.e. Software Engineering

3 学分 96 学时

本课程是计算机科学与技术系为全校本科生开设的一门重要的计算机专业基础课，目的是培养学生的软件工程素质，提高学生的软件开发能力。本课程以 _软件生命周期_ 的主要活动为主线，从软件及软件工程的历史和发展、软件开发过程、需求分析、软件设计、程序编码、软件测试、软件维护、软件项目管理、标准及规范等方面全面介绍软件工程的基本理论、方法、技术和工具。

*** 数据结构

i.e. Data Structure

4 学分 64 学时

数据结构是计算机科学的关键内容，也是构建高效算法的必要基础。其覆盖的知识，在相关专业的课程体系中始终处于核心位置。本课程旨在围绕 _各类数据结构的设计与实现_ ，揭示其中的规律原理与方法技巧；同时针对 _算法设计及其性能分析_ ，使学生了解并掌握主要的套路与手法。讲授的主题从基础的数据结构，一直延伸至新近的研究成果。

*** 计算机组成与系统结构

i.e. Computer Organization and Architecture

4 学分 64 学时

本课程是为非计算机专业的本科生开设的 _计算机硬件课程_ ，包括 3 部分教学内容。作为预备性知识，将简单介绍数字电路与计算机中的某些部件的逻辑线路设计，课程主体知识是讲解简单、完整的计算机组成原理和内部运行机制，包括数据表示和运算器部件、指令系统和控制器部件、层次存储器系统、输入输出系统（总线、接口）和输入输出设备等。在系统地讲解通用原理性知识的基础上，始终把教学组研制的、硬软件配置比较完整的 16 位字长的教学计算机系统的实例贯穿到教学的各个环节之中，处理好学习理论和提高实践能力、计算机部件和整机、硬件和软件的关系。作为提高性的知识，课程将介绍计算机体系结构的基本知识和概念，重点在于了解如何通过指令流水线技术和并行计算机体系结构来提高计算机系统的性能。

*** 计算机网络

i.e. Computer Networks

3 学分 48 学时

本课程的教学目标是使学生了解计算机网络的基本知识，掌握计算机网络的基本概念和应用方法。介绍计算机网络的概念、原理和体系结构，着重讲述物理层、数据链路层、介质访问子层、网络层、传输层和应用层的基本原理和协议，掌握以 TCP/IP 协议族为主的网络协议结构，初步培养在 LAN 上的实际工作能力，并且了解网络新技术的最新发展。

*** 计算科学与生涯规划

i.e. Computer science and career design

2 学分 32 学时

计算机行业发展简史，包括机械计算机发展史，机电计算机发展史，电子计算机发展史，通用计算机发展史中的重要人物、事件及产业发展状况。互联网发展简史，互联网产业发展状况。专业就业情况，市场对人才的需求等。

*** 计算机系统研讨

i.e. Seminar on Computer Systems

1 学分 16 学时

现代计算机系统，种类多样、结构复杂，在设计这些系统的时候所遵循的基本原则是什么？本课程介绍 _计算机系统中的基本设计原则_ ，在避免大量编程细节的前提下，讲解了计算机系统处理复杂性的一些基本方法，如抽象、命名、模块化、分层等，并以实际系统为例加以说明。本课程还介绍了在实际系统中出现的可靠性、原子性、一致性等问题和相应的解决方案，使得学生掌握计算机系统设计所需的全局思维和设计方法论，为今后在计算机系统方向的深入学习打下坚实的基础。

*** 数据科学导论

i.e. Introduction to Data Science

2 学分 32 学时

本课程将介绍数据科学的理论基础，包括统计基础，及分析方法，包括数据获取、数据处理（数据清洗、数据采样等）、数据挖掘、机器学习等。具体，本课程将介绍 1）数据获取，2）数据清洗，3）数据采样，4）数据表示与建模，5）数据分析平台与系统。6）大数据应用。

*** 多媒体设计与制作

i.e. Design and Realization of Multimedia

3 学分 48 学时

讲述多媒体应用的基本概念和基础知识，从创作层面掌握三个多媒体应用软件（Photoshop、 Audition、 AE）。

*** C++ 语言程序设计

i.e. C++ Programming

3 学分 80 学时

本课程为高级语言程序设计的入门课程，完全针对零起点的学生，可作为其他信息类相关课程的基础课。内容包括面向对象程序设计的基本概念和方法、C++ 的基本语法和编程方法、集成开发环境、常用数据结构和算法简介、C++ 标准模板库简介。

*** 操作系统

i.e. Modern Operating Systems

3 学分 48 学时

本课程作为计算机学科的核心课程，主要讲述现代计算机操作系统的基础知识，分析现代主流操作系统的基本原理与实现技术。课程主要目的是帮助学生掌握操作系统的基本原理，解决系统问题。主要内容包括当代操作系统的基本概念、演化与机制，进程与线程管理，CPU 调度，内存管理，输入输出，文件系统，设备驱动程序，网络技术等。

*** Java 语言程序设计

i.e. JAVA and Object-Oriented Programming

3 学分 80 学时

本课程介绍 Java 语言程序设计基础知识，包括 Java 的基础语法、面向对象的程序设计方法、GUI 程序和多线程程序开发方法简介、数据库访问及网络程序设计方法简介。

*** 并行计算基础

i.e. Fundamental of Parallel Computing

2 学分 56 学时

当今计算技术的发展使得并行计算成为一种通用计算技术。本课程通过理论讲解、实例分析帮助学生了解并行计算的概念、理论和经典技术方法，掌握初步的并行程序设计和分析方法，体验实际程序开发过程，推动并行计算技术的普及和应用。教学内容按照基础知识、并行编程、性能优化、以及并行程序开发的顺序来组织授课，每部分辅以丰富案例和工具介绍，便于学生建立感性认识，由浅入深地掌握知识、方法和工具，并可以学以致用。同时，课程还及时将业界的最新动态以及最新的并行计算技术介绍给学生。课程项目从项目立题、方案设计、实现、文档等多方面给予细致的指导，鼓励学生凭兴趣选取项目，开展有研究性的探索。

*** 网页设计与制作

i.e. Web Design and Produce

2 学分 48 学时

本课程主要介绍客户端的网页制作技术。主要内容有：网页制作基础知识、HTML、使用 Dreamweaver 制作网页和网站管理、网页图像加工（Photoshop、网页动画制作（Flash、 样式表（CSS）、Javascript。

*** 数据挖掘：方法与应用

i.e. Data Mining： Methodology and Application

3 学分 48 学时

数据挖掘是针对不同专业领域的数据处理和分析的必然结果，已经成为一项必不可少的数据处理方法与技术。本课程从应用的角度，全面、系统地介绍数据挖掘的基本概念、基本方法和基本技术，以及数据挖掘的最新进展。要求学生通过本课程的学习，认识数据挖掘在当今数据分析与处理中的作用，了解数据仓库的原理和实现方法以及数据挖掘的整体结构，掌握数据预处理方法和数据挖掘基本方法，熟悉数据挖掘的基本原理和发展方向。通过课程实验，要求学生能够将理论与实践相结合。

*** 计算机程序设计基础（Python）

i.e. The Fundamentals of Computer Programming （Python）

2 学分 64 学时

本课程为计算机程序设计基础核心课程之一，以 Python 语言程序设计的内容为基础，注重讲解程序设计的概念、方法和思路。课程的主要目标是帮助学生掌握基本的编程技术，提高逻辑思维能力、系统思维能力和抽象思维能力。本课程的主要内容包括：程序设计的基本概念、Python 语言基础与 Python 程序结构、数学与数值计算、字符串与文件操作、列表与数据操作、函数与递归函数、分支结构与循环结构、程序设计方法学、面向过程程序设计与面向对象程序设计、图形编程、算法设计等。

*** 离散数学

i.e. Discrete Mathematics

3 学分 48 学时

本课程是软件学院的基础数学课程，以离散量为研究对象，即面向计算机科学的应用，同时欲揭示相关理论的内在联系。本课程主要包括以下内容：

（1）数理逻辑部分：包括命题及其符号化、命题公式及其真值、命题逻辑等值演算、命题逻辑的推理理论、谓词的概念及其符号化、谓词等值演算，范式以及谓词的推理理论等内容。

（2）集合论：包括集合的概念、运算；关系及其表示，关系的性质，等价关系与等价类、相容关系、偏序关系以及格与布尔代数；函数的概念，反函数和复合函数，模糊子集等内容；实数集合与集合的基数、康托定理以及连续统假设等。

3 学分 48 学时

本课程分两大部分，一部分是图论（2 学分），另一部分为代数结构（1 学分）。课程主要包括以下内容：

（1）图论部分：详细讨论图的基本定义及代数表示，道路与回路的基本概念、基本原理包括欧拉图与哈密顿图的判别方法、基本算法包括旅行商问题、最短路径、关键路径、中国邮路等；树的基本回路矩阵、割集矩阵、支撑树生成和计数等；最后讲与图论相关的四个典型应用与算法包括平面图、图的着色、图的匹配与网络流等。

（2）代数结构部分：主要介绍代数系统的定义和性质，半群、群及子群、陪集等的定义和性质及其判定，介绍特殊的群类及群的同态、同构基本定理，介绍环和域的概念及基本性质，环的同态、同构基本定理等内容。

*** 数值分析

i.e. Numerical Analysis

3 学分 48 学时

本课程介绍适合于计算机使用的、求解各种常用数学问题的数值计算方法，研究各种数学问题求解的数值计算方法，讲解如何用计算机解决实际数学问题的方法。主要内容包括线性方程组的解法（包括直接法与迭代法），插值求值法（拉格郎日插值，牛顿插值，分段低次插值，三次样条插值），函数逼近计算，数值积分与数值微分的近似计算，方程求根的近似解法，以及矩阵特征值与特征向量的计算。这些算法与计算机紧密结合。

*** 初等数论

i.e. Elementary Number Theory

2 学分 32 学时

本课讲述了数论和密码学所需的数学基础知识。介绍了整数、素数、同余、积性函数、原根、二次剩余、中国剩余定理以及素性测试等概念以及其在密码学中的应用，顺便介绍了密码学的基本知识，比如 RSA 公钥密码体制的设计原理。

*** 汇编语言程序设计

i.e. Assembly Language Programming

3 学分 48 学时

本课程与计算机组成原理、编译原理、操作系统、计算机系统结构等课程组成计算机系统核心课程；同时汇编语言程序设计作为本科生接触到的第一门系统课程，被定位为该课组的入门课，起到“承上启下”的作用。

具体的，授课对象都是掌握了 C 语言的本科生，从他们相对熟悉的语言入手可以加深对汇编的理解与印象。更重要的，汇编语言是高级语言在机器层面的表示，掌握这两种语言的对应可以将程序的执行与计算机的工作过程紧密联系起来，直接体现汇编语言本身固有的特点，即它是最易于将“程序”和“机器”统一起来的一个结合点。进一步的通过对不同汇编代码的解释来给出微体系结构方面的差异，可以为后续课程，如编译原理、计算机组成原理等提供一些先导知识，并有利于学生从整个系统构成的角度来理解各个课程的作用与位置。在内容选择上从系统角度“自上而下/自下而上”的来组织汇编课程内容，将汇编定位为软硬件的接口、处理器对外提供的功能规格。具体的，从 C 语言角度、处理器结构角度讲解汇编语言的语义及其某些新汇编指令出现的原因，并突出汇编优化程序的特点以及“反汇编”的应用。并引入了 MIPS 汇编的内容来为同一课组的后续课程打下语言基础。

总的内容包括以下几个方面：

#+BEGIN_EXAMPLE
1、基本知识
- 汇编语言与计算机系统结构
- 各类指令集初步
- 数制与整数表示
- 浮点数表示

2、X86 汇编
- 80x86 计算机组织与保护模式
- X86 指令系统与寻址方式
- C 与 X86 汇编
- X86 汇编语言程序格式与基本编程

3、MIPS 汇编
- MIPS 计算机组织初步
- 指令系统介绍
- 汇编代码与异常处理
- MIPS 内存管理与汇编编程
#+END_EXAMPLE

*** 数据库技术及应用

i.e. Principal and Application of Database

3 学分 48 学时

本课程通过案例教学和项目研发训练，了解和掌握数据处理以及数据库可视化相关技术，旨在通过数据处理感受数据化的价值。内容包括：1.数据库技术基本知识；2.SQL 语言；3.数据处理；4、数据可视化。

*** 计算机程序设计基础

i.e. Programming Fundamentals

3 学分 48 学时

本课程为计算机基础核心课程，以 C 语言程序设计内容为基础，注重讲解程序设计的概念、方法和思路，培养同学的基本编程能力，以及逻辑思维和抽象思维能力。主要内容包括 C 语言基础与程序控制结构、结构化程序设计，函数与模块化、库与接口设计、复合数据类型（数组、指针、结构体）、文件、算法设计、递归程序设计、数据抽象、程序抽象等。

*** 基于 Linux 的 C++

i.e. C++ Programming for Linux

4 学分 96 学时

本课程为计算机基础课程，以 Linux 操作系统下的 C++ 语言程序设计为基础，注重讲解程序设计的概念、方法和思路，培养同学的基本编程能力，以及逻辑思维和抽象思维能力。本课程主要内容包括 C++ 基本概念，C++ 语法规范，结构化程序设计，函数与模块化、库与接口设计、复合数据类型、文件、算法设计、递归程序设计、数据抽象、程序抽象、面向对象程序设计、Linux 系统编程（进程编程、线程编程和网络编程）等。

*** 设计导论

i.e. Introduction to VLSI Systems

2 学分 32 学时

结合当前集成电路设计和 EDA 的发展，从非微电子专业掌握 VLSI 设计知识和技术的需求出发，以集成电路系统设计为背景，系统地、全面地介绍 VLSI 设计知识和方法，主要包括： VLSI 最新发展情况、VLSI 设计领域的最新发展情况和 EDA 领域的发展情况介绍； VLSI 设计方法及基本流程， VLSI 工艺、器件、电路、系统、及版图设计基础介绍，半定制、全定制设计方法，VLSI 设计方法学，IC CAD 方法、优化算法及 EDA 软件系统，应用 EDA 软件工具进行 VLSI 设计的方法等。

*** 程序设计基础

i.e. Fundamentals of Programming

3 学分 48 学时

《程序设计基础》是计算机系本科生进入大学接触到第一门专业课。该课程强调在解题的实践中，掌握程序设计的基本概念，基本思想和基本方法，运用好计算机这一智力工具，提高分析问题和解决问题的能力；要求学生强化动手实践，引导理性思维和理性实践，养成良好的编程习惯。本课程改革了作业评价和考试方法，设计开发了练习题网上提交与自动评测系统，期中和期末采用上机解题，自动评测，真正考核学生的实际编程能力。

*** 操作系统

i.e. Operating Systems

3 学分 48 学时

操作系统是计算机系统中负责管理各种软硬件资源的核心系统软件，为应用软件运行提供良好的环境。掌握操作系统的基本原理及其核心技术是研究型大学计算机专业本科毕业生的基本要求。本课程是计算机专业核心课，以主流操作系统为实例，以教学操作系统 ucore 为实验环境，讲授操作系统的概念、基本原理和实现技术，为学生从事操作系统软件研究和开发，以及充分利用操作系统功能进行应用软件研究和开发打下扎实的基础。

*** 数据库系统概论

i.e. Introduction to Database Management System

2 学分 32 学时

本课程主要分四大部分：
- 数据库的设计与应用：主要讲述 E-R 模型和关系模型；
- 数据库管理系统的数据存储：主要讲述文件组织和索引结构；
- 数据库管理系统的核心技术：主要讲述查询处理、事务管理和并发控制；
- 数据库管理系统的体系结构扩展和前沿研究。

*** 数学逻辑电路

i.e. Digital Logic Circuit

3 学分 48 学时

本课程由 4 部分组成，分别是：逻辑代数与逻辑函数化简、组合逻辑分析与设计、同步时序逻辑分析与设计、可编程逻辑设计。

- 逻辑函数化简主要介绍逻辑代数的基本原理和逻辑函数化简方法，重点是卡诺图化简与表格化简法；
- 组合逻辑部分结合计算机系统中常用的译码器、编码器、数据选择器、ALU 等组合逻辑器件，介绍组合逻辑电路原理、分析与设计方法；
- 同步时序逻辑部分主要讲解触发器的工作原理与各种触发方式的时钟配合、寄存器的结构、重点介绍各种同步计数器和移位寄存器的分析、设计及应用；
- 可编程逻辑部分涉及可编程逻辑的原理、以及 PLA、PAL、GAL 等常用可编程器件的结构与应用。

*** 编译原理

i.e. Principles and Practice of Comopiler Construction

2 学分 64 学时

本课程是为计算机科学与技术专业的本科生开设的。课程主要介绍编译程序构造的原理与实践。课程涵盖的内容包括：词法分析，语法分析，语义分析，语法制导翻译，运行时环境，代码生成和优化等。课程实验是一个 4~5 阶段的项目，其内容是基于课程给定框架设计和实现一个完整的小型面向对象语言的编译程序。

*** 数学图像处理

i.e. Digital Image Processing

2 学分 32 学时

数字图象处理的基本原理和技术，基本部分：图象的获取、显示与表示，色彩空间，直方图处理，线性变换，几何变换，形态学处理，边缘检测；图象变换与特征抽取（KL/PCA），图象分割，图象压缩。高级部分：图像内容理解，图像检索，基于深度学习的图像分析，图像推荐等。

*** 信息检索

i.e. Information Retrieval

2 学分 32 学时

本课程讲授文本信息检索的基本方法与技术，主要内容包括：信息检索的重要性及其应用、信息检索基本框架、文本分析及自动标引、潜在语义分析、信息检索模型、相关反馈、检索评价、检索界面与可视化、Web 信息检索、信息抽取等。

*** 数学系统设计自动化

i.e. Design Automation for Digital Systems

2 学分 72 学时

本课程面向计算机、电子工程、自动化等有关专业的本科生。主要目标为：为 EDA（Electronic DesignAutomation， EDA）工具的开发者提供基本理论基础；为 EDA 工具的使用者提供专业知识，学生通过完成一系列任务而初步掌握数字系统的设计方法。本课程着重介绍数字系统设计自动化各个领域的基础理论和最新发展，包括硬件描述语言 VHDL、模拟技术、逻辑综合和高层次综合、故障诊断以及形式验证等。

*** 计算机图形学基础

i.e. Fundamentals of Computer Graphics

2 学分 32 学时

本课程是为计算机系本科生开设的选修课，旨在介绍计算机图形学的基本概念、理论、方法和系统，主要内容包括：直线扫描转换的 DDA 算法、中点算法、Bresenham 算法，多边形扫描转换算法，裁剪，消隐，曲线曲面造型，实体造型，光照模型，明暗处理，纹理，光线跟踪算法等。

*** 计算机系统结构

i.e. Computer Architecture

3 学分 64 学时

“计算机系统结构”是以计算机系统的外部特性为主来讲解计算机系统基本结构的一门学科。所谓外部特性是指编写出能够在计算机系统上正确运行的程序所必须了解到的计算机系统的特性。“计算机系统结构”研究的主要内容包括：数据表示、寻址方式、指令系统、中断系统、存储系统、输入输出系统、流水线处理机、超标量处理机、互连网络、向量处理机、并行处理机和多处理机等。

*** 计算机网络原理

i.e. Theory of Computer Network

3 学分 48 学时

介绍计算机网络的概念、原理和体系结构，着重讲述物理层、数据链路层、介质访问子层、网络层、传输层和应用层的基本原理和协议。通过实验，掌握计算机网络的基本实现技术。

*** 计算机网络安全技术

i.e. Computer Network Security Technology

2 学分 32 学时

本课程从网络安全在全球的使用、市场现状为起点，使学生能够清楚的了解目前安全市场的发展趋势，从而能够更有目的和针对性的去学习网络安全技术。本课程除了介绍重点防火墙、入侵检测、防病毒等基本的网络安全技术外，还将详细介绍加密、认证和虚拟专用网 VPN 技术。在课程中将结合具体的网络安全方案进行讲解，使学生在学习过程中能够感觉到学有所用。

*** 存储技术基础

i.e. Storage Technology Foundations

2 学分 48 学时

《存储技术基础》课程面向信息学院本科生/研究生，介绍国际上先进的技术和业界先进的应用示例。围绕网络环境下海量信息的组织、管理、可靠性与可用性等热点需求，讲解以下内容：信息管理的复杂性，存储系统体系结构，网络存储，业务连续性，数据中心，示例分析 。

*** 搜索引擎技术基础

i.e. Fundamentals of Search Engine Technology

2 学分 32 学时

搜索引擎是网络用户最主要的信息获取工具之一，搜索引擎的设计和实现过程，综合运用了当今互联网应用领域最高水平的研究成果。学生通过对本课程的学习，既可以掌握与互联网实际应用密切相关的网络信息检索、网络数据挖掘等方面的知识，更有助于培养其综合运用知识解决问题的能力。

本课程的教学目的包括：了解搜索引擎的基本原理、产品设计思路及商业运营模式；掌握互联网数据环境的特点及其对搜索引擎设计实现过程的影响；深入学习并掌握大规模商用搜索引擎的系统设计要点及其核心算法。

*** 计算机组成与系统结构

i.e. Computer Organization and Architecture

4 学分 64 学时

这门课是将软件和硬件理论结合讲述的教程，覆盖计算机组成、体系结构、处理器设计、编程优化等多方面内容，从程序员以及软件运行的角度去看计算机系统，讲解其基本组成及其工作原理，分析计算机组成对系统性能的影响。这对于理解计算机内部结构，从而更好的掌握程序编写、优化技能，掌握全面的计算机基础知识，帮助学生建立计算机整机系统的完整概念是很有裨益的，还有助于为进一步学习计算机体系结构、操作系统、编译器和网络互联打下基础。

*** 媒体计算

i.e. Media Computing

2 学分 32 学时

本课程是为计算机系本科生开设的选修课，旨在介绍媒体计算的基本概念、理论、方法及其应用，主要内容包括：媒体计算的基本概念、图像和视频内容编辑、图像和视频非真实感绘制等。

*** 现代密码学

i.e. Introduction to Modern Cryptogrophy

2 学分 32 学时

该课程作为密码学的入门课程，介绍了从古典密码算法到现代密码算法的设计和分析理念。课程主要分为古典密码、对称加密算法、Hash 函数和消息认证码、序列密码与伪随机数、公钥密码学以及基本的身份认证协议这 6 个部分。该课程内容是密码学的核心内容。
