#+SETUPFILE: ../theme-rose.setup
#+DATE: <2020-06-19 Fri 12：29>
#+TITLE: CS Classes

** 计算机科学与技术系

*** 计算机辅助设计技术基础

i.e. Fundamentals of Computer Aided Design

3 学分 48 学时

本课程坚持基础知识与实践相结合的指导思想，在学习计算机辅助设计的基础知识的同时，学习三维动画软件的操作与使用。

基础知识包括：图形变换、自由曲线曲面造型技术、三维几何造型、真实感图形。应用软件：3DSMAX 2013 软件的操作。这两部分内容是有机联系的，基础知识对理解 3DSMAX 软件中的基本概念提供帮助；通过 3DSMAX 软件的操作与实践，能够更好地理解有关基本概念并学习到一门很实用的技术（三维造型与动画）。

课程的基础知识包括：
- 二维图形变换：主要讲授图形的基本变换（平移、旋转、缩放等）及组合变换。简介自由曲线曲面造型技术的基本思想和技术，该技术主要应用在非规则几何模型建模。
- 三维几何造型：主要讲授规则三维模型的几种表示方法，介绍当前主流的三维造型方法，最后介绍自然景物的造型方法。
- 真实感图形：介绍计算机生成真实感图形的绘制流程：局部光照模型、全局光照模型、纹理映射技术、图形绘制技术等。

课程的 3DSMAX 软件内容包括：
- 操作界面及对象控制命令，学习凉亭制作等；
- 二维、三维建模与修改器，学习手机、床等制作；
- 材质与贴图：具体学习材质编辑器的使用；
- 三维动画制作，学习弹跳小球动画制作；
- 摄影机与灯光：学习摄影机的建立与修改，摄影机动画制作，学习灯光的布局和使用；
- 粒子特效与环境效果，学习雪、消防栓喷射等特效制作，学习雾、火等环境效果制作。

*** 软件工程

i.e. Software Engineering

3 学分 96 学时

本课程是计算机科学与技术系为全校本科生开设的一门重要的计算机专业基础课，目的是培养学生的软件工程素质，提高学生的软件开发能力。本课程以 _软件生命周期_ 的主要活动为主线，从软件及软件工程的历史和发展、软件开发过程、需求分析、软件设计、程序编码、软件测试、软件维护、软件项目管理、标准及规范等方面全面介绍软件工程的基本理论、方法、技术和工具。

*** 人工智能导论

i.e. Introduction of Artificial Intelligence

2 学分 32 学时

本课程为非计算机专业的本科生介绍人工智能的基本原理和方法的入门课程。课程主要讲述人工智能的一般性原理和基本思想，介绍问题求解常用的搜索方法和策略（包括无信息搜索、有信息搜索、对抗搜索等）、知识表示方法（包括命题逻辑、非确定性的表示和推理等）、机器学习方法（包括监督学习、非监督学习等）、以及人工智能相关的应用和最新进展。课程不仅介绍一般性的原理和方法，同时包含实践性的作业，通过编程帮助学生理解、掌握一些人工智能的基本方法。通过期末大作业，学生将课堂学习的理论和方法用于解决现实中的实际问题，特别鼓励与学生自己的专业相结合。

*** 数据结构

i.e. Data Structure

4 学分 64 学时

数据结构是计算机科学的关键内容，也是构建高效算法的必要基础。其覆盖的知识，在相关专业的课程体系中始终处于核心位置。本课程旨在围绕 _各类数据结构的设计与实现_ ，揭示其中的规律原理与方法技巧；同时针对 _算法设计及其性能分析_ ，使学生了解并掌握主要的套路与手法。讲授的主题从基础的数据结构，一直延伸至新近的研究成果。

*** 面向计算机科学的离散数学 A

i.e. Discrete Mathematics in Computer Science A

3 学分 48 学时

本课程为计算机科学理论的基础课程，是面向计算机科学的离散数学结构的第一部分。内容主要包括数理逻辑与集合论两大部分。本课程系统介绍数理逻辑与朴素集合论的基础知识，包括：命题逻辑和谓词逻辑、定理的推理演算和机器证明方法，集合和二元关系的基本运算和性质、任意集合中的函数及其性质，无穷集合的基数，以及上述知识在计算机科学中的应用。

*** 面向计算机科学的离散数学 B

i.e. Discrete Mathematics in Computer Science B

3 学分 48 学时

本课程面向各专业计算机辅修课学习的学生，主要讲授图论的基本概念，道路与回路，树，平面图与图的着色，匹配与网络流，图的连通性等内容。

*** 计算机组成与系统结构

i.e. Computer Organization and Architecture

4 学分 64 学时

本课程是为非计算机专业的本科生开设的 _计算机硬件课程_ ，包括 3 部分教学内容。作为预备性知识，将简单介绍数字电路与计算机中的某些部件的逻辑线路设计，课程主体知识是讲解简单、完整的计算机组成原理和内部运行机制，包括数据表示和运算器部件、指令系统和控制器部件、层次存储器系统、输入输出系统（总线、接口）和输入输出设备等。在系统地讲解通用原理性知识的基础上，始终把教学组研制的、硬软件配置比较完整的 16 位字长的教学计算机系统的实例贯穿到教学的各个环节之中，处理好学习理论和提高实践能力、计算机部件和整机、硬件和软件的关系。作为提高性的知识，课程将介绍计算机体系结构的基本知识和概念，重点在于了解如何通过指令流水线技术和并行计算机体系结构来提高计算机系统的性能。

*** 计算机网络

i.e. Computer Networks

3 学分 48 学时

本课程的教学目标是使学生了解计算机网络的基本知识，掌握计算机网络的基本概念和应用方法。介绍计算机网络的概念、原理和体系结构，着重讲述物理层、数据链路层、介质访问子层、网络层、传输层和应用层的基本原理和协议，掌握以 TCP/IP 协议族为主的网络协议结构，初步培养在 LAN 上的实际工作能力，并且了解网络新技术的最新发展。

*** 下一代互联网

i.e. Next Generation Internet

2 学分 32 学时

互联网取得了巨大成功，已成为现代社会最重要的信息基础设施之一，广泛渗透国民经济和社会各领域，对经济和社会发展的作用日益加大，同时也成为影响国防和国家安全的重要因素。随着网络规模的持续膨胀和新的网络应用需求不断增长，目前互联网发展面临了许多挑战，主要是互联网取得了巨大成功，对经济和社会发展的作用日益加大，同时也成为影响国防和国家安全的重要因素。目前互联网的发展在地址空间、网络安全等方面面临着许多挑战。

下一代互联网主要特征包括：能提供更大的 IP 地址空间；数据传输速度更快；互联网络更安全可信；支持大规模实时交互式的网络视频通信；支持大规模移动和漫游服务；更易于管理、盈利模式更清晰等。

*** 计算科学与生涯规划

i.e. Computer science and career design

2 学分 32 学时

计算机行业发展简史，包括机械计算机发展史，机电计算机发展史，电子计算机发展史，通用计算机发展史中的重要人物、事件及产业发展状况。互联网发展简史，互联网产业发展状况。专业就业情况，市场对人才的需求等。

*** 数字娱乐中的媒体技术

i.e. Digital Media Technology for Digital Entertainment

1 学分 16 学时

数字化已渗透到娱乐业的各个方面，从内容的拍摄中的数字电影摄像机、数字后期处理、动画和特效生成、游戏编程，到内容的网络传输、传播和消费都已经全面的完成向数字化的转型。在这一生态系统中，从传感器到终端，乃至于版权保护，都设计到很多计算机科学问题和技术。本课程以数字娱乐内容的生态为背景，定义相关科学问题，介绍其主要研究路径和成果，为今后的学习、研究、就业的合理选择提供背景知识。

*** 人工智能前沿探讨

i.e. Artificial Intelligence and its Frontiers

1 学分 16 学时

人工智能是让机器具有智能和学习能力的学科。过去 60 多年，人工智能在理论与应用方面均取得了显著的进展和成功，尤其是近期深度学习的突破进展。作为一门多学科交叉的新兴学科，人工智能具有精妙的核心思想和算法，在应用方面已经发展成为很多科学与工程领域（如计算机视觉、语音识别、自然语言处理、互联网智能搜索等）中解决复杂问题的首选方案，并且在智能处理大数据方面发挥着越来越重要的角色。本课程将通过讲述典型算法与应用案例，介绍人工智能的核心思想；通过回顾历史、分析现状与趋势，启发学生的兴趣；通过研讨交流，引导学生掌握思考问题和解决问题的能力。

*** 计算机系统研讨

i.e. Seminar on Computer Systems

1 学分 16 学时

现代计算机系统，种类多样、结构复杂，在设计这些系统的时候所遵循的基本原则是什么？本课程介绍 _计算机系统中的基本设计原则_ ，在避免大量编程细节的前提下，讲解了计算机系统处理复杂性的一些基本方法，如抽象、命名、模块化、分层等，并以实际系统为例加以说明。本课程还介绍了在实际系统中出现的可靠性、原子性、一致性等问题和相应的解决方案，使得学生掌握计算机系统设计所需的全局思维和设计方法论，为今后在计算机系统方向的深入学习打下坚实的基础。

*** 深度学习导论

i.e. Introduction to Deep Learning

2 学分 32 学时

深度学习是人工智能学科的一个重要组成部分，是近年来人工智能再次腾飞的主要推动力之一。本课程将介绍深度学习的概念和历史，深入讲解其基本原理和典型模型，并讨论其研究前沿。具体内容包括多层感知机、卷积神经网络、Elman 反馈神经网络、长短时记忆网络、Hofield 网络、受限波尔兹曼机、深度信念网络、生成对抗网络等模型，以及他们在计算机视觉、语音处理和自然语言处理等领域的应用。课程还将简要讲授 python 编程基础和神经网络的工具软件 Tensorflow 的使用方法。学期末学生需要针对一个实际的应用问题（自选+教师提供结合）构建自己的模型进行求解，撰写和提交课程报告，并通过海报展示。

*** 数据科学导论

i.e. Introduction to Data Science

2 学分 32 学时

本课程将介绍数据科学的理论基础，包括统计基础，及分析方法，包括数据获取、数据处理（数据清洗、数据采样等）、数据挖掘、机器学习等。具体，本课程将介绍 1）数据获取，2）数据清洗，3）数据采样，4）数据表示与建模，5）数据分析平台与系统。6）大数据应用。

*** 多媒体设计与制作

i.e. Design and Realization of Multimedia

3 学分 48 学时

讲述多媒体应用的基本概念和基础知识，从创作层面掌握三个多媒体应用软件（Photoshop、 Audition、 AE）。

*** C++ 语言程序设计

i.e. C++ Programming

3 学分 80 学时

本课程为高级语言程序设计的入门课程，完全针对零起点的学生，可作为其他信息类相关课程的基础课。内容包括面向对象程序设计的基本概念和方法、C++ 的基本语法和编程方法、集成开发环境、常用数据结构和算法简介、C++ 标准模板库简介。

*** 操作系统

i.e. Modern Operating Systems

3 学分 48 学时

本课程作为计算机学科的核心课程，主要讲述现代计算机操作系统的基础知识，分析现代主流操作系统的基本原理与实现技术。课程主要目的是帮助学生掌握操作系统的基本原理，解决系统问题。主要内容包括当代操作系统的基本概念、演化与机制，进程与线程管理，CPU 调度，内存管理，输入输出，文件系统，设备驱动程序，网络技术等。

*** VC++ 面向对象与可视化程序设计

i.e. Object Oriented and Visual Programming

3 学分 96 学时

本课程介绍 Visual C++ 可视化编程的方法及其实现。主要介绍 windows 编程和 MFC 编程。内容包括 windows 编程构架和 MFC 编程构架以及事件驱动消息响应机制，知识点涵盖绘图、文字、键盘鼠标、常用控件、菜单、工具栏的消息响应的应用等以及基于对话框的应用程序和基于文档的应用程序的编写。为在教学过程中提高学生的应用开发能力，本课程针对每个知识点配有一个实例开发作为授课的例子，通过实例让学生全面掌握“面向对象与可视化程序设计”的思路、开发技巧与体系。

*** Java 语言程序设计

i.e. JAVA and Object-Oriented Programming

3 学分 80 学时

本课程介绍 Java 语言程序设计基础知识，包括 Java 的基础语法、面向对象的程序设计方法、GUI 程序和多线程程序开发方法简介、数据库访问及网络程序设计方法简介。

*** 办公自动化软件应用

i.e. Application of office software

2 学分 40 学时

本门课程讲述的办公软件包括：字处理软件、电子表格软件和演示文稿制作软件、图像处理、动画制作等。课程除讲解软件的基本功能与使用外，通过对一些实例的深入讲解，快熟掌握讲授内容的练习设计，使同学尽快掌握常用软件的实用技能，进一步提高软件的应用水平。

*** 并行计算基础

i.e. Fundamental of Parallel Computing

2 学分 56 学时

当今计算技术的发展使得并行计算成为一种通用计算技术。本课程通过理论讲解、实例分析帮助学生了解并行计算的概念、理论和经典技术方法，掌握初步的并行程序设计和分析方法，体验实际程序开发过程，推动并行计算技术的普及和应用。教学内容按照基础知识、并行编程、性能优化、以及并行程序开发的顺序来组织授课，每部分辅以丰富案例和工具介绍，便于学生建立感性认识，由浅入深地掌握知识、方法和工具，并可以学以致用。同时，课程还及时将业界的最新动态以及最新的并行计算技术介绍给学生。课程项目从项目立题、方案设计、实现、文档等多方面给予细致的指导，鼓励学生凭兴趣选取项目，开展有研究性的探索。

*** 网页设计与制作

i.e. Web Design and Produce

2 学分 48 学时

本课程主要介绍客户端的网页制作技术。主要内容有：网页制作基础知识、HTML、使用 Dreamweaver 制作网页和网站管理、网页图像加工（Photoshop、网页动画制作（Flash、 样式表（CSS）、Javascript。

*** 嵌入式系统设计与应用

i.e. Embedded system design and Applications

2 学分 32 学时

本课程从未来世界对计算机技术的需求入手，介绍嵌入式系统的基本概念和一些典型应用场景，介绍嵌入式设备的设计方法与技术，通过让同学完成一个系统设计方案和部分设计，并通过课堂讨论加深对课程的理解。

*** 数据挖掘：方法与应用

i.e. Data Mining： Methodology and Application

3 学分 48 学时

数据挖掘是针对不同专业领域的数据处理和分析的必然结果，已经成为一项必不可少的数据处理方法与技术。本课程从应用的角度，全面、系统地介绍数据挖掘的基本概念、基本方法和基本技术，以及数据挖掘的最新进展。要求学生通过本课程的学习，认识数据挖掘在当今数据分析与处理中的作用，了解数据仓库的原理和实现方法以及数据挖掘的整体结构，掌握数据预处理方法和数据挖掘基本方法，熟悉数据挖掘的基本原理和发展方向。通过课程实验，要求学生能够将理论与实践相结合。

*** 计算机程序设计基础（Python）

i.e. The Fundamentals of Computer Programming （Python）

2 学分 64 学时

本课程为计算机程序设计基础核心课程之一，以 Python 语言程序设计的内容为基础，注重讲解程序设计的概念、方法和思路。课程的主要目标是帮助学生掌握基本的编程技术，提高逻辑思维能力、系统思维能力和抽象思维能力。本课程的主要内容包括：程序设计的基本概念、Python 语言基础与 Python 程序结构、数学与数值计算、字符串与文件操作、列表与数据操作、函数与递归函数、分支结构与循环结构、程序设计方法学、面向过程程序设计与面向对象程序设计、图形编程、算法设计等。

*** 离散数学（1）

i.e. Discrete Mathematics（1）

3 学分 48 学时

本课程为计算机科学与技术系本科生的专业基础课程，是面向计算机科学的离散数学结构的第一部分。内容主要包括数理逻辑与集合论两大部分。本课程系统介绍数理逻辑与集合论的基础知识，包括：命题逻辑和谓词逻辑、定理的推理演算和机器证明方法，集合和二元关系的基本运算和性质、任意集合中的函数及其性质，无穷集合的基数，以及上述知识在计算机科学中的应用。

*** 离散数学（2）

i.e. Discrete Mathematics（2）

3 学分 48 学时

内容包括图的基本概念，欧拉回路，哈密顿回路，最短路，树，平面图与图的着色，匹配与网络流，图的连通性，群、环、域、布尔代数。内容丰富、精炼、算法多且分析深入，习题丰富且难度恰当。

*** 数值分析

i.e. Numerical Analysis

3 学分 48 学时

本课程介绍适合于计算机使用的、求解各种常用数学问题的数值计算方法，研究各种数学问题求解的数值计算方法，讲解如何用计算机解决实际数学问题的方法。主要内容包括线性方程组的解法（包括直接法与迭代法），插值求值法（拉格郎日插值，牛顿插值，分段低次插值，三次样条插值），函数逼近计算，数值积分与数值微分的近似计算，方程求根的近似解法，以及矩阵特征值与特征向量的计算。这些算法与计算机紧密结合。

*** 初等数论

i.e. Elementary Number Theory

2 学分 32 学时

本课讲述了数论和密码学所需的数学基础知识。介绍了整数、素数、同余、积性函数、原根、二次剩余、中国剩余定理以及素性测试等概念以及其在密码学中的应用，顺便介绍了密码学的基本知识，比如 RSA 公钥密码体制的设计原理。

*** 汇编语言程序设计

i.e. Assembly Language Programming

3 学分 48 学时

本课程与计算机组成原理、编译原理、操作系统、计算机系统结构等课程组成计算机系统核心课程；同时汇编语言程序设计作为本科生接触到的第一门系统课程，被定位为该课组的入门课，起到“承上启下”的作用。

具体的，授课对象都是掌握了 C 语言的本科生，从他们相对熟悉的语言入手可以加深对汇编的理解与印象。更重要的，汇编语言是高级语言在机器层面的表示，掌握这两种语言的对应可以将程序的执行与计算机的工作过程紧密联系起来，直接体现汇编语言本身固有的特点，即它是最易于将“程序”和“机器”统一起来的一个结合点。进一步的通过对不同汇编代码的解释来给出微体系结构方面的差异，可以为后续课程，如编译原理、计算机组成原理等提供一些先导知识，并有利于学生从整个系统构成的角度来理解各个课程的作用与位置。在内容选择上从系统角度“自上而下/自下而上”的来组织汇编课程内容，将汇编定位为软硬件的接口、处理器对外提供的功能规格。具体的，从 C 语言角度、处理器结构角度讲解汇编语言的语义及其某些新汇编指令出现的原因，并突出汇编优化程序的特点以及“反汇编”的应用。并引入了 MIPS 汇编的内容来为同一课组的后续课程打下语言基础。

总的内容包括以下几个方面：

#+BEGIN_EXAMPLE
1、基本知识
- 汇编语言与计算机系统结构
- 各类指令集初步
- 数制与整数表示
- 浮点数表示

2、X86 汇编
- 80x86 计算机组织与保护模式
- X86 指令系统与寻址方式
- C 与 X86 汇编
- X86 汇编语言程序格式与基本编程

3、MIPS 汇编
- MIPS 计算机组织初步
- 指令系统介绍
- 汇编代码与异常处理
- MIPS 内存管理与汇编编程
#+END_EXAMPLE

*** 数据库技术及应用

i.e. Principal and Application of Database

3 学分 48 学时

本课程通过案例教学和项目研发训练，了解和掌握数据处理以及数据库可视化相关技术，旨在通过数据处理感受数据化的价值。内容包括：1.数据库技术基本知识；2.SQL 语言；3.数据处理；4、数据可视化。

*** 计算机程序设计基础

i.e. Programming Fundamentals

3 学分 48 学时

本课程为计算机基础核心课程，以 C 语言程序设计内容为基础，注重讲解程序设计的概念、方法和思路，培养同学的基本编程能力，以及逻辑思维和抽象思维能力。主要内容包括 C 语言基础与程序控制结构、结构化程序设计，函数与模块化、库与接口设计、复合数据类型（数组、指针、结构体）、文件、算法设计、递归程序设计、数据抽象、程序抽象等。

*** 基于 Linux 的 C++

i.e. C++ Programming for Linux

4 学分 96 学时

本课程为计算机基础课程，以 Linux 操作系统下的 C++ 语言程序设计为基础，注重讲解程序设计的概念、方法和思路，培养同学的基本编程能力，以及逻辑思维和抽象思维能力。本课程主要内容包括 C++ 基本概念，C++ 语法规范，结构化程序设计，函数与模块化、库与接口设计、复合数据类型、文件、算法设计、递归程序设计、数据抽象、程序抽象、面向对象程序设计、Linux 系统编程（进程编程、线程编程和网络编程）等。

*** C++ 程序设计实践

i.e. The Practice of C++ Programming

2 学分 33 学时

课程针对有一定 C 语言基础的同学，以授课结合实践的形式，使同学熟悉 C++语言，并理解其中体现的面向对象编程思想。预期掌握的关键知识点包括：类与对象、封装、继承、多态、模板、命名空间与类库、异常处理、以及 Qt 程序设计初步。

*** 计算机程序设计基础

i.e. Programming Fundamentals

2 学分 64 学时

本课程讲解程序设计的基础知识、基本概念，面向过程及面向对象的程序设计思想，C/C++基础语法，及程序设计方法。

*** 人工智能导论

i.e. Introduction to Artificial Intelligence

2 学分 32 学时

本课程主要介绍人工智能问题求解方法的一般性原理和基本思想。主要讲述一般的搜索问题，包括盲目搜索和启发式搜索等；博弈问题，包括博弈树搜索、蒙特卡洛树搜索等；人工智能中的谓词演算及其应用，包括归结方法、基于归结的问答系统、基于规则的逆向演绎系统；高级搜索，包括局部搜索方法、模拟退火方法和遗传算法等；统计学习方法，包括决策树、支持向量机等；深度学习方法，包括神经元网络基础、全连接网络、卷积神经网络、BP 算法等。

*** 信号处理原理

i.e. Principles of Signal Processing

3 学分 48 学时

本课程讨论数字信号处理的基本原理和方法，主要包括：连续时间傅里叶变换、离散傅里叶变换、Z 变换、数字滤波器的原理和设计实现等。另外还简单介绍数字信号处理的一些最新技术，包括小波变换、稀疏表示等。

*** 高性能计算导论

i.e. Intoduction to Hign Performance Computing

2 学分 32 学时

本课程采用英语教材，英语授课及所有教学活动均用英语为语言工具的形式。课程的内容是介绍高性能计算的基本概念、方法和工具。它包括了高性能计算机的体系结构的简单介绍，并行程序设计模型、程序性能模型、性能调试技术、并行程序设计和编程的方法，并行程序开发平台和工具以及并行算法的介绍。

*** 设计导论

i.e. Introduction to VLSI Systems

2 学分 32 学时

结合当前集成电路设计和 EDA 的发展，从非微电子专业掌握 VLSI 设计知识和技术的需求出发，以集成电路系统设计为背景，系统地、全面地介绍 VLSI 设计知识和方法，主要包括： VLSI 最新发展情况、VLSI 设计领域的最新发展情况和 EDA 领域的发展情况介绍； VLSI 设计方法及基本流程， VLSI 工艺、器件、电路、系统、及版图设计基础介绍，半定制、全定制设计方法，VLSI 设计方法学，IC CAD 方法、优化算法及 EDA 软件系统，应用 EDA 软件工具进行 VLSI 设计的方法等。

*** 程序设计基础

i.e. Fundamentals of Programming

3 学分 48 学时

《程序设计基础》是计算机系本科生进入大学接触到第一门专业课。该课程强调在解题的实践中，掌握程序设计的基本概念，基本思想和基本方法，运用好计算机这一智力工具，提高分析问题和解决问题的能力；要求学生强化动手实践，引导理性思维和理性实践，养成良好的编程习惯。本课程改革了作业评价和考试方法，设计开发了练习题网上提交与自动评测系统，期中和期末采用上机解题，自动评测，真正考核学生的实际编程能力。

*** 操作系统

i.e. Operating Systems

3 学分 48 学时

操作系统是计算机系统中负责管理各种软硬件资源的核心系统软件，为应用软件运行提供良好的环境。掌握操作系统的基本原理及其核心技术是研究型大学计算机专业本科毕业生的基本要求。本课程是计算机专业核心课，以主流操作系统为实例，以教学操作系统 ucore 为实验环境，讲授操作系统的概念、基本原理和实现技术，为学生从事操作系统软件研究和开发，以及充分利用操作系统功能进行应用软件研究和开发打下扎实的基础。

*** 数据库系统概论

i.e. Introduction to Database Management System

2 学分 32 学时

本课程主要分四大部分：
- 数据库的设计与应用：主要讲述 E-R 模型和关系模型；
- 数据库管理系统的数据存储：主要讲述文件组织和索引结构；
- 数据库管理系统的核心技术：主要讲述查询处理、事务管理和并发控制；
- 数据库管理系统的体系结构扩展和前沿研究。

*** 计算机科学导论

i.e. Computer Science： An Overview

2 学分 32 学时

本课综合阐述计算机科学作为一个专业的科学基础。主要讲授：1、计算机结构基础，了解计算机存储数位与逻辑运算的理论基础、存储程序式计算机结构的概念；2、算法 数据结构=程序，了解为支持高效求解问题的算法建立数据信息的逻辑结构与存储结构，以及使算法的程序表达在计算机上实现的编译过程；3、算法机器的潜能，了解人工智能基本原理的基础上讨论未来人机关系、了解计算理论基本概念基础上讨论计算机可解与能解问题的范围。本课综合阐述上述内容，使得学生了解计算机科学核心概念及其相关性，建立对计算机科学知识体系的基本概览。本课涉及相关内容的历史，但并不以时序为讲述线索，而是将其结合进课程内容中。本课以课堂讲授为主，学生练习有两种主要方式，一是纸笔推演，二是提供一个 8 位虚拟仿真计算机，以理解和验证所讲授的概念和方法。课程主要参考书为英文原版教材，不但有利于学生理解专业术语，而且有利于以后专业课程的学习。

*** 人机交互理论与技术

i.e. Human Computer Interaction Theory and Technology

2 学分 32 学时

人机交互研究关于人机之间的信息交流的原理和方法，是计算机学科体系中的一个重要组成部分，以认知科学为交互设计的理论基础，同时又是以信息技术作为交互设计的技术基础。本课程讲授人的能力范围以及信息处理能力的模型化表示，人机界面模式的沿革、特点和支持工具，交互效率的评价模型，新型交互模式和交互接口的设计，使学生了解和掌握人机交互的基本原理、交互效率的提高途径，体验创新性交互技术研究的重要性。

*** 人工神经网络

i.e. Artificial Neural Networks

2 学分 32 学时

本课程主要是介绍人工神经网络的基本原理，包括网络的学习机制，网络结构、各种特点等。从介绍典型的感知器（单层感知器和多层感知器）开始，引深到目前受到极大关注的深度神经网络。课程内容包括网络结构，学习算法，在图像和文本处理领域中的典型应用等等。最后一部分将介绍自组织神经网络（Kohonen网络和 ART 网络），hopfild 网络等等经典的，有特色的网络，开拓同学们的视野。本课程没有考试，但是有多个实用最新的平台如 TensorFlow 进行编程实现的作业，还有一个基于深度学习方法完成某种任务的程序实现大作业。

*** 程序设计与训练

i.e. Java Program Design and Training

2 学分 64 学时

课程主要包括下列内容：Java 语言的发展及相关技术的介绍，Java 技术和平台在网络计算及电子商务中的应用介绍；Java 语言的基础知识、主要特点、设计思想、Java 虚拟机、垃圾回收机制、安全性的保证机制；Java 语言的基本语法规范，包括标识符、关键字、数据类型、表达式和流控制，程序基本结构；面向对象技术的基本特点，Java 语言的面向对象特性，类和对象的概念，封装性、继承性、多态性，Java 语言的特殊属性；Java 程序的例外处理机制和方法；Java 语言的输入/输出处理机制和方法，常用的输入/输出方法，输入/输出处理的应用； AWT 界面设计的基本方法，常用的组件类库，图形用户界面的事件处理模型和方法，JFC 介绍，Swing 图形界面设计；Java Applet 程序设计，Applet 程序的特点，运行机制，与浏览器的集成，安全机制的使用；多线程程序设计，进程和线程的联系和区别，多线程程序设计的一般方法，线程的生命周期，线程状态的控制，多线程的互斥和同步；Java 语言的网络编程技术和应用，Socket 程序设计，Client/Server 程序设计；Java 的 Servlet 和 JSP（Java Server Page）技术；JavaBeans 和 RMI。

*** 数学逻辑电路

i.e. Digital Logic Circuit

3 学分 48 学时

本课程由 4 部分组成，分别是：逻辑代数与逻辑函数化简、组合逻辑分析与设计、同步时序逻辑分析与设计、可编程逻辑设计。逻辑函数化简主要介绍逻辑代数的基本原理和逻辑函数化简方法，重点是卡诺图化简与表格化简法；组合逻辑部分结合计算机系统中常用的译码器、编码器、数据选择器、ALU 等组合逻辑器件，介绍组合逻辑电路原理、分析与设计方法；同步时序逻辑部分主要讲解触发器的工作原理与各种触发方式的时钟配合、寄存器的结构、重点介绍各种同步计数器和移位寄存器的分析、设计及应用；可编程逻辑部分涉及可编程逻辑的原理、以及 PLA、PAL、GAL 等常用可编程器件的结构与应用。

*** 数学逻辑设计

i.e. Digital Logic Design

3 学分 48 学时

本课程的重点是培养学生的基础理论知识，增强学生的实验方法和实验技能。主要讲授逻辑代数基础、组合和时序电路的分析设计方法、存储器和可编程逻辑器件，以及数字系统设计方法等。实验内容包括基础型和设计型实验，尽可能为学生提供发展的空间，在实践中理解理论知识，提出新方案。 目的是理论知识和动手能力双提高。

*** 编译原理

i.e. Principles and Practice of Comopiler Construction

2 学分 64 学时

本课程是为计算机科学与技术专业的本科生开设的。约 32 学时的课堂讲授和 32 学时的编程实验。课程主要介绍编译程序构造的原理与实践。课程涵盖的内容包括：词法分析，语法分析，语义分析，语法制导翻译，运行时环境，代码生成和优化等。课程实验是一个 4~5 阶段的项目，其内容是基于课程给定框架设计和实现一个完整的小型面向对象语言的编译程序。

*** 操作系统专题训练

i.e. Operation System Special Topic Trainning

2 学分 32 学时

操作系统是计算机系统中负责管理各种软硬件资源的核心系统软件，是计算机专业的重要基础教学内容，具备操作系统核心功能设计和实现能力是对研究型大学计算机专业学生的基本要求。本课程是“操作系统”的专题训练课程，属于实践课程系列。通过操作系统核心代码的分析和功能扩展实现，增强学生对操作系统基本概念和原理的理解和运用能力，为学生今后从事大型系统软件的研究与开发奠定坚实的基础。

*** 编译原理专题训练

i.e. Programming Languages Laboratory

2 学分 40 学时

本课程是计算机科学与技术系为本系本科生开设的一门重要的计算机限选课，目的是加强学生对系统软件的理解和把握，培养学生的软件工程素质，提高学生的软件开发能力。本课程基于工业界广泛采用的自由软件 GCC、以程序语言编译系统框架为主线安排实验，通过实验掌握词法分析、语法分析、中间表示、优化和目标代码生成以及交叉编译等方面的基本技术和相关工具。

*** 数据库专题训练

i.e. Database Special Topic Training

2 学分 32 学时

本课程主要讲授数据库最新研究进展，一方面让学生了解前沿课题，一方面实现最新研究算法，锻炼学生实践能力。主要讲授数据库基础、数据库近似检索、近似连接、近似抽取、即敲即得式检索、地图搜索、时空数据处理、时空数据挖掘。

*** 程序设计训练

i.e. Programing and Training

2 学分 64 学时

本课程的定位是：通过大量的编程实践，使学生更加深刻的理解并巩固面向对象程序设计的基本原理和方法，熟练掌握程序设计环境及其应用，培养学生程序设计过程中的分析、设计、编码、调试和优化等基本方法和能力。在此基础上，提高学生解决实际问题的模块化思想和适应新的编程语言的能力，养成良好的编程风格及编程习惯。课程涵盖了编程的基本知识，面向对象编程的基本思想，Linux 下编程的基本技术，多线程编程，windows图形界面编程（QT 编程），脚本语言编程和网络编程，学习新语言的能力，以及相应的实践训练，主要内容包括：

#+BEGIN_EXAMPLE
（1）基本语法、良好的编程风格、图形界面编程 QT 等；
（2）Linux 环境编程、多线程编程、网络编程等；
（3）Python 语言介绍、搜索引擎介绍；
#+END_EXAMPLE

*** 面向对象程序设计基础

i.e. Foundation of Object-Oriented Programming

2 学分 48 学时

面向对象已成为计算机领域的主流技术之一，课程将以 C++ 语言为基础，详细介绍用 C++ 进行面向对象的程序设计的核心思想。C++ 语言设计成熟、理论体系完整，全面支持面向对象设计思想，应用十分广泛。以 C++进行面向对象程序设计，可以保证程序的高度可复用性、可维护性，有利于团队协作，便于复杂系统的设计与实现。本课程为程序设计基础课程的后续拓展课程，要求学生在已掌握的计算机语言程序设计的基础上，能进一步拓展到面向对象的 C++ 编程。通过本课程的学习，要求学生全面掌握用 C++ 语言进行面向对象程序设计的基本概念和方法，建立面向对象的思维模式，并能训练地用 C++ 实现这些思路。具体内容包括：C++ 面向对象的基本语法、面向对象的编程方法和思想，以及设计模式等内容。要求学生理解对象、继承、多态、模板等技术手段。通过完成规定的设计练习，加强和提高程序调试的水平和能力。通过完成大作业，掌握有一定规模的程序设计方法，培养团队协作的素质。

*** 智能硬件设计

i.e. Intelligent Device Design

2 学分 32 学时

智能硬件设计课程每年春季学期授课，在技创辅智能硬件方向的第二学期开设，属于创新创业辅修专业方向的必修核心课程之一，课程的教学内容包括教授学生学习在智能硬件平台上实现输入输出感知和控制，以及利用云端的服务实现图像识别、语音识别等智能处理，同时课程拟聘请企业导师指导学生学习和使用智能硬件平台更为强大的信息处理功能。课程的教学环节将在原理上介绍各种模拟传感器、数字传感器、常用 I/O 接口、摄像头、麦克风、Speaker、显示器、舵机和各种电机的工作原理，从应用方法上介绍上述设备的控制使用方法，并通过一个智能私密保管箱做为教学实验用例，指导学生如何利用所学知识设计一款具有智能人机交互能力、环境感知能力和对现实世界的驱动能力。学生通过在本课程的学习中掌握智能硬件的软硬件基本技能，为在“专业创新实践”课程中实现一个有自己创意的创新型智能硬件打下良好的基础。

*** 系统分析与控制

i.e. System Analysis and Control

3 学分 48 学时

本课程主要讲授基于传递函数的经典控制理论，初步介绍基于状态空间的现代控制理论方法。授课内容：

#+BEGIN_EXAMPLE
（1）控制系统的数学模型，包括微分方程、传递函数、状态方程、结构图和模型转换；
（2）控制系统的时域分析，包括时间响应计算、控制系统的稳定性、能控性、能观性和动态性能；
（3）控制系统的频域分析，包括 Nyguist 稳定判据、Bode 图、开环 Bode 图与控制系统的性能；
（4）控制系统的设计，包括串联校正、并联校正和复合校正；（5）采样控制系统理论，包括采样系统的模型描述、性能分析和系统设计。
#+END_EXAMPLE

*** 数学图像处理

i.e. Digital Image Processing

2 学分 32 学时

数字图象处理的基本原理和技术，基本部分：图象的获取、显示与表示，色彩空间，直方图处理，线性变换，几何变换，形态学处理，边缘检测；图象变换与特征抽取（KL/PCA），图象分割，图象压缩。高级部分：图像内容理解，图像检索，基于深度学习的图像分析，图像推荐等。

*** 计算机组成原理

i.e. Computer Organization

4 学分 64 学时

本课程主要介绍简单、完整、单处理器计算机的基本组成原理和内部运行机制，并探索硬、软件之间相互作用的关系，以及如何有效利用硬件提高系统性能。教学内容包括算术逻辑部件（ALU）、指令系统、控制器设计、高速缓冲存储器和虚拟存储器、总线和外部设备等，尽力体现设计计算机时在成本、性能和复杂性之间的权衡。教学中，采用教学计算机 TEC-2000 作为示例，并要求学生在实验中，以 16 位教学计算机及其软件模拟系统为基础，独立设计和实现一台 8 位的计算机。

*** 信息检索

i.e. Information Retrieval

2 学分 32 学时

本课程讲授文本信息检索的基本方法与技术，主要内容包括：信息检索的重要性及其应用、信息检索基本框架、文本分析及自动标引、潜在语义分析、信息检索模型、相关反馈、检索评价、检索界面与可视化、Web 信息检索、信息抽取等。

*** 多媒体技术基础及应用

i.e. Fundamentals and Applications of Multimedia Technology

2 学分 32 学时

《多媒体技术基础及应用》是计算机科学与技术专业的一门本科生选修课。本课程综合讲述了多媒体计算机的基本原理、关键技术及其开发和应用。课程讲授的主要内容有：多媒体计算机的定义及其关键技术；视频音频信息的获取与处理；多媒体数据压缩编码技术；多媒体计算机硬件及软件系统结构。通过学习这些内容，为今后开展多媒体领域的研究和开发工作，打下良好的基础。

*** 数学系统设计自动化

i.e. Design Automation for Digital Systems

2 学分 72 学时

本课程面向计算机、电子工程、自动化等有关专业的本科生。主要目标为：为 EDA（Electronic DesignAutomation， EDA）工具的开发者提供基本理论基础；为 EDA 工具的使用者提供专业知识，学生通过完成一系列任务而初步掌握数字系统的设计方法。本课程着重介绍数字系统设计自动化各个领域的基础理论和最新发展，包括硬件描述语言 VHDL、模拟技术、逻辑综合和高层次综合、故障诊断以及形式验证等。

*** 计算机图形学基础

i.e. Fundamentals of Computer Graphics

2 学分 32 学时

本课程是为计算机系本科生开设的选修课，旨在介绍计算机图形学的基本概念、理论、方法和系统，主要内容包括：直线扫描转换的 DDA 算法、中点算法、Bresenham 算法，多边形扫描转换算法，裁剪，消隐，曲线曲面造型，实体造型，光照模型，明暗处理，纹理，光线跟踪算法等。

*** 形式语言与自动机

i.e. Formal Languages and Automata

2 学分 32 学时

课程主要包含如下三部分内容：

#+BEGIN_EXAMPLE
（1）有限状态自动机，正规表达式，正规语言；
（2）上下文无关文法，下推自动机，上下文无关语言；
（3）图灵机，问题的不可解性、难解性和复杂性等计算理论初步知识。
#+END_EXAMPLE

*** 计算机系统结构

i.e. Computer Architecture

3 学分 64 学时

“计算机系统结构”是以计算机系统的外部特性为主来讲解计算机系统基本结构的一门学科。所谓外部特性是指编写出能够在计算机系统上正确运行的程序所必须了解到的计算机系统的特性。“计算机系统结构”研究的主要内容包括：数据表示、寻址方式、指令系统、中断系统、存储系统、输入输出系统、流水线处理机、超标量处理机、互连网络、向量处理机、并行处理机和多处理机等。

*** 模式识别

i.e. Pattern Recognition

2 学分 32 学时

本课程为机器学习、人工智能、计算机视觉、图像识别等领域的基础课程。本课程从模式、识别、分类等概念开始，系统地讲授了统计模式识别的理论、方法与最新进展，并通过课堂作业和项目研究，逐步深入理解模式分类概念与掌握模式分类方法。本课程的主要内容包括：贝叶斯决策理论、贝叶斯置信网络、神经网络、玻尔兹曼机、监督机器学习与无监督机器学习、聚类等。

*** 现代控制技术

i.e. Modern Control Technology

2 学分 36 学时

本课程主要讲述现代控制技术中最核心的内容，包括：控制系统的状态空间描述及其运动分析方法；线性控制系统的能控性、能观性及李雅普诺夫稳定性分析；控制系统的综合与最优控制基础；以时间触发网络时间同步问题为例的现代控制应用实践。

*** 数据挖掘

i.e. Data Mining

2 学分 32 学时

互联网已进入大数据时代，人们迫切需要新的技术和工具，以便从海量的数据中自动地、智能地抽取隐藏于这些数据中的知识和信息。因此，数据挖掘是大规模数据处理的必然结果，目前已经成为一项必不可少的数据处理技术。通过此课程的学习，使学生了解数据挖掘的研究内容、基本理论及其应用。学习数据挖掘的各个阶段的主要任务和最新技术，掌握其中关键算法和技术，为将来从事海量数据处理和挖掘方面的工作和研究奠定必要的基础。

主要内容包括：

#+BEGIN_EXAMPLE
（1）数据挖掘技术概述
（2）数据的表示和可视化，介绍如何将现实世界相关数据表示成计算机能够处理的格式，同时能够精确表示对象的语义和特点。简单介绍数据可视化方法；
（3）数据预处理技术，介绍如何通过数据预处理获得高质量的数据，重点关注介绍噪音数据处理、数据集成以及数据转换技术，
（4）数据仓库技术，简单介绍数据仓库的基本技术，包括数据仓库的数据模型、数据仓库体系结构，以及数据仓库的应用技术；
（5）关联规模挖掘，介绍挖掘数据之间关联的经典算法；
（6）分类，介绍挖掘从有标注分类数据中学习分类器，利用分类器对新数据进行分类的的分类算法；
（7）聚类，介绍将大规模数据分析为数据组（类簇）的集合，以揭示数据的分布的聚类分析方法。
（8）数据挖掘趋势，介绍数据挖掘未来的发展趋势和挑战问题。
#+END_EXAMPLE

*** 计算机网络原理

i.e. Theory of Computer Network

3 学分 48 学时

介绍计算机网络的概念、原理和体系结构，着重讲述物理层、数据链路层、介质访问子层、网络层、传输层和应用层的基本原理和协议。通过实验，掌握计算机网络的基本实现技术。

*** 机器学习概论

i.e. Introduction to Machine Learning

2 学分 32 学时

机器学习是研究如何利用已有经验来设计模型和系统以自动解决具体问题的学科，在社会经济、日常生活、工农业生产等各个方面都有丰富的应用背景。特别是近年来在互联网信息挖掘与管理、生物信息学、商业用户分析、航空航天自动控制等方面的应用都有长足进展。课程讲授机器学习的核心思想、经典算法和重要理论，注重基础知识和前沿发展的结合。包括概念学习、决策树学习、贝叶斯学习、基于实例的学习、聚类、集成学习、相关学习理论（评估假设、VC 维、可能近似正确学习等）、及部分前沿专题讲座（如深度学习、强化学习等）等。课程强调和培养主动思考、积极动手和分析的习惯与能力。要求学生已预先掌握了概率统计和人工智能的基本知识。

*** 嵌入式系统

i.e. Embedded System

2 学分 32 学时

嵌入式系统就是专用可计算系统，随着微电子技术、计算机技术、网络技术的飞速发展，嵌入式系统将走入我们日常学习、生产、生活的每一个角落，构成无所不在的计算环境。本课程主要介绍嵌入式系统的基本构造原理，讲解最新的嵌入式系统设计的相关技术。整个课程将从嵌入式系统的硬件平台、嵌入式系统的软件平台和嵌入式系统的开发平台三个方面进行讲解，并配合难易分配合理的 5-6 个实验来加深学生对知识的掌握，并增强他们的动手能力。

*** 计算机网络安全技术

i.e. Computer Network Security Technology

2 学分 32 学时

本课程从网络安全在全球的使用、市场现状为起点，使学生能够清楚的了解目前安全市场的发展趋势，从而能够更有目的和针对性的去学习网络安全技术。本课程除了介绍重点防火墙、入侵检测、防病毒等基本的网络安全技术外，还将详细介绍加密、认证和虚拟专用网 VPN 技术。在课程中将结合具体的网络安全方案进行讲解，使学生在学习过程中能够感觉到学有所用。

*** 存储技术基础

i.e. Storage Technology Foundations

2 学分 48 学时

《存储技术基础》课程面向信息学院本科生/研究生，介绍国际上先进的技术和业界先进的应用示例。围绕网络环境下海量信息的组织、管理、可靠性与可用性等热点需求，讲解以下内容：信息管理的复杂性，存储系统体系结构，网络存储，业务连续性，数据中心，示例分析 。

*** 搜索引擎技术基础

i.e. Fundamentals of Search Engine Technology

2 学分 32 学时

搜索引擎是网络用户最主要的信息获取工具之一，搜索引擎的设计和实现过程，综合运用了当今互联网应用领域最高水平的研究成果。学生通过对本课程的学习，既可以掌握与互联网实际应用密切相关的网络信息检索、网络数据挖掘等方面的知识，更有助于培养其综合运用知识解决问题的能力。

本课程的教学目的包括：了解搜索引擎的基本原理、产品设计思路及商业运营模式；掌握互联网数据环境的特点及其对搜索引擎设计实现过程的影响；深入学习并掌握大规模商用搜索引擎的系统设计要点及其核心算法。

*** 计算机组成与系统结构

i.e. Computer Organization and Architecture

4 学分 64 学时

这门课是将软件和硬件理论结合讲述的教程，覆盖计算机组成、体系结构、处理器设计、编程优化等多方面内容，从程序员以及软件运行的角度去看计算机系统，讲解其基本组成及其工作原理，分析计算机组成对系统性能的影响。这对于理解计算机内部结构，从而更好的掌握程序编写、优化技能，掌握全面的计算机基础知识，帮助学生建立计算机整机系统的完整概念是很有裨益的，还有助于为进一步学习计算机体系结构、操作系统、编译器和网络互联打下基础。

*** 计算机网络管理

i.e. Computer Network Management

2 学分 32 学时

课程将包含以下教学内容：
1. 计算机网络原理。从网络工程实现和运行管理的视角介绍计算机网络及其工程实现；
2. 网络管理基础知识。讲授网络管理体系结构、网络测量、网络管理协议、网络管理系统和网络运行管理等基本原理和技术；
3. 网络管理工程案例介绍和研讨。介绍清华大学校园网、中国下一代互联网核心网 CNGI-CERNET2 和跨欧亚信息网 TEIN 等网络的实际运行管理工作和经典案例，研讨 IPv6、移动互联网、云计算、物联网、人工智能等新技术发展带来的网络管理的新问题和新需求；
4. 网络管理实践。课程将安排网络管理工程实验和实践活动，覆盖通信基础设施管理、IP 网络管理、网络测量、简单网络管理协议 SNMP 应用、网络运行管理等领域；
5. 课程大作业。根据同学自身兴趣特点和专业背景，安排课程大作业研究题目，引导同学独立思考和解决工程问题，进行创新研究尝试。

*** 网络安全工程与实践

i.e. Network security engineering and practice

2 学分 32 学时

#+BEGIN_EXAMPLE
一、概要：介绍计算机和网络安全相关的常见威胁、攻击和基本概念
二、TCP/IP 协议安全、网络入侵检测与逃逸
三、安全通信协议与 TLS
四、Web 安全
五、软件安全
#+END_EXAMPLE

课程注重安全技术领域的实践，在每一章的内容之后都有动手编程序或者动手操作的训练。同时，通过攻击与防御技术的对抗，培养学生的批判性思维、发现问题、解决问题的能力。

*** 媒体计算

i.e. Media Computing

2 学分 32 学时

本课程是为计算机系本科生开设的选修课，旨在介绍媒体计算的基本概念、理论、方法及其应用，主要内容包括：媒体计算的基本概念、图像和视频内容编辑、图像和视频非真实感绘制等。

*** 现代密码学

i.e. Introduction to Modern Cryptogrophy

2 学分 32 学时

该课程作为密码学的入门课程，介绍了从古典密码算法到现代密码算法的设计和分析理念。课程主要分为古典密码、对称加密算法、Hash 函数和消息认证码、序列密码与伪随机数、公钥密码学以及基本的身份认证协议这 6 个部分。该课程内容是密码学的核心内容。

*** 人工智能技术

i.e. Artificial Intelligence Technology

2 学分 32 学时

本课程主要介绍人工智能问题求解方法的一般性原理和基本思想，培养学生用所学知识求解实际问题的能力。主要讲述一般的搜索问题，包括盲目搜索和启发式搜索等；对抗搜索，包括α-β剪枝算法，蒙特卡洛树搜索方法等；人工智能中的谓词演算及其应用；高级搜索方法，包括局部搜索方法、模拟退火算法和遗传算法等；统计学习方法，包括朴素贝叶斯方法，支持向量机方法和决策树方法等；神经网络与深度学习等。

*** 人机交互理论与实践

i.e. Theory and Practive of Human Computer Interaction

2 学分 32 学时

《人机交互理论与技术》课程针对技术创新创业辅助专业的学生开设，主要讲授人机交互的基本理论、关键技术、集成方法、测试评价和创新实践等。课程将采用教师讲授和学生实践交叉进行的教学方式，课堂讲授环节包括授课和讨论两个方面，实践环节则包括实验和科研创新活动两个方面。通过本课程使学生掌握人机交互所涉及的多学科基础知识、理论方法和关键技术，具备将理论知识应用在智能硬件开发中的综合应用能力，通过科技创作实现团队协作、创新能力的培养。

*** 认知机器人

i.e. Congnive Robotics

1 学分 16 学时

主要从主动感知、认知和经验（记忆）学习的角度，讲授认知机器人哲学、心理学与物理学基础、人类视听触觉主动感知机理、机器人视听触觉信息的深度表征与融合、基于经验学习的灵巧操作以及人机共融操作的理论方法，开展移动平台主动感知的实验教学和课外实验，与当前前沿的研究热点和方向结合，开阔学时的视野，并为学生未来从事新一代机器人的研究奠定基础。

** 软件学院

*** 算法设计及其复杂性分析

i.e. Algorithm Design and Complexity Analysis

2 学分 32 学时

本课程目的是使同学初步熟悉《算法设计及其复杂性分析》有趣而富有挑战的科研方法，经历其过程，了解如何设计算法解决实际问题，并能进入计算复杂度这一重要而神奇的世界。教学方式是教师首先介绍关于算法的基本理论并布置相应的问题，这些问题在不同的学期会有所不同，不过都具有很强的理论价值和应用价值，其中曾经包括素数判定问题（2002 年印度理工学院的一位教授和两位本科生在该问题上取得重要进展，成果发表在《Science》上）、利用前缀翻转操作进行整数排序问题（微软创始人比尔盖茨（Bill Gates）在读大学二年级时在该问题取得有意义进展，成果发表在《Discrete Mathematics》上）等一些有趣而易于理解的问题。

选课指导：本课程富有挑战性，需要较大的勇气以及强烈的求知欲望和上进心。请想混学分或担心学习力不从心的同学不要选这门课。据往届同学反映，本课程作业量大，富有挑战性，需要付出很大的努力，最终收获也很大。部分同学的研究成果已经形成了学术论文。

*** 大数据技术导论

i.e. Introduction of Big Data Technology

1 学分 16 学时

近年来，“大数据”作为一个新的名词在众多领域得到关注，包括科学、工程、医疗、卫生、经济、商业，乃至整个社会。除了直观理解的“规模大” （Volume）特征以外，大数据还具有“高吞吐率” （Velocity）， “多样性”（Variety）， “价值稀疏”（Value）等多个 V 特征。本课程侧重引导学生对大数据管理与应用的学习兴趣和路线。从当前行业现状出发，利用一些真实案例，向学生介绍行业中大数据存在的真实情况，引出一系列大数据所带来的价值与挑战，使得学生对相关背景和存在问题建立初步轮廓。通过介绍大数据相关技术，让学生对大数据管理技术有一个大致了解，从而引导学生对后续相关课程的选则。此外，本课程还将介绍知名大学在大数据研究方面的最新进展，以及潜在的研究方向，激发同学进一步学习研究的热情。

*** 软件文化概论

i.e. Introduction to Software Culture

2 学分 32 学时

软件文化概论课程内容主要包括：“人类计算及计算机的历史、软件的创新与发展、世界软件分类标准、信息产业与智能软件应用及软件未来应用探索”，课程针对软件的产生和发展进行了深刻的论述，目的是让本科生（留学生）同学了解软件的应用与创新所产生的软件文化，对人类的影响和对社会发展的贡献，在课程的经典案例中学生会了解世界许多著名的科学家和工程师在软件领域中的里程碑贡献，分享他们的成功经验和奋斗的人生成长历程，同时也会了解世界上最具影响力的跨国集团的软件创新文化和历史创新的推动力，培养对经典案例的探究分析能力，建立起软件科学的科学发展观，培养本科生创新能力，培养具有“大国匠人”风范的领军人物，为今后的科学探索与创新打下扎实的基础。

*** 离散数学（1）

i.e. Discrete Mathematics（1）

3 学分 48 学时

本课程是软件学院的基础数学课程，以离散量为研究对象，即面向计算机科学的应用，同时欲揭示相关理论的内在联系。本课程主要包括以下内容：

（1）数理逻辑部分：包括命题及其符号化、命题公式及其真值、命题逻辑等值演算、命题逻辑的推理理论、谓词的概念及其符号化、谓词等值演算，范式以及谓词的推理理论等内容。

（2）集合论：包括集合的概念、运算；关系及其表示，关系的性质，等价关系与等价类、相容关系、偏序关系以及格与布尔代数；函数的概念，反函数和复合函数，模糊子集等内容；实数集合与集合的基数、康托定理以及连续统假设等。

*** 离散数学（2）

i.e. Discrete Mathematics（2）

3 学分 48 学时

本课程分两大部分，一部分是图论（2 学分），另一部分为代数结构（1 学分）。课程主要包括以下内容：

（1）图论部分：详细讨论图的基本定义及代数表示，道路与回路的基本概念、基本原理包括欧拉图与哈密顿图的判别方法、基本算法包括旅行商问题、最短路径、关键路径、中国邮路等；树的基本回路矩阵、割集矩阵、支撑树生成和计数等；最后讲与图论相关的四个典型应用与算法包括平面图、图的着色、图的匹配与网络流等。

（2）代数结构部分：主要介绍代数系统的定义和性质，半群、群及子群、陪集等的定义和性质及其判定，介绍特殊的群类及群的同态、同构基本定理，介绍环和域的概念及基本性质，环的同态、同构基本定理等内容。

*** 程序设计基础

i.e. Programming Methodology

3 学分 48 学时

通过课堂讲授和上机实践相结合的方式，使学生理解程序设计的基本思路和常用编程思想，掌握编写程序解决实际问题的一般方法，并为将来学习专业领域的其他编程语言打下基础。课程由简单的计算程序入手，通过不同的问题引出解决问题所需的程序设计思想和方法，依次讲授程序设计中的代数思维、逻辑思维、模块化思维，枚举法、递推法、动态规划及优先搜索算法等，由浅入深。上机实践过程中，通过分组编程、配对调试等形式，引导学生逐渐形成团队意识，为高年级较大型的课程作业及研究项目打下基础。

*** 程序设计实践

i.e. Practice of Programming

2 学分 32 学时

本门课程的目的是培养学生以自学为主熟练掌握一种新的编程环境和编程语言的能力。培养学生综合运用所学知识，独立对软件的应用需求进行分析和整理，以协作的方式共同完成软件系统的设计，开发和测试，体验软件项目开发的全过程。教学计划主要分两个阶段进行：首先通过一周的教学和练习使学生对.NET 框架和 C 语言有一个基本的入门知识，要求学生通过自学和练习熟练掌握编程环境和编程技巧。在此基础上，学生以三人为单位组成项目小组，根据《实验说明书》的要求以协作的方式完成一个完整的软件项目开发任务。软件项目开发任务具有一定的开放性，要求学生自己对软件的需求进行分析，并进行功能设计。项目开发过程中要求小组人员责任分工明确，开发过程阶段划分明确。在每个阶段学生需要提供详细的技术说明文档并以 ppt 的形式在全班进行报告。项目开发过程应该包括：需求分析和功能设计阶段，系统设计和模型设计阶段，软件演示和测试阶段。

*** 程序设计实训

i.e. Practical Training For Programming

2 学分 64 学时

本课程是以实践为主的高级语言程序设计课程，是软件工程课组的重要组成部分。本课程采用基于问题的教学与学习方法。本课程将设计几类适合学生学习与实践的问题（因为每个学期均需要变更问题，所以具体问题和分类方法可能会有所变化）。问题通常为三大类，例如：基本程序类、平台类和竞赛类。其中基本程序类侧重于面向对象程序设计的一些思维模式、重要知识点、难点或易发生错误的知识点。平台类和竞赛类均侧重于面向对象的程序设计的综合应用，提高学生学习的自主性和学习乐趣。本课程的第一个环节是提出问题。在本课程的第二个环节中，学生将分成为小组，每个小组一般为 3 人，且不超过 3 人。学生通过小组讨论分析并通过面向对象程序设计的方法解决问题。本课程的最后一个环节是汇报、讨论以及讲评，从而培养学生综合应用计算机语言程序设计的能力。

*** 计算机与网络体系结构（1）

i.e. Architecture of Computer and Network（1）

4 学分 64 学时

针对软件工程学科对计算机与网络原理的培养需求，围绕计算机与网络体系结构，讲解的主要知识点包括：计算机中信息表示、机器级指令、 CPU、存储系统组织、计算机网络服务模型、层次结构、各层次通信协议、网络安全、多媒体数据传输、移动网络等内容。本课程培养学生计算思维能力，着重强调数据流、控制流、流水线设计、协议设计、鲁棒数据传输、性能分析等能力。

*** 计算机与网络体系结构（2）

i.e. Architecture of Computer and Network 2

4 学分 64 学时

针对软件工程学科对计算机与网络原理的培养需求，围绕计算机与网络体系结构， 《计算机与网络体系结构2》讲解的主要知识点包括：汇编级机器组织、实时与嵌入式系统、程序设计语言概述、虚拟机、语言翻译简介、语言翻译系统等。教学重点在于从“程序员角度”系统化介绍计算机与网络的基本原理及组织，突出软件与硬件的有效组织。为学生掌握设计与实现计算机、网络和高级程序设计语言的能力打下良好基础。

*** 软件工程（3）

i.e. Software Engineering（3）

5 学分 80 学时

本课程从软件生命周期的角度讲解软件工程的基本概念、基本原理和基本方法，内容涉及开发管理、需求建模、设计实现和测试维护等四大部分的相关基础知识，强调软件工程的根本性和永久性原则，诸如可测试性、软件体系结构、模块化和可复用性等，关注软件系统的复杂性问题以及迭代式的开发方法，重视分析问题与解决问题的能力以及软件工程实践训练，培养学生良好的工程化开发习惯。经过本课程的学习，学生能够掌握软件工程的基础知识，从工程学角度认识软件在大型系统中的设计和应用，具备作为软件工程师从事软件开发所需的专业能力。

*** 软件理论基础（2）：函数式语言程序设计

i.e. Functional Programming

2 学分 32 学时

函数式语言是编程语言的一个重要分支。相比命令式语言（如 C，Java 等），函数式语言更加抽象和简洁，数学特性更强，更贴近于人的直接思维，便于书写出精简且严谨的程序。本课程的讲解基于纯函数式语言Haskell。我们首先介绍基础知识（包括语法、语义等），然后介绍函数式语言的设计方法（包括递归、模式匹配等），再进一步说明函数式语言区别于命令式语言的特点（无副作用、惰性求值、高阶函数等），最后介绍函数式语言在实际工程中的使用方法（Monad 等）。

*** 面向对象程序设计基础

i.e. Fundamentals of Object-Oriented Programming

2 学分 32 学时

面向对象已成为计算机和软件工程领域的主流技术之一，C++语言有效支持面向对象设计思想，应用十分广泛。本课程讲解面向对象的思维模式和程序设计方法，涵盖类、对象、封装、继承、多态、模板、编程规范、设计模式、程序测试和程序调试等内容。本课程的目标是促进学生理解和建立面向对象的程序设计思想，并使得学生掌握采用面向对象程序设计方法来求解实际问题，培养学生问题分析、对象模型建立、代码编写、程序验证，和程序调试的能力，提高程序编写效率和运行效率，提高代码的可复用性和可维护性。

*** 数据结构

i.e. Data Structure

3 学分 48 学时

数据结构是计算机程序设计的重要理论基础，它所讨论的知识内容和提倡的技术方法，无论对进一步学习计算机领域的其它课程，还是对从事软件工程的开发，都有着不可替代的作用。通过本门课程的学习，帮助学生正确理解和掌握数据结构相关的基本概念、基本定理、基本算法及实现方法，了解相关知识在计算机各个领域的重要应用，同时培养学生将实际问题抽象为数学问题并利用相应的数学基本理论分析方法和算法解决问题的能力，使学生学会从问题入手，分析研究计算机处理的数据结构的特性，以便为应用所涉及的数据选择适当的逻辑结构、存储结构及其相应的操作算法，并初步掌握时间和空间分析技术。在理论和实践上都为后续其它计算机专业课程的学习奠定坚实的基础。

*** 大数据技术与应用

i.e. Big Data Technology and Applications

2 学分 32 学时

近年来，大数据在科学、工程、医疗、卫生、经济、商业等众多领域得到关注。除了直观理解的“规模大”（Volume）特征以外，大数据还具有“高吞吐率”（Velocity），“多样性”（Variety），“价值稀疏”（Value）等多个 V 特征。本课程侧重引导学生对大数据技术与应用的学习兴趣和路线。从当前行业现状出发，利用一些真实案例，向学生介绍行业中大数据存在的真实情况，引出一系列大数据所带来的价值与挑战，使得学生对相关背景和潜在应用建立初步轮廓。通过介绍大数据相关技术，让学生对大数据管理技术有一个大致了解。

*** 数据科学导论

i.e. Introduction to Data Science

3 学分 48 学时

本课程介绍数据的基本概念、数据的采集、数据的处理理论和方法。内容包括数据科学介绍；Matlab 的使用；数据的采集与采样；数据的质量分析；数据滤波处理；数据表示；数据关联规则；数据分类；数据的因果分析；时间序列方法；数据回归方法；估计与检测；数据预测方法；数据科学方法的应用。培养学生对数据计算、分析、处理和仿真的能力，为后续数据科学与技术专业课程的学习和实践提供必要的方法和基础。

*** 信息检索技术

i.e. Information Retrieval Technology

3 学分 48 学时

本课程将从计算机科学的角度，从理论和技术两个方面描绘信息检索领域研究的全景，重点讨论信息检索系统中的信息检索算法、信息检索的理论、信息组织方法、信息自动处理方法等。作为一门综合性专业课程，信息检索课程注重培养学生理论与实际相结合的能力，除了要求学生充分了解和掌握信息检索的数学模型、检索评价、查询语言和操作、文本语言与操作多媒体语言及其特征、标引与检索、web 检索和数字图书馆等基本理论和技术外，还希望通过实践提高学生综合运用数学方法对信息对象进行分析、建模、组织和存储的能力。本课程的许多知识点都涉及当前的热点研究问题，课程将在每一个教学单元介绍当前信息检索领域的发展趋势，并组织对有代表性学术研究论文进行讨论和分析，希望通过这种方式，使高年级本科生或研究生能够掌握基本的独立从事科学技术研究的方法和技巧。

*** 前端技术实训课程

i.e. Web Front-end Technology

3 学分 48 学时

本课程由企业有经验的前端开发工程师主讲，结合当前流行的 Web 前端技术以及企业产品开发实践，针对目前 Web 前端富交互领域和 Web 前端展现领域的研究热点和关键技术，课程从多个方面对 Web 前端技术和架构进行讲解和分析，主要内容包括 Web 前端技术发展、浏览器渲染技术、JavaScript 高级程序设计、HTML5&CSS3 技术、NodeJS 基础等主题，使学生掌握 Web 前端技术以及前端工程性的开发方法。

*** 计算机系统软件（2）

i.e. Computer System Software（2）

4 学分 64 学时

本课程围绕数据资源的管理及应用，讲解的知识点主要包括：数据库设计理论、技术与方法；SQL 语言及数据库调用接口、嵌入式 SQL；数据库管理系统体系结构与基础算法；数据质量度量理论。通过这些内容的讲解，并结合开源的数据库管理系统 HSQL 等，使学生具备以下能力：

#+BEGIN_EXAMPLE
1）具备数据库系统设计能力、数据库应用开发和管理能力以及数据库核心系统实现技术与开发能力；
2）具备编写或构造计算机系统软件的基础理论和专门知识。
#+END_EXAMPLE

*** 专业专题训练

i.e. Project Training

5 学分 80 学时

本课程结合实际的工程项目，让学生参与软件系统的整体规划，独立完成模块的需求调研、需求分析、系统设计、系统测试、系统实施、文档编写。

*** 数字媒体（1）：图形与动画

i.e. Digital Media（1）： Computer Graphics and Animation

5 学分 80 学时

#+BEGIN_EXAMPLE
- 光栅图形学；
- 真实感图形学；
- 几何建模；
- 关键帧动画；
- 变形体动画；
- 过程动画；
- 关节动画；
- 基于物理的动画
#+END_EXAMPLE

*** 数字媒体（2）：多媒体

i.e. Digital Media（2）： Multimedia

5 学分 80 学时

本课程一方面讲授数字图像、视频、音频处理的基本概念、基本原理、典型方法、实用技术，同时还介绍图像、音频、视频处理在各个领域中的应用和国际上有关的最新研究成果，包括图像编辑、拼接、变形、着色、抠像、图像检索、以图搜图、视频内容分析、音频管理等，扩展学生们的知识面和学术视野。在课程一开始就帮助学生们建立一个图像处理软件框架和音视频管理与搜索框架，帮助学生们掌握开发数字媒体软件的基本方法和技巧，通过将每堂课介绍的算法不断加入到这个软件中，最终在课程结束时实现一个自己的实用多媒体处理软件，提高编程能力。并通过开放式的大作业，通过自发阅读相关论文，提出新的想法并编程实现，不断提高大作业的质量，激发学生们进一步研究探索的兴趣以及团队协作的能力，为学生今后从事多媒体方向的工程开发和学术研究打下坚实的基础。

*** 云数据管理（1）

i.e. Cloud Database Management（1）

5 学分 80 学时

理解分布式计算环境下云数据管理的基本概念，包括大规模数据的分布与并行处理、大数据（半结构与非结构化数据）组织模型及其存储管理基本原理和方法，基于云数据服务的一些具有挑战性的研究问题；掌握云数据集成与大数据分析技术；掌握大数据智能处理技术、典型算法及其应用技术；掌握信息检索基础知识与应用技术；了解主流的非关系数据管理系统，培养学生大规模数据管理的独立思维、分析和解决实际应用问题的能力。课程分别从基础、系统和应用三方面讲解云数据管理基础、云数据（NoSQL 和 SQL）管理系统和云数据管理应用。基础部分覆盖大数据基本概念、云数据挖掘和云数据质量；系统部分讲解分布与并行数据管理和云数据集成与分析；应用与实践部分介绍信息检索与服务等。本课程分系统篇（云数据管理 1）和应用篇（云数据管理 2），系统篇包括云数据管理基础和分布式数据库管理，应用篇包括数据分析与挖掘、多媒体信息检索和综合实践。计划每周 10 个学时，每次 2/3 学时，包括 8 次研讨课，每次 2 学时，内容包括论文报告、自学讨论等。

*** 云数据管理（2）

i.e. Cloud Data Management（2）

5 学分 80 学时

针对分布式环境下复杂、海量数据服务的需求，围绕云数据管理系统建设及其应用讲解的知识点主要包括：云数据管理基础、大数据存储技术、分布与并行数据管理、云数据集成与分析、数据仓库与云数据挖掘、信息检索与服务。

通过这些内容的讲解，并结合非结构化数据库管理平台中的分布式文件存储、类 SQL 引擎、图像数据检索、文本数据挖掘等实践平台，使学生具备以下能力：

#+BEGIN_EXAMPLE
1）掌握云数据管理系统体系结构、大数据处理基本技术、非结构化数据管理模型与数据处理方法；
2）具备云数据分布式存储设计、面向应用的分布式数据管理的能力；
3）掌握智能数据处理方法与算法，具备信息检索、云数据服务和智能数据处理的能力；
4）具备构建大数据管理系统的基础理论和系统的专门知识。
#+END_EXAMPLE

*** 网络系统（1）

i.e. Network System（1）

5 学分 80 学时

《网络系统（1）》课程重点关注现实可用的主流工业互联网系统，目的是指导学生全面深刻地测量和分析现存工业互联网系统，以及帮助学生自主开发高性能、低开销的实验互联网系统。教学方式以课堂授课讲解经典网络系统案例为主，考核方式以学生实践作业并做课堂汇报为主。课程内容主要包括：网络操作系统、网络协议、Web 网页性能分析、以微信为代表的移动互联网系统、以QQ 旋风为代表的离线下载系统、以 Dropbox 为代表的云存储系统、以百度手机卫士为代表的移动节流系统、Java 网络编程、Django 网络编程等。

*** 网络系统（2）

i.e. Network System（2）

5 学分 80 学时

本课程将以现有物联网和无线网络最新的发展趋势为基本出发点，通过对物联网发展过程中关键和前沿技术的介绍，使得学生了解物联网发展的历史和现状，了解现有物联网典型应用，学习物联网中关键技术和系统组成部分，探讨和思考未来发展趋势。

*** 软件系统建模与验证（1）

i.e. Modeling and Verification of Software Systems（1）

4 学分 64 学时

本课程面向软件工程专业高年级本科生开设，介绍软件分析与验证的基本原理与基本方法。通过本课程的学习，同学们将学习到利用形式逻辑等数学工具对程序行为进行抽象和推理的能力；常见的软件分析与验证工具背后的基本原理；以及借助已有工具，编写更安全、更可靠软件代码的能力。本课程覆盖的内容包括：命题与一阶逻辑，一阶理论，可满足性判定过程，程序正确性规约，程序语义，霍尔逻辑，程序终止性判定，程序正确性证明等。本课程将结合实际工具进行相关概念的讲解和实验。

*** 软件系统建模与验证（2）

i.e. Modeling and Verification of Software Systems： Part II

3 学分 48 学时

本课程主要面向软件工程学科高年级本科生。课程覆盖当前模型驱动的软件系统设计理论和实践。课程将围绕当前软件工程中的模型驱动的研发最新技术进展，详细讲解这些技术如何被用于辅助开发人员用模型描述系统需求，如功能需求、性能需求等；详细讲解这些技术如何被用于模型的仿真和验证及代码生成。本课程主要分为两阶段：第一阶段重点讲解如何利用自动机、数据流、等建模方法，对系统的同步异步通信，层次结构进行建模。第二阶段重点讲解如何利用模型验证，代码生成技术，对模型进行验证并自动生成系统代码。

*** 专业课程实践

i.e. Course Project in Speciality Fields

2 学分 64 学时

课程结合软件工程专业各方向的实际科研和工程项目，让学生综合运用所学知识，参与软件系统的整体规划，独立完成模块的需求分析、概念设计、详细设计、实现、测试、实施、产业化等一个或多个阶段。

#+BEGIN_EXAMPLE
1、正确理解工程项目的生命周期；
2、基本掌握软件系统的整体规划方法；
3、基本掌握一个模块的需求调研、需求分析、系统设计方法；
4、基本掌握软件系统的测试与实施常用方法；
5、基本掌握软件系统相关文档的编写技巧；
6、初步了解软件产品化过程。
#+END_EXAMPLE

*** 数据库技术

i.e. Database Technology

3 学分 48 学时

本课程内容以关系数据库理论、方法和应用技术为主。包括关系理论、实体联系模型、SQL 语言、关系型数据库设计、数据库查询与应用及等内容。课程结合若干个案例，以实际操作的形式，巩固所学数据管理知识，增强数据库技术的实际应用。通过这些方面的讲解和实践，使学生具备以下能力：1）针对不同的业务场景具备相应数据库的设计能力，2）具有 SQL 语句的编写能力，3）具有主流数据库如 MySQL，Oracle 的基本操作能力。

*** 形式语言与自动机

i.e. Formal Language and Automata

3 学分 48 学时

这门课主要介绍 DFA、NFA、PDA、DPDA、TM 等自动机，RL、CFL、RE 等形式语言，以及可计算性及相关内容，包括：基础知识；确定性有限自动机、非确定性有限自动机；正则表示与语言；正则语言与正则文法；正则语言的性质、Pumping 引理及应用；上下文无关文法与语言；下推自动机、确定性下推自动机；上下文无关语言的性质、上下文无关语言的 Pumping 引理及应用；图灵机与计算；问题的不可判定性，计算复杂性问题；软件建模及验证等。

*** 计算机组成原理

i.e. Computer Organization Principle

3 学分 48 学时

计算机组成原理课程是软件工程专业的本科生专业主修课，重点讲解计算机体系结构的设计与实现，这部分内容是了解计算机如何工作、软件如何运行的核心基础。本课程内容包括计算机中的信息表示、程序的机器级表示、处理器体系结构、存储器体系结构、程序性能优化等。通过本课程的学习，学生可以理解计算机体系结构的基本概念和设计原则，掌握计算机高可靠、高效运行的基本实现方式和方法，并通过编程实践让同学们熟练掌握计算机程序设计、调试、性能优化等技能。

*** 算法分析与设计基础

i.e. Intoduction to Algorithms

2 学分 32 学时

本课程将介绍算法分析与设计的基础内容。主要包括如何分析算法的渐进复杂度，均摊分析以及随机分析。教授基本的算法设计方法，例如分治法、动态规划算法以及贪心算法，以及若干专题，例如堆的设计与分析、字符串匹配算法、排序算法以及 NP 完全性理论和近似算法等等。

** 电子工程系

*** 集成电路简史

i.e. A Short History of Integrated Circuits

1 学分 16 学时

今天，用硅材料制作的 MOS（i.e. MOSFET Metal-Oxide-Semiconductor Field-Effect Transistor 金属-氧化物半导体场效应晶体管） 集成电路已经深入到国民经济和人们日常生活的各个方面，集成电路也当之无愧地成为信息社会的两大支柱之一。纵观从电子元件的产生到微系统芯片的短暂历史，不论是从电子管到晶体管，不论是从 Ge 到 Si，也不论是从模拟到数字，我们都不难看到其间有许多伟大的发明创造，但也走了不少弯路。本课程希望通过介绍这段历史中的一些典型事件，透视电子系统的发展规律，从而使新入学的同学掌握如何辨别新技术（方法）的价值、如何确定工作方向的基本方法，同时也希望新同学从集成电路发展历史中获得一些启示。

*** 光通信与信息社会

i.e. Optical Communications and Information Society

2 学分 32 学时

光通信以其长距离、大容量和高可靠等突出优点，已广泛应用于海底（洲际）通信、国家骨干网络、城域网、光纤到家和 4G/5G 无线通信回传等场合，成为整个信息社会的基石。教学内容涵盖光通信在现代信息社会中的主要应用方面，教学形式包括讲座、研讨、实验室参观、现场教学等多种形式相结合。

*** 电子工程的物理基础 -- 材料与器件

i.e. Physical Basis of Electronic Engineering -- Materials and Devices

1 学分 16 学时

_比特_ 是信息的基本数量。而比特的产生是通过操控电子器件中电子的 _能量状态_ 实现的，并经过电子、光子不同能量状态的传输、处理，以及电子、光子的能量状态的检测到达用户端。本课程拟通过对国家与社会需求分析提出我们对器件的基本需求，通过基础材料和器件的基本概念介绍，了解材料与器件对电子工程的作用。本课程力求使学生理解什么是电子工程，以及它的物理基础材料和器件。

*** 单片机和嵌入式系统

i.e. Microcontrollers and Embedded systems

2 学分 32 学时

嵌入式系统是智能化时代研究开发的热点之一。

本课程主要通过由单片微机构成的嵌入式系统介绍：
1. 单片机和嵌入式系统的硬件组成和工作特性。
2. 嵌入式系统软件的特点，混合编程和实时操作系统
3. 嵌入式应用系统的设计要点。

本课程是一门以实践为主的课程，注重提高学生应用单片微机设计和构成嵌入式系统的能力。本课程的实
验部分结合新唐 NuMicro 系列 ARM Cortex-M0 微控制器进行，上机 30 小时，包括最后用作考查的 18 小时
设计性综合实验。

*** 高级编程与工程应用

i.e. Advanced Matlab Programming and Its Application

2 学分 32 学时

讲授：MATLAB 基本语法，矩阵和数值运算，符号运算，二维三维绘图和声音，M 文件编程，图形化仿真程序设计，SIGNAL 等工具箱，和 C 语言混合编程等，课程设计包括：概率统计，数字信号处理和通信系统仿真。

*** 数据与算法

i.e. Data and Algorithm

3 学分 72 学时

数据是客观世界的抽象描述，是信息和知识的载体；算法是处理数据的系统，帮助我们获取数据中的信息和知识；本课程介绍数据的表示、存储、访问方式，以及针对不同数据类型的各种算法的实现、评价和设计策略。课程内容主要包括非数值数据类型（表、树、图） ，数值数据类型（整数、浮点数），非数值算法（查找、排序、搜索），数值算法（插值、拟合），算法的分析方法（时间、空间复杂度）以及基本的算法设计策略（分治、动态规划）等。数据与算法之间的相互作用是课程的核心思想和主要线索。课程旨在帮助同学们提升用现代计算方法解决现实世界实际问题的能力，为后续的课程以及未来的研究、工作奠定基础。

*** 电子电路课程设计

i.e. Electronic circuit course design

1 学分 32 学时

《电子电路课程设计》是一门综合应用模拟电路和数字电路知识进行电子系统设计的课程，要求设计并制作具有较完整功能与实际应用相关的电子系统，它侧重于电子技术理论知识的灵活运用和设计的创新，具有系统性、综合性和一定的探索性。目前开设的专题项目有：数字温度计设计、超声波测距系统设计、站台无线计时器设计和模拟智能路灯控制系统设计。可任选其中一个专题完成相应的设计。随着课程改革的不断深入，本课程的专题项目将在后续的教学过程中进一步丰富。

*** 电子电路与系统基础实验（1）

i.e. Basic Experiments for Electronic Circuits and Systems（1）

1 学分 28 学时

本实验课是与《电子电路与系统基础》（1）理论课对应的实验课程，为独立开设的基础实验课，是电子工程系本科生的必修课。课程内容本着“由易到难，循序渐进，跟理论课紧密结合，结合实际应用”的基本原则，具体开设的实验内容包括：仪器使用及常用基本电量的测量、仪器使用及常用电路参数的测量、电路基本定律定理、二极管特性及其应用和运算放大器应用。

*** 电子电路与系统基础实验（2）

i.e. Basic Experiments for Electronic Circuits and Systems（2）

1 学分 36 学时

本实验课是与《电子电路与系统基础》（2）理论课对应的实验课程，为独立开设的基础实验课，是电子工程系本科生的必修课。课程内容本着“由易到难，循序渐进，跟理论课紧密结合，结合实际应用”的基本原则，具体开设的实验内容包括：RC 电路、单管放大电路、与非门测试、RC 有源滤波器、RLC谐振电路、波形产生电路和晶体管输出特性曲线测试电路设计。

*** 电子系统专题设计与制作

i.e. Design and Making of Electronic System

2 学分 64 学时

在本课中，选用一种电子技术设计的典型平台（Arduino 教学平台），首先要求学生熟悉和理解开发板硬件设计原理，然后分析设计需求，按照工程开发实际流程，自主完成实验项目的系统方案设计、单元模块设计，最后在相应的集成开发环境下，完成流程图设计、代码编写、程序仿真、调试和验证与测试。

*** 电动力学

i.e. Electrodynamics

4 学分 64 学时

讲授电磁场的基本定律，麦克斯韦方程组，静电场，标量电势，静电场问题的求解，恒定磁场，矢量磁势，标量磁势，时变电磁场，波动方程，坡印廷定理，能量和能流，平面电磁波，反射与折射，波导与谐振腔，时变场的标势与矢势，达朗伯方程，偶极辐射，天线辐射。

*** 信号与系统

i.e. Signals and Systems

4 学分 64 学时

归类整理了在信息科学中基本的信号和系统分析的数学工具，将数学理论和信息系统中的物理问题相结合，搭建起从数学方法到物理问题的桥梁。是信息领域最重要的“专业”基础课之一。信号表示与系统分析紧密联系，掌握几种基本分析工具：基本工具：卷积（和）、连续傅里叶变换、离散傅里叶变换、拉普拉斯变换、Z 变换；系统表示：微分方程、差分方程、状态方程、系统函数、频率响应；信号表示：频谱、功率谱、相关函数等。

*** 通信原理实验

i.e. Communication System Laboratory

2 学分 48 学时

本课程是《通信与网络》和《现代通信原理》的后续课程，主要研究和验证现代通信原理中的基本原理，如：信源编码、信道编码、调制、解调等方面内容。通过实验，使学生掌握现代通信原理中的一些关键技术，同时，通过实验培养学生的动手能力和独立思考能力。本实验的研究型部分能培养学生在中大规模 FPGA的使用、电路系统设计、电路调试等方面技能。课程说明： 包括验证型和研究型两部分实验。其中验证型实验在现有的教具上验证现代通信原理的一些关键技术；研究型实验是在通用实验平台上，通过自主设计，研究现代通信中的一些关键技术。

*** 计算机图形基础

i.e. Fundamentals of Computer Graphics

2 学分 32 学时

本课程主要包括讲授计算机图形学的基础知识，包括常见计算机图形设备的工作原理、基本图形如直线、圆弧、曲线的快速生成方法，图形的扫描转换、区域填充、裁剪，三维图形的生成与透视变换、消隐处理、真实感图形生成理论等。

*** 遥感原理

i.e. Principles of Remote Sensing

2 学分 32 学时

概述遥感技术的现状与发展方向；从太阳、地球和大气的波谱特性阐述遥感技术的基本原理，介绍遥感物理基础、卫星轨道计算原理、传感器特性以及典型卫星遥感系统；介绍遥感信息系统的组成，包括接收系统和卫星图像处理系统；介绍遥感信息处理技术，包括辐射校正、几何校正，以及面向卫星图像的变换、分类、高度计测、数据压缩、高光谱信息提取等基础处理理论；分析具体的遥感应用实例。

*** 天线原理

i.e. Principles of Antenna

2 学分 32 学时

天线在通信、雷达、微波遥感、电子对抗和射电天文等系统中是必不可少的部件。天线的指标参数对系统的整体性能起着非常关键的作用。该课程讲述了首先从物理概念和数学模型的结合点出发，求解有源麦克斯韦方程及描述电磁辐射场；其次介绍了天线关键参数的定义和测量方法，以及天线在无线信道的基本计算中配置方法；第三，讲授常见天线的基本原理和参数，采用经典的分析计算方法对简单天线的远区场进行了求解，系统的讨论了线天线、环天线、槽天线、微带天线、抛物面天线等工作原理和设计方法；最后讲授天线阵列的工作原理和设计方法。

*** 通信原理概论

i.e. Introduction of Principles of Communications

3 学分 48 学时

本课程主要介绍现代通信技术的基本原理，以数字通信为主。内容包括通信系统基本概念、信息论初步、模拟调制、语音编码、多路复用、数字基带传输、数字调制、差错控制、多址方式、无线通信系统介绍等。

*** 数据库

i.e. Database

2 学分 32 学时

内容包括：数据库的基本概念，数据模型，关系型数据库的定义和数学模型，关系代数和关系演算 QBE，结构化关系数据库语言 SQL，关系数据理论，数据库设计，数据的安全性、完整性、并发控制及数据库恢复，数据库最新技术与进展，一个实际的数据库系统 SQL Server 简介。

*** 电磁场

i.e. Electromagnetic Fields and Waves

3 学分 48 学时

课程首先概略地介绍矢量的运算规则、相关定义和矢量积分定理。第 2 章至第 4 章讨论静电场和恒定磁场，包含电磁学的基本定理、定律以及求解电磁问题的基本方法。作为从静电场到时变场的过渡，第 5 章讨论准静态场，利用准静态条件从电磁场理论的基本方程，导出电路理论的基本方程——环路电压定理和节点电流定理。第 6、 7 章讨论时变场，内容涉及时变场满足的基本方程式和电磁波波动特性，讨论各种位函数、麦克斯韦方程组、波动方程、电磁波在各种媒质中的传播特性和导波等。第 8 章讨论电磁波的辐射，主要讨论电、磁偶极子的辐射场形式及特点。

*** 通信电路

i.e. Communication RF Circuits Design

3 学分 48 学时

射频通信由于建设速度快、质量稳定、通信可靠、维护方便、易于跨越复杂地形等优点，已经广泛应用于移动通讯、局域网络、电子娱乐、医疗器材等领域，并将继续深入影响人们的日常生活。本课程主要内容是射频通信电路原理，讨论射频通信系统尤其是模拟单元电路的设计问题。通过对本课程的学习，同学将会获得一个射频通信系统的整体概念，能够识别射频通信系统各单元电路，了解其基本功能，以及实现这些功能的基本电路原理及电路形式。 课程主要内容包括：
1. 射频通信系统的基本概念：发射机与接收机结构、噪声与失真、线性与非线性、调制与解调、正负反馈、AGC/AFC/PLL 等；
2. 射频通信系统的基本电路形式：滤波器、小信号放大器、功率放大器、乘法器、变频器、振荡器、
调制解调器和频率综合器等；
3. 其他相关内容：匹配、部分接入和阻抗变换，放大器宽带化措施等。

本课程为电子系本科生专业限选课，以课堂授课为主，同一学期有隶属于该课程的实验课程可供选修。

*** 通信电路实验

i.e. Communication Circuits Laboratory

1 学分 32 学时

本课程旨在帮助学生建立一个射频通信系统的整体概念，清楚识别射频通信系统各单元电路，了解其基本功能，并掌握实现这些功能的基本电路原理、电路形式及测试技术。

课程共设有两个实验项目：
- 实验一 调频接收机模块电路设计与无线链路实验。本实验项目两人一组，在 6 周时间内（每周一个单位时间），根据指标要求共同设计 FM 接收机主要模块，
包括高频小信号放大器、本地振荡器、混频器、中频放大器、鉴频器，然后将几个模块连成接收机，达到一定的性能要求。具体分工：组员 A 负责高放和鉴频，组员 B 负责本振、混频和中放。

- 实验二 50MHz FM/FSK 无线收发信机综合实验。本实验项目两人一组，在 3 周时间内（每周一个单位时间），共同深入研究一个典型的实用调频收发信机，调测其性能达到一定指标要求，建立无线通信系统概念。

*** 现代通信原理

i.e. Principles os Modern Communications

3 学分 48 学时

本课程主要讲授现代通信系统的基本原理，以数字通信为主，内容包括：信息论初步、模拟调制、数字调制、信源编码、基带传输、数字复接、信道编码、多址方式等。

*** 数字信号处理

i.e. Digital Signal Processing

3 学分 48 学时

本课程介绍离散信号处理的相关知识，包括：

#+BEGIN_EXAMPLE
0、从连续到离散：采样和量化；
1、离散信号的表示和常用变换方法；
2、离散信号频域表示；
3、离散傅里叶变换的快速算法；
4、离散傅里叶变换的应用；
5、离散系统的表示和分析；
6、数字滤波器的设计方法；
7、有限字长效应；
8、多采样率信号处理。
#+END_EXAMPLE

*** 计算机网络技术与实践

i.e. Computer Network Technology and Experiment

3 学分 48 学时

该课程的教学内容主要是围绕计算机网络基础知识和最新技术来组织。深入分析计算机网络和电信网络的关系和特点；同时介绍计算机网络的主要应用技术。主要内容分 3 个层面：第 1 层面：按照网络分层模型来介绍相关的传输、数字通信以及交换等方面概念、原理、以及计算机网络基本知识；并加强网络接口层的知识点。目标是让学生掌握有关：传输、通信、交换以及网络的基本知识和概念，同时了解网络的一些主要协议。第 2 层面：以构建大型计算机网络为线索，结合前面所介绍的基本知识，分析组建不同网络域所需要采用的网络技术，分析这些网络的特点。最后，从网络大数据的视角，从社交网络、媒体网络、云计算等视角实践网络的主要应用情况，以及数据 3 类信息传输的实现方式和技术要求、以及目前它们所基于的网络不同特点，从而使学生了解到网络最新技术和技术发展趋势。

*** 信号与系统（英）

i.e. Signals and Systems（in English）

4 学分 64 学时

归类整理了在信息科学中基本的信号和系统分析的数学工具，将数学理论和信息系统中的物理问题相结合，搭建起从数学方法到物理问题的桥梁。是信息领域最重要的“专业”基础课之一。信号表示与系统分析紧密联系，掌握几种基本分析工具：基本工具：卷积（和）、连续傅里叶变换、离散傅里叶变换、拉普拉斯变换、Z 变换；系统表示：微分方程、差分方程、状态方程、系统函数、频率响应；信号表示：频谱、功率谱、相关函数等。

*** 计算机程序设计基础（1）

i.e. Computer Program Design（1）

2 学分 72 学时

学习 C/C++语言编程的基础知识，主要包括数据类型、运算符、表达式、控制结构、函数、指针、数组、结构体等知识点，掌握面向过程的结构化程序技术和方法，为进一步学习 C++程序设计打好基础。

*** 计算机程序设计基础（2）

i.e. Computer Program Design（2）

3 学分 106 学时

该课程主要介绍面向对象的编程方法，进一步学习 C++的知识点，主要包括：类和对象，运算符与重载，继承与派生，多态性与虚函数，输入/输出流与流类库。同时还介绍一些基本软件工程知识点，并完成大型程序的设计训练。

*** 数字图像处理

i.e. Digital Image Processing

3 学分 48 学时

图像工程是系统地研究各种图像理论、技术和应用的新的交叉学科，内容可分三层：图像处理，图像分析，图像理解。本课程是图像课程的第 1 门，主要介绍低层内容，有一定的深度和广度。读者通过本课程的学习，一方面可解决一些实际的图像技术应用问题，另一方面也将为进一步学习图像工程的中高层技术打下基础（图像分析为本科高年级或研究生开设，图像理解为研究生开设）。

第 1 章：绪论；第 2 章：空域增强：点操作；第 3 章：空域增强：模板操作；第 4 章：频域图像增强；第5 章：图像消噪和恢复；第 6 章：图像校正和修补；第 7 章：图像投影重建；第 8 章：图像编码基础；第 9章：图像变换编码；第 10 章：其他图像编码方法；第 11 章：图像水印；第 12 章：彩色图像处理；第 13章：视频图像处理；第 14 章：多尺度图像处理。

*** 物理电子学基础实验

i.e. physical electronics foundation laboratory

1 学分 24 学时

本课程授课对象为电子工程系全体本科二年级学生，旨在使学生掌握物理电子学/信息光电子学的基础实验技能，掌握基本专业知识、实验研究方法和基本实验技巧，学会本领域的基本测试方法与仪器使用方法，促进基础性实验与前沿性实验的结合。实现重基础宽口径的教育理念，并且引导部分学生深入某个研究领域的兴趣。实验内容涵盖真空与材料工艺、集成光电子器件与工艺、微纳结构器件与工艺、光纤、光通信、光传感，现代光学及信息处理应用。

本课程 1 学分，课内 24 学时，分为以下三个专题，同学可任选一个专题选课。
课序号 1. 光纤应用与光信息处理（吕晖老师负责）
课序号 2. 现代半导体光电子器件工艺（韩彦军老师负责）
课序号 3. 微纳结构器件与工艺（刘仿老师负责）

本课程简介：

课序号 1 课程为“光纤应用与光信息处理”，课程目的为：了解光纤的基本特性并掌握基本实验技能；了解光纤在传感中的应用技术；掌握光纤通信系统设计方法，了解现代光学及光信息处理方法；学习掌握光电子常用测试手段及设备使用方法。课程内容包括：讲授光电子学、光传输、光传感与现代光学的基础知识，实验研究有关光纤、激光器、光探测器、光放大器等关键光元器件特性与应用；实验研究光传输系统；现代光学应用实验等。

课程安排：共 7 次实验：3 次基本仪器使用和 4 次实验。

1. 光纤特性
2. 半导体激光器
3. 光纤通信系统
4. 全息光栅

*** 微波与光波技术基础

i.e. Fundamentals of Microwave and Lightwave Technology

3 学分 48 学时

该课程以电磁场理论为基础，采用场和路相结合的方法，讲授各种导波结构中电磁波的求解方法、基本特
性以及应用技术，主要包括：

1）从集总参数电路过渡到分布参数电路，研究微波传输线的基本特性及其计算方法，着重介绍传输线理论
的图解法--Smith 圆图。

2）从电路理论过渡到电磁场理论，分析多种类型传输线或波导，讲授求解方法、模式的概念及其电磁场分
布和传播特性。

3）微波网络的基本理论，介绍多种微波网络参量，着重分析散射参量。

4）应用传输线理论，微波网络理论和电磁场理论相结合的方法，了解多种微波无源器件的结构和功能，分
析微波元器件以及由这些元器件构成的微波电路的特性。

5）天线的基本原理和分析方法，介绍常用的天线结构。

*** 概率论与随机过程（1）

i.e. Probability and Stochastic Processes（1）

2 学分 32 学时

本课程的内容为不涉及严格测度理论的初等概率论基本知识。包括概率空间（样本空间，西格玛域和概率），随机变量与随机分布，分布函数和概率密度、独立性、条件概率、离散随机变量（Bernoulli、二项、 Poisson、几何、超几何、负二项），连续随机变量（均匀、指数、高斯），随机变量的数字特征（期望、方差、高阶矩、熵），随机变量的初等变换及其导出分布，多元随机变量及其联合概率分布、条件期望与条件分布、特征函数与极限定理初步。

*** 固体物理基础

i.e. Foundation of Solid State Physics

3 学分 48 学时

固体物理是研究固体的结构和组成粒子（原子、离子、电子等）之间相互作用与运动的规律、从而阐明其性能与用途的科学，是包含电子科学与技术在内的诸多学科的基础，比如半导体材料与器件已成为现代科技发展中最核心、最重要的方向之一。本课程将围绕固体物理学的基础知识展开教学，包括原子结合、晶体结构、晶格振动、能带理论、晶体中电子的运动，固体中的电磁光特性等。其中能带理论为本课程的教学重点。

*** 概率论与随机过程（2）

i.e. Probability and Stochastic Processes（2）

3 学分 48 学时

本课程的内容为不涉及严格测度理论的随机过程基本知识。包括随机过程的基本概念（样本轨道、联合分布族），相关函数与功率谱密度，宽平稳随机过程，非平稳过程（循环平稳，正交增量），遍历性，Karhunan-Loeve 展开与变换，高斯过程与多元高斯分布，多元高斯分布的性质（线性、条件分布、高阶矩），高斯过程与非线性系统，随机过程的窄带表示，Poisson 过程，Poisson 过程与指数分布和 Gamma 分布的关联，Poisson 过程的条件分布，Poisson 过程的各类扩展（非齐次，复合，过滤），离散时间 Markov 链的基本概念，一步转移概率与 Chapman-Kolmogorov 方程，Markov 链的状态分类，常返性，平稳概率与转移概率的极限，连续时间 Markov 链的基本概念，Q 矩阵，生灭过程，排队论简介。

*** 数字逻辑与处理基础

i.e. Fundamental of digital logic and processor

3 学分 48 学时

数字逻辑与处理器基础课程讲述数字逻辑电路和处理器的基本概念，围绕数字单元与系统讲解表示、综合、优化的基本方法。课程分为两个部分。第一部分以数字逻辑电路为主。讲述在逻辑门与触发器级别的数字电路工作原理，并介绍组合逻辑与时序逻辑的分析与设计方法。第二部分以处理器的组织与结构为核心，讲述指令集、算术逻辑单元、控制器与输入/输出等基本概念。以一个单周期的处理器和一个流水线处理器为例讲解处理器的工作原理与基本设计方法。

*** 电子电路与系统基础（1）

i.e. Fundamentals of Electronic Circuits and System I

2 学分 32 学时

电路是电子系统中物质构成、能量转换、信息处理的结合点，电子电路是构建信息系统的物理层基础。 “电子电路与系统基础”课程从构成电路的基本元件、基本分析方法入手，介绍电路及电路系统的基本概念，分析基本单元电路的原理及应用。本课程融合了原“电路原理”、“模拟电路”、“通信电路”和“数字电路”课程内容及场路抽象内容，以电路抽象为主干，在线性电阻电路、非线性电阻电路、一阶动态电路和二阶动态电路四个分支上挂接了理想变压器、回旋器、环行器及电阻分压网络、电桥、放大器、滤波器、振荡器、模数转换器、与或非门、整流器、逆变器、稳压器、变压器、存储器等基本单元电路。“电子电路与系统基础（1）”的具体内容包括：电路基本定律和定理；电阻电路（电阻、电源）分析方法；晶体管电路（受控源、开关）分析方法，重点为放大器。另有配套实验课《电路基础实验 I》1 学分。“电子电路与系统基础（2）”的具体内容包括：由电阻、电容、电感元件构成的动态电路的时域及频域分析方法；寄生电容形成放大器带宽和数字门电路延时的机制；RLC 电路应用，包括滤波器，振荡器。同时包括电阻电路的运放、数字门电路内容。另有配套实验课《电路基础实验 II》1 学分。

*** 电子电路与系统基础（2）

i.e. Fundamentals of Electronic Circuits and System II

2 学分 32 学时

电路是电子系统中物质构成、能量转换、信息处理的结合点，电子电路是构建信息系统的物理层基础。 “电子电路与系统基础”课程从构成电路的基本元件、基本分析方法入手，介绍电路及电路系统的基本概念，分析基本单元电路的原理及应用。本课程融合了原“电路原理”、“模拟电路”、“通信电路”和“数字电路”课程内容及场路抽象内容，以电路抽象为主干，在线性电阻电路、非线性电阻电路、一阶动态电路和二阶动态电路四个分支上挂接了理想变压器、回旋器、环行器及电阻分压网络、电桥、放大器、滤波器、振荡器、模数转换器、与或非门、整流器、逆变器、稳压器、变压器、存储器等基本单元电路。“电子电路与系统基础（1）”的具体内容包括：电路基本定律和定理；电阻电路（电阻、电源）分析方法；晶体管电路（受控源、开关）分析方法，重点为放大器。另有配套实验课《电路基础实验 I》1 学分。“电子电路与系统基础（2）”的具体内容包括：由电阻、电容、电感元件构成的动态电路的时域及频域分析方法；寄生电容形成放大器带宽和数字门电路延时的机制；RLC 电路应用，包括滤波器，振荡器。同时包括电阻电路的运放、数字门电路内容。另有配套实验课《电路基础实验 II》1 学分。

*** 媒体与认知

i.e. Media and Cognition

2 学分 32 学时

与人类视听觉感知密切相关的图像、语音和文本（语言）信息在社会、经济和国家安全等领域中扮演着重要角色，并在今后一段时间内仍将迅猛增长。这类信息可被人类直接感知和理解，也可用计算机进行处理，但计算机的处理能力远逊于人类且处理效率远不能满足当今社会的发展需求。如何借鉴人类的认知机理和相关数学的最新研究成果，建立新的计算模型和方法，从而大幅度提高计算机对这类信息的理解能力与处理效率，不仅可有力推动信息科学的快速发展，也将为国民经济和社会发展做出重大贡献。

课程主要分三个模块：

（1）媒体与信息：详细介绍媒体与信息的概念、媒体获取以及表示形式。既包括传统媒体如报纸等，也包括电子化媒体，图像、语音、网络信息等。

（2）认知科学：详细介绍研究历史和现状，包括唯物和唯心的心理学研究，认知机理（视觉、听觉等认知计算等），信息科学，以及与传媒的关系。

（3）智能信息处理：包括媒体计算理论，媒体认知理论，智能处理理论，以及媒体认知的应用。

*** 数字逻辑与处理器基础实验

i.e. Fundamental Experiment of Digital Logic and Processor

2 学分 64 学时

本课程领域包括基于硬件描述语言的数字系统建模方法、基本数字电路设计与实现、简单处理器硬件设计与实现。本课程主要以硬件描述语言（HDL）为手段，可编程逻辑器件（FPGA）为平台完成各项数字系统实验，掌握现代数字系统设计的基本理论和方法，实验内容覆盖基础逻辑、简单系统、软硬件混合系统（处理器）等。

通过本课程的学习，使学生能够正确观察和分析实验现象，掌握基本实验方法，培养基本实验技能，通过运用所学知识，设计制作较为复杂的功能电路，培养学生数字逻辑设计与综合应用的能力、使用计算机辅助设计工具的能力，全面提高学生的素质、动手能力和创新能力。

*** 视听信息系统导论

i.e. Introduction to Auditory-visual Information System

3 学分 48 学时

“图像信息可以直通大脑的长期记忆区域，每幅图像的信息在大脑中作为一个完整的块或者概念存储。” –M.H. Erdelyi and J.B. Stein“人的喜怒哀乐，一切骚扰不宁、起伏不定的情绪，连最微妙的波动、最隐蔽的心情，都能由声音直接表达出来， 而表达的有力、细致、正确，都无与伦比。” – H.A. Taine视听（图像与声音）信息是人类实现信息交流最为重要的载体，也是现代信息处理技术的主要研究对象。在信息总量以前所未有的方式极度膨胀的海量信息时代，视听信息在人类信息获取中展现的普遍性和高效性确立了其在现代信息技术领域的核心地位。现代视听信息处理技术涵盖了视听信息的感知、获取、存储、传输、搜索、处理、分析、理解、重建、再现与虚拟等各个方面。而人类视听信息认知的复杂性、微妙性与多样性也使得视听信息处理从传统的信息科学逐步扩展到生理学、心理学以及认知科学，成为一门跨领域的综合学科。今时今日，越来越多的信息以图像与声音的方式被生成、存储、传递与共享，这一趋势深刻的变革着人类生产和生活方式。从数字电视到三维电影，从智能手机到网络媒体，各类视听信息系统以前所未有的广度与深度迅速渗透到人类生活的各个角落正是视听信息浪潮的最为直接的体现。近年来，视听信息系统的飞速发展是视听信息技术进步最为集中的体现。数字电视替代模拟电视使得用户坐在家中也可以欣赏和演播室画质等同的电视节目；智能手机逐步成为个人信息中心，甚至能理解用户的语言表情或是动作；三维电影使得身临其境的梦想成为现实，先进的三维信息重现技术使得观众无法区分虚拟和现实。本课程以视听信息系统为依托，介绍视听信息的基本原理、关键技术和典型应用。课程主要讲授视听信息本源及形成机理，人类视听感知的基本生理及心理原理，光与颜色，声音的特性与度量，成像几何学基础，视听信息的感知与获取，视听信号的构成与传输，视听信息的重现，常见的视听设备以及典型的视听信息系统及其应用。

*** 操作系统

i.e. Operating System

3 学分 48 学时

作为当今技术含量最高的系统软件，操作系统构成了现代计算机的基础运行平台，掌握操作系统的基本原理对于深入了解计算机的运行机制，开发高效率的应用软件具有举足轻重的作用。本课程的教学将贯彻两条主线：一是通过课堂教学，使学生理解操作系统的基本概念、原理、结构和主要功能；二是通过针对 Linux 和 Windows 的实验，使学生掌握主流操作系统内核的运行原理和机制。在教学内容方面，本课程强调原理的基础性和技术的前沿性。一方面强化基本原理的教学，另一方面跟踪现代操作系统技术的新发展。以往的操作系统教学要么因为无法将原理与实际相结合，导致学生在学习的过程中获得的只是一些空洞的知识，要么只是将原理与一个简化的或模拟的操作系统相结合，使得学生无法了解现代主流操作系统所采用的实现技术。Linux 和 Windows 代表了现代操作系统的最高水平。Linux 是一个开源的操作系统，Windows 虽然并不开源，但是面向学术界推出的 WRK（Windows Research Kernel）开放了 Windows 的大部分内核源代码。以 Linux 和以 WRK 为教学平台，能够给学生提供良好的环境深入理解现代操作系统的重要概念是如何在一个实际的操作系统中实现的。在教学方法上，本课程采用课堂教学 课外实验的形式。课堂教学方面主要讲授操作系统的基本原理，包括进程、线程、处理机管理、存储管理、文件系统、I/O 管理、设备驱动程序，以及这些基本概念和基本原理在 Linux 和 Windows 操作系统中的具体实现。在课外实验方面，本课程将安排多个 Project，这些 Project 涉及操作系统的主要管理功能，包括进程与线程调度、存储管理、文件系统、I/O 系统。通过这些 Project 的训练，可以使学生较深入地掌握操作系统的基本原理，为今后从事相关的开发工作打下良好的基础。

*** 数字系统设计

i.e. FPGA Based Design Methodology For Advanced Digital System

3 学分 64 学时

课程目标：通过学习数字系统的设计优化理论，利用现代大规模高性能可编程逻辑芯片进行实践，使得同学掌握复杂数字系统的基本设计理念和方法。

基本内容：软到硬的转化（并行概念的引入），设计优化技术（时序、延时、时钟、同步），系统设计方法（系统规划、软硬划分、接口、测试）

课程要点：利用现代大规模高性能可编程逻辑芯片，采用先进设计方法实现高级数字系统的设计。

课程对象：面向电路与系统、通信、图像、雷达等和数字系统相关专业的学生

*** 信息光电子学基础

i.e. Fundamentals of information optoelectronics

3 学分 48 学时

光电子学是一门光学与电子学交叉形成的科学。基于光优异的信息携载能力，以光电子学为基础的现代信息获取，信息加载，信息传输，信息处理，信息变换，信息存储和信息显示等功能支撑了现代信息社会的高速发展。

本课程面向光电子学在信息社会中的应用，讲授光的电磁本性，传播规律，产生机制和探测原理，帮助学生建立对信息光电子学及其思想方法的整体认识，为学生今后从事相关研究与工程应用工作打下良好的基础。

*** 电子信息科学与技术导引（2）

i.e. Introduction to ELectronic Information Science and Technology（2）

1 学分 16 学时

结合电子工程学科知识体系，介绍电子信息科学与技术各专业的学科内容、研究方向与未来趋势，引导学生由基础课向专业课平稳过渡，并提供专业选择的指导。

*** 统计信号处理基础

i.e. Fundamentals of Statistical Signal Processing

3 学分 48 学时

估计理论：最小方差无偏估计；Cramer-Rao 界；线性模型的 MUV 和最佳线性无偏估计；充分统计量；最大似然估计及应用；最小二乘估计；贝叶斯原理和一般贝叶斯估计量；线性模型的 MMSE 估计和线性 MMSE估计；维纳滤波及其应用；卡尔曼滤波及其应用；Bayesian 滤波和粒子滤波；稳健估计； 检测理论：简单假设检验；确定信号的检测；随机信号的检测；复合假设检验；具有未知参数确定性信号的检测； 统计信号处理在通信系统、雷达系统、图像处理等方面的应用。

*** 电子信息科学与技术导引（1）

i.e. Introduction of Electronic Information Science and Technology（1）

1 学分 18 学时

作为清华大学电子工程系新课程体系的导引课，本课程全面阐述电子信息科学与技术知识体系的七个层次，展示了知识体系七层次之间的内在关联性，突出知识体系的全面性和系统性，目的是使电子系大一新生对电子信息与科学技术有总体的系统的了解，并通过本课程学习具有自主安排后续专业课程选修与学习计划的能力，进而确定以后的研究方向。授课内容确定为 9 讲 18 学时，为电磁学史及分析数学史概览，场与物质，电势与电路，比特与逻辑，程序与处理器，数据与算法，通信与网络，媒体与认知，电子信息科学与技术的研究对象、知识体系及课程体系，由 8 位教师分别授课。

*** 通信信号处理

i.e. Signal Processing for Communications

3 学分 48 学时

课程内容包括贝叶斯估计、最大似然估计、最大后验概率估计、最小均方误差估计、最小二乘估计、克拉美罗界等参数估计理论；单载波和多载波系统；无线信道特性分析；实际信道条件下单载波系统的定时和载波恢复；实际信道条件下多载波系统的定时和载波恢复；时域信道估计和均衡算法；频域信道估计和均衡算法；OFDM-MIMO 信号处理技术；Massive MIMO 信号处理技术；LTE/LTE-A、WiFi 等实际数字接收机结构等内容。

*** 基于数字信号处理器的系统设计

i.e. Systems Design Based on Digital Signal Processors

2 学分 48 学时

本课程是以基础实验和系统设计为主，理论讲授与实践训练密切结合的综合性系统设计课程。课程内容包括知识学习、技能训练和能力培养三方面：

1、知识（knowledge）学习：数字信号处理器（DSP）结构设计原理、嵌入式系统开发的程序设计方法和多层优化策略。课堂讲授基本概念、原理和例程分析。

2、技能（skill）训练：嵌入式数字信号处理系统开发的程序设计技能，包括软件建立、软件验证和系统验证。通过与课堂讲授内容配套的基础实验操作、结果观察、问题思考和对比分析，在训练操作技能的同时，训练创新研究思维技能。

3、能力（capacity）培养：嵌入式数字信号处理系统设计、优化的能力和创新研究能力。通过分析定点计算的常见问题，验证相关解决方案，掌握实时数字信号处理系统的设计优化方法。通过开放式自主设计选题、理论分析、方案论证、硬件平台选择、软件设计验证、实时系统验证、设计演示和设计分析总结报告等环节，培养应用系统开发和创新研究能力。

4、本课程使用 ADI 公司的 Blackfin 处理器 BF533 和 BF561 两个评估系统平台，以及基于 BF609 的图像处理应用系统平台。

*** 通信与网络

i.e. Communications and Networks

4 学分 64 学时

本课程是电子工程系的一门核心课，主要讲述的是信息传输系统的基本结构，以经典通信理论作为信息传输的理论基石，以经典网络架构作为信息传输的组织形式，从网络中单个节点的信源和信道模型出发，扩展至整个网络的多址模型和拓扑结构，将通信与网络作为整体进行授课。重点讨论了网络整体架构、模型与评价指标，信源压缩原理，数字基带、频带传输理论，多种经典数字调制解调的原理、方法及性能指标的计算，最佳接收与判决，差错控制，多址接入、多路复用和双工技术，网络路由与交换，流量控制等内容，针对信息传输的有效性、可靠性，有效的资源共享和网络组织等方面进行教学，并配以必要的实验，提高学生对相关重点的理解与掌握。

*** 模拟电路原理

i.e. Principles of Analog Circuits

3 学分 56 学时

课程介绍模拟电路的基本原理、分析和设计方法。包括半导体器件基础；模拟电路中的重要单元电路；负反馈放大电路；集成运算放大器电路分析与应用；典型应用电路的分析与设计，包括 A/D 与 D/A 转换器；信号发生器、基准电压源等。结合模拟电路的特点分析非理想因素的影响，学习实际应用电路的分析与设计方法。同时配合对电路的仿真分析与设计实验。

*** 编码引论

i.e. Introduction of Coding

3 学分 48 学时

编码是通信系统中的重要组成部分。

编码是运用概率论与数理统计的方法研究信息、通信系统、数据压缩、数据传输等问题的应用学科理论，是电子通信类专业重要的基础知识集合。 本课程是系核心课“通信与网络”的重要延伸，通过本课程的学习将进一步加深对通信的认识和理解。

编码不仅是学生理解与电子通信类专业有关的专业课程的基础，同时引导学生在信息理论和编码方向进行研究的兴趣，对学生今后的专业发展起到积极的推进作用。

课程内容主要包括：编码概论、信息论和近世代数基础补充、信源和信道编码译码准则、熵编码、信源编码原理、抽样与量化、变换与预测、线性分组码与循环码、卷积码（网格码）、特定应用下的信源和信道编码实例、安全编码等。

学完本课程之后，学生可根据自身特点选择在信息压缩、信息传输和信息安全等方面确定相应的专业方向。毕业后可继续攻读通信及相关电子类学科、交叉学科的硕士和博士学位，或者到科研机构从事科学研究和技术开发，或者到高等学校从事教学工作。

*** 现代计算机体系架构

i.e. Modern Computer Architecture

3 学分 48 学时

计算机体系架构广泛应用于现代众多计算系统中，涵盖云计算服务器、个人电脑、智能手机到微型嵌入式系统等。本课程重点讲述各类计算机系统设计中最基本的通用概念，体系架构和软件设计方法，并介绍当代计算机系统发展的主流技术与最新成就。

首先，课程介绍计算机体系架构的发展沿革与未来趋势，然后给出评估计算机体系的量化指标与方法。其次，课程按照“计算、存储和外部设备”的线索，介绍计算机体系架构中的三大关键组成。计算架构方面，课程将讨论处理器中的两项关键高性能技术：流水线和超标量。存储架构方面，课程将重点讲述缓存、主存和外部存储技术。外部设备方面，课程将阐述互联和输入输出设备的基本原理与架构。随后，课程将介绍两款典型的现代多核计算机系统，分别讨论基于同构多核处理器（MultiCore）和异构图形处理器（GPU）的计算机系统硬件架构和软件设计与优化技术。最后，课程将介绍云计算、深度学习和物联网芯片的研究现状。

*** 图像处理系统

i.e. Image Processing System

2 学分 32 学时

本课程论述图象处理系统设计的原理及其实现方法，介绍一些著名的图象处理系统和图象处理的一些新思想、新技术、新方法。

*** 射频通信电路

i.e. Radio Frequency Communication Circuits

3 学分 48 学时

主要讲授广泛应用于射频/微波通信、电视广播、雷达、导航、遥感、天文、电子仪器等系统中的射频/微波有源电路，包括射频/微波小信号放大器、功率放大器、频率变换器、振荡器、控制电路等射频/微波电路的基本工作原理、分析和设计方法。主要内容包括：常用的分布参数平面传输线结构及其特性，所用各种微波半导体器件的结构和基本工作原理，上述射频/微波电路的基本工作原理、分析和设计方法，以及利用微波仿真分析软件进行电路设计的设计和优化方法。在学习基本理论知识的基础上，用微波仿真分析软件进行实际电路的设计实验。

*** 付立叶光学

i.e. Fourier Optics

2 学分 32 学时

本课程主要讲述付立叶分析在光学领域的应用，尤其是在衍射、成像、光学数据处理以及全息术方面的应用。通过本课程的学习要求能基本掌握付立叶光学的基本理论及其分析计算方法，了解付立叶光学的主要应用。内容主要包括付立叶变换和卷积，光的衍射理论基础，透镜的付立叶变换和成象性质，全息术的基本原理，记录介质，全息干涉计量，莫阿技术，激光散斑，空间滤波与光信息处理，光学成象系统的频谱分析等。

*** 光检测技术

i.e. Optical Detection

2 学分 32 学时

《光检测技术》课程是电子工程系信息光电子研究所开设的关于光检测方向的一门专业选修课。信息光电子研究所是电子系最大的研究所之一，光电子方面的各类实验研究（包括基础研究与应用研究）都依赖于各类测试测量仪器与测试测量技术，很多研究都需要开发特定的测试测量方法，才能得以开展。作为光电子方面研究的入门课程，本课围绕各类光检测技术，以光检测原理作为主要授课目标，围绕讲授光检测的核心（光检测器）和光检测的灵魂（检测方法），以大量的案例为牵引，同时结合近百年来光检测技术的发展，使同学们领悟“光检测技术”的演进过程，加深对光和光检测系统相互作用的规律的把握，为今后从事光电子方面的研究储备相关方法和知识。

本课程分为三大部分：光电探测器、光电信息系统的检测方法、典型光电信息系统。第一部分为光电探测器，包括光电导探测器、光伏型探测器、光电发射探测器和热探测器。主要讲述光子效应探测器（光电导、光伏、光电发射）和热效应光电探测器的工作原理和典型光电器件的特性与使用方法。第二部分为光电信息系统的检测方法，包括非相干检测技术和相干检测技术。结合单通道检测、双通道检测和调制检测的典型系统讲述非相干检测技术中信号加载、提取和信号处理。相干检测技术主要讲述双光束干涉、多光束干涉的相位调制系统和差频检测频率调制系统的工作原理和信号处理方法。第三部分为典型光电信息系统，光电探测器和检测方法的应用部分，介绍光源与光学器件的特性参量测量和温度、应变、电流、电压、声波等非光学量的光电检测方法。包括成熟的检测方法和近些年新型的检测方法。

课程内容由浅入深，随着技术发展，检测技术已经广泛应用于日常生活和各行各业。

*** 激光与光电子技术实验

i.e. Laser and Optoelectronics Laboratory

1 学分 18 学时

课程是面向全校学生开设的光电子领域的研究型和探索型实验课程，课程既为相关专业的学生提供研究平台，又为对光电感兴趣的学生提供初探的大门。课程现可提供 12 个实验，每个实验平台都以一项具有现实应用价值的光电技术为核心，并利用光、机、电多重设备和器材，兼具开放性和综合性。学生在平台上可以学习特定技术的原理和实现方式、研究系统的工作条件和规律、并进行以自身兴趣为导向的探索实践。课程会提供参考性的实验内容，但更鼓励学生自发的拟定研究内容、设计研究方案。无论从硬件平台还是实验环节，课程都力图提供最接近真实科研的实验环境。

*** 生产实习

i.e. Production Practical Training

5 学分 200 学时

通过在实习单位按要求完成一项具体的课题工作，增长社会经验，了解电子信息科学与技术专业在实践中的作用，并培养运用所学知识分析解决实际问题的能力，锻炼沟通能力。

*** 信息显示技术

i.e. Information Display Technology

2 学分 32 学时

Information Display Technology信息显示技术，是根据人类的视觉器官对可见光的响应特性，以电信号驱动的方式将信息内容以可见光的形式让人类的视觉器官产生视觉效果的技术手段。由于视觉器官是人接收信息最多的感觉器官，信息显示技术在人们的学习、工作和娱乐中发挥着的越来越重要的作用。信息显示技术的任务是根据人的心理和生理特点，采用电子学的方法改变呈现在人眼视觉系统的光的特性，形成不同形式的视觉信息。图像是视觉信息表现的最一般的形式。《信息显示技术》作为电子工程系本科生高年级的专业课，是综合性和应用性极强的课程。一方面，本课程不仅涉及了电子学、光学、材料学、化学、力学等“客观性”知识，而且涉及到视觉、心理学等“主观性”知识。另一方面，本课程为学生进一步从事光电显示器件、图像信息处理等方面的研究奠定了基础。

*** 综合论文训练

i.e. Diploma Projects（Thesis）

15 学分 600 学时

要求学生在教师指导下完成一项工程设计（研究）任务，并独立完成一篇论文，包括开题、中期检查和论文答辩。是训练学生综合运用所学知识分析解决实际问题的基本能力，培养总结和表述研究工作的能力、培养创新意识和思维能力的综合训练环节。

*** 电磁场与微波实验

i.e. Electromagnetic Field and Microwave Experiment

1 学分 26 学时

本课程是在“电磁场与波”/“电动力学”的基础上，为促进学生深入理解和掌握电磁场相关原理知识的实验课程，它将为学生今后从事相关领域的学习和科研工作打下坚实的基础。课程针对电磁场“看不见、摸不着”的特点，以动画演示的方式，为同学们讲解电磁场在各类传输线、微波元器件、自由空间中的传播特性，包括电磁场的分布、时域特性、频域特性、辐射特性等。操作内容在三套实验系统上完成，电磁波综合测试仪、测量线系统、矢量网络分析仪。电磁波综合测试仪上涉及电磁场的内容，包括电磁波的传播特性、反射折射特性、极化特性等；测量线系统的内容有利于学生建立场的驻波分布概念，从而进一步理解场的分布和传播理论；矢量网络分析仪是应用于射频和微波频率的先进测试仪器，利用这个仪器，学生可以进行关于各类微波元器件的阻抗、匹配、传输参数等特性的测量研究。

课程还通过微波仿真软件 ADS（Advanced Design System）的熟悉和使用来掌握微带线的基本原理和特性，建立了更加完善的电磁场与微波实验教学体系内容。

*** 移动通信与卫星通信

i.e. Mobile Communications and Satellite Communications

2 学分 32 学时

以现代移动通信和卫星通信系统为背景，讲述现代移动通信中的基本概念和卫星通信中的基本理论，介绍典型移动和卫星通信系统中的系统结构、关键技术和实际应用，以及未来无线通信技术的发展趋势，培养和激发同学的兴趣与热情。

*** 数字电视传输技术

i.e. Digital TV Transmission Technology

2 学分 32 学时

数字电视传输技术是现代数字通信的一个研究热点，目前已经到了可以实用的阶段。本课程重点介绍相关调制解调、信道编解码、同步和信道均衡等技术，完善学生数字电视传输方面的知识。本课程分析当前及未来数字电视系统所采用的传输技术，并指导学生使用仿真软件进行性能仿真， 培养学生理论学习与实际仿真相结合的能力，同时通过仿真使学生加深对通信原理的理解。使学生掌握数字电视传输系统的构成原理、实际工程设计所要考虑的各种因素，培养学生数字通信系统整体设计的观念。

*** 无线信号的光纤传输技术

i.e. RF Over Fiber Technologies For Wireless Communications

2 学分 32 学时

本课程是光通信、光电子类专业的入门基础课，介绍光通信技术的发展历史、产业现状和研究前沿，讲解光通信系统中基础器件的工作原理，包括激光器、电光调制器、光电探测器、光纤、光放大器、波分复用器等；介绍光传输链路的性能指标和分析方法，针对简单的例子进行数学分析和数值模拟；最后介绍模拟光链路的典型应用，包括超宽带微波光子信号产生和处理、光子数模/模数转换器、光控微波波束形成、光纤射频信号传输、光纤频率分配等。

*** 通信网络设计实例研究

i.e. Case Study on the Design of the Communication Networks

2 学分 32 学时

以目前正日益得到广泛重视的电力线通信/网络的设计作为题目，通过文献调研、课堂讲解（任课老师/选课同学共同参与）、分组讨论、实验设计与现场参观介绍等手段，以互动形式，启发学生研究和探索的兴趣，培养学生的思维方式和研究方法，鼓励学生的交流和合作，锻炼学生应用已有知识（主要是从其他专业基础课、专业课课堂上系统学习所获得的知识）解决实际问题的意识和能力，帮助学生掌握撰写科学论文、实验报告或者是文献综述的基本技巧。电力线通信系统/网络这个领域比较新但应用面非常广泛、涉及的基础理论知识也非常多。但当前相关参考文献少（能减少文献调研负担并突出重点）；许多问题还没有现成答案可循，希望以此刺激学生的研究兴趣，争取新成果。

*** 网络技术基础

i.e. Fundamentals of Network technology

2 学分 32 学时

本课程是面向本科中高年级的网络技术基础课程，涵盖通信和计算机网络中的基本概念。重点集中于数据链路、网络和传输三个层次，以网络技术为线索，引出若干重要的网络基础理论，以澄清网络结构、工作原理和性能分析工具等基本概念。

*** 微波电路设计

i.e. Design of Microwave Circuits

2 学分 48 学时

微波电路是构成通信系统、雷达系统和微波应用系统中的发射机和接收机的关键部件。随着科技的发展，各种电路的原理日趋成熟，结构形式多样，工作频率越来越高，带宽也越来越宽。为了适应该领域科技发展的需要，电子工程系开设了《微波电路设计》课程。

本课程是为了学生尽快适应微波工程领域中国际领先科研工作的需要而新开设的，是设计研究型实验。

本课程主要针对通信、雷达系统的典型单元电路，如滤波器、功率分配器、分支线电桥、低噪声放大器等，完成从软件设计到硬件实现的全过程。研制的电路采用微带线结构形式，工作频段在 1~8.5GHz。同时紧跟学科发展方向，对部分电路提出小体积和宽频带的要求。

本课程还通过对无线通信系统收发信机的系统仿真和测量研究，培养学生建立系统级概念。实验室为学生们提供了先进的设计研究环境，使用安捷伦公司先进的微波设计软件 ADS（Advanced DesignSystem）、SystemVue 和矢量网络分析、信号源、频谱仪等测试仪器。这些都将为学生将来更好的适应科研工作打下坚实的基础。

*** 网络信息论

i.e. Network Information Theory

1 学分 16 学时

网络信息论是现代通信理论和技术研究中一新的国际研究方向。它的基本目标在于能将原本分离的物理层Shannon 信息理论与网络层的路由、调度控制与交换理论有机地组合在一起，以提高整个网络的传输效率。目前网络信息论的研究主要侧重在两个基本问题上，首先是网络的容量估计问题，其次是逼近网络容量的可实现性方法研究。本课将以探讨的方式开展侧重于网络信息论中的网络容量分析的研究，同时寻找一些相应的编码、调度和交换处理算法观察它们对网络容量的逼近特性。主要内容包括网络信息的发展史 ，网络信息论的研究基础，网络编码专题，数字喷泉码专题，大数据与网络信息论专题，排队论与信息论组合专题，网络信息论在高速列车通信系统设计中应用专题等。

具体学时分配：

#+BEGIN_EXAMPLE
网络信息论历史与基础部分 6 学时；
其他专题共计 8 学时；
论文阅读和专题讨论 2 学时；
课外学时要求：每个学生需从网络下载 2 到 3 篇相关方向的杂志论文，阅读，总结，并结合课堂讲解，进行课堂讨论展示，并撰写综述报告。
#+END_EXAMPLE

*** 国防信息系统概论

i.e. Introduction to Defense Information System

3 学分 48 学时

本课程为电子信息系统专业的专业课，主要讲授雷达、通信、导航、声纳、遥感以及信息网络（包括相应的对抗技术）等现代军用或者军民两用信息系统的基本概念、系统结构、工作原理、主要的战技性能以及在军事方面的应用。

*** 语音信号处理实验

i.e. Experiments on Speech Signal Processing

1 学分 32 学时

本课程共进行四次语音信号处理实验，包括三次基础实验和一次自主型项目实验。

1）语音信号特征分析实验：掌握语音信号特征分析方法，分析的特征包括短时过零率、短时自相关、短时能量特征和 LPC 预测系数，并能根据这些特征进行简单的端点检测和基音周期估计。

2）语音参数编解码实验：掌握语音信号特征提取和参数编码方法，能够完成简化的 LPC-10 声码器设计，在编码端实现清浊音判别、基音周期提取、LPC 等效参数提取、参数量化，在解码端实现激励信号和滤波器设计合成语音。

3）语音分类识别实验：掌握统计分类和动态时间规整算法方法，掌握训练单高斯模型进行两类数据分类的方法，能够通过提取 LPC 参数、模板匹配及识别来进行长短不一的孤立词识别。

4）自主型实验要求学生完成至少一个小型语音信号应用项目，以报告及成果展示形式为最终输出，鼓励学生结合实验成果撰写科研论文，培养学生初步的科研能力。

*** 语音信号处理

i.e. Speech Signal Processing

3 学分 48 学时

语音信号处理课程的内容主要是由 9 个章节组成。

#+BEGIN_EXAMPLE
第一章：语音信号的时域及频域特征分析
第二章：语音信号的产生模型—声管模型
第三章：语音信号的同态处理技术
第四章：语音信号的线性预测编码技术
第五章：人耳的听觉系统
第六章：语音信号的波形编码
第七章：语音信号的参数编码
第八章：语音合成与修整技术
第九章：语音识别技术
#+END_EXAMPLE

*** 光电子技术实验

i.e. Optoelectronics Laboratory

2 学分 50 学时

“光电子技术实验”是一门光电子技术专业限选实验课，涉及激光原理与技术、物理光学、现代光学、光电子技术等方面内容，包括典型激光器与光放大器、光的调制与转换技术、光纤器件、光纤通信与光传感技术、光电子应用技术等实验内容。课程以综合型实验为主，设有设计型实验，从基础知识延伸到前沿应用。通过独立搭建实验系统和师生讨论式的教学方式，使学生不但掌握实验原理和实验技术，而且通过自主设计实验条件，体会科学实验的过程，培养分析解决实际问题的能力。

实验内容主要涵盖五类技术：1.典型激光器特性研究；2.电光、声光等调制技术；3.光纤通信；4.光纤传感；5. 现代光学（全息）。共安排 1 次讲课 8 次实验课，两人一小组。前 5 次是由实验室安排的大循环实验，包括 4 次实验和一次口头交流；第 6、7 次完成一个开放的设计实验；最后就设计实验完成一次口头报告。

前 4 次实验在如下实验中选择 4 个：

#+BEGIN_EXAMPLE
1.固体激光器的静态特性及调 Q 技术；
2.电光调制与语音信号传输
3.声光偏转与声光调制
4.光纤放大器增益与噪声特性
5.光纤长距离传输系统设计
6.光纤光栅特性与应用
7.波分复用光纤传输系统
8.全息照相
#+END_EXAMPLE

*** 通信系统

i.e. Communication Systems

3 学分 48 学时

现代社会的发展需要提供在任何时候、任何地方、与任何人都能及时沟通联系、交流信息的通信手段。符合这一要求的通信技术和系统在最近十年来取得了飞速的发展，日益成为现实生活中必不可缺的内容，成为信息社会的基础。同时，通信系统的多样性和复杂性也在学生理论联系实际的过程中带来了不少的困难和障碍。即使当今社会的通信技术发展呈现如此纷繁复杂的局面，有差异的通信系统中内含了很多共性的知识点。

《通信系统》的开设旨在剖析隐含在其中的共性科学问题，在此基础上，区分重点地介绍典型通信系统的设计原理和相关知识。本门课程是电子科学与技术领域的一门重要的专业限选课。本课程主要介绍微波中继通信、移动通信、卫星通信等典型通信系统的原理、组成及链路计算，电缆通信、光通信、数字广播的相关知识，以及通信领域的最新研究成果及发展方向。 通过本课程的学习，使学生了解通信系统的内在科学问题、组成及原理，为今后从事通信领域相关工作打下良好的基础。

*** 数字电视传输系统实验

i.e. Experiment on Digital TV Transmission System

1 学分 16 学时

本实验立足于将科研成果转化为实验教学的基本思想，加强科研与教学的结合，结合在数字电视地面传输技术的研究过程中积累起来的 TDS-OFDM 理论基础和实际系统开发经验，以数字电视地面传输系统为应用实例，通过系统分析和实验，加深同学们对基础理论知识和学科前沿技术发展的理解，对于培养学生的工程实践能力和创新能力具有重要意义。通过对地面数字电视传输系统的学习，可以全面掌握数字电视传输系统的组成、原理，通过对实验平台的编程控制与研究，可以全面掌握信源编解码和信道编解码技术的要点。本实验平台通过对地面数字电视传输系统的分析讲解，使同学们能够对理论课程中学到的各个知识点进行有效贯通，理解每个模块在信号传输过程中所起的作用，并且，还能指导学生从宏观系统设计的角度，根据应用需求，如何设计一个完整的通信系统。

本实验平台除了涵盖信道编码、调制映射、交织、信号组帧、成形滤波等通信系统的基本组成部分外还包括信源的编码解码技术。

本实验鼓励学生进行创新研究，在完成基本实验内容的基础上，实验平台的关键模块（如信道估计等）可以替换为同学们提出的新方法或新结构，并且进行软硬件平台验证。

*** 电子系统设计

i.e. Electronic System Design

2 学分 48 学时

1.现代电子系统设计导论：介绍电子系统的组成和内部结构，构建系统的不同方法和设计思想，系统需求划分和功能划分，电子系统的设计与实现过程，包括资料检索、元器件购置、设计模拟、电路板设计、焊接调试等；

2.电子系统的工程实现：介绍电子系统的关键参数和指标；系统的可靠性设计，包括干扰、干扰类别、电磁兼容、隔离与去耦；电路板的设计，包括电路板设计软件使用介绍、可靠性设计与安装；电子系统的调测，包括调测方法、仪器的正确使用及系统参数的各项测试；

3.项目的设计与实现：包括项目选择、系统设计方案、开题、实现、验收、答辩、演示等环节。

*** 信息网络原理与设计

i.e. Principles and Design of Information Networks

3 学分 48 学时

本课程面向信息通信网络，以网络的核心概念（接入、交换、路由、流量控制、移动性管理等）为主线展开，通过对信息网络的代表性技术及其原理的穿插讲授，并辅以不同网络形式下的应用举例，内容主要涵盖：网络分层模型与可靠传输、网络延时分析（排队论基础）、多址和随机接入、交换原理与技术、路由与移动性管理、流量控制与资源分配，最终展望信息网络的最新进展，如软件定义网络，网络功能虚拟化等。作业以理论题、论文阅读评述和仿真实验为主。

*** 光通信技术

i.e. Optical Communications Technologies

3 学分 48 学时

光纤通信是现代信息社会的基石，从越洋通信到光纤到家，从电信网到数据中心，从数字传输到无线信号光纤分配，光纤在整个通信网中的地位已举足轻重。

本课程重点讲述光通信技术的原理。内容包括：光通信发展历程与趋势，光信号在光纤中传输特性；光发送机、接收机与光放大器等关键单元的基本原理；波分复用技术及其关键器件；光交换与光网络关键器件与技术；光纤通信系统的设计原则。课程以信号与系统的角度讲述光通信系统中的关键器件和子系统，侧重于基本物理概念和系统相结合，从而加深对跨信息与电子两个学科的基础知识的理解。

** 微电子与纳电子学系

*** 晶体管的发明和信息时代的诞生

i.e. The Invention of Transistors and the Birth of Information Age

1 学分 16 学时

晶体管的发明，是二十世纪最重要的科技进步。晶体管及以晶体管核心的集成电路是现代信息社会的基础，对社会的进步起着无以伦比的作用。晶体管的发明，源于 19 世纪末 20 世纪初物理学、电子学以及相关技术科学的迅速成熟。晶体管的发明造就了一大批伟大的物理学家、工程师。晶体管的发明，也随之产生了许多著名的研究机构与重要的公司，如贝尔实验室、仙童公司、Intel 等都与晶体管的发明密切相关。 “以铜为鉴，可正衣寇；以古为鉴，可知兴替；以人为鉴，可明得失”。晶体管发明作为现代科技史上的重大事件发生过鲜为人知的重要经验和教训，涉及科研管理、人才和科学方法等诸多方面，可以从成功和失败两个方面为后人提供十分重要的借鉴与启示。本课程试图从晶体管的发明到信息社会的诞生，探讨技术革命和创新的方向，为大学低年级学生将来从事科学研究建立正确的思想观。所讨论的课题包括，科学预见和准确选题的重要性、科学研究的方法、放手研究的政策、知人善任和合理配备专业人才等。

*** 量子信息处理的超导实现

i.e. Quantum Information Process and its Implemention with Superconducting devices

1 学分 16 学时

基于半导体集成电路的经典信息处理技术已渗透到我们生活的各个方面，信息处理器件，例如个人电脑和手机，为我们生活质量的提高提供了强有力的技术支持。但是经典信息处理技术的继续发展面临着技术上的瓶颈，其性能很难在现有技术路线上继续提高。一种新型的完全基于量子力学原理的量子信息处理技术，有望提高信息处理的效率并解决一些经典信息处理技术无法解决的问题。 量子信息处理技术的成功实施，将为我们提供绝对保密的量子通信技术和高效的量子计算机。本课程将学习量子信息处理的基本原理；超导材料的基本特性以及利用超导器件实现量子信息处理的原理与方法。通过文献调研和小组讨论等方式了解利用超导器件实现量子信息处理的最新进展和面临的挑战，探讨可能的解决方案。

*** 智能传感有社会生活中的应用

i.e. Smart Sensing in Social Activities

1 学分 16 学时

智能传感已经深入到社会生活的各个领域，深刻地影响着我们的社会组织方式和行为方式。在物联网、人工智能、大数据、工业 4.0 等众多改变人们生活方式的热门领域背后，无不以大量的智能传感器作为海量数据信息的来源。本课程采用视频、图片等多媒体方式，以活泼生动地方式，向具有不同专业背景的学生深入浅出地讲述智能传感器及其在社会和生活中的应用。例如，在文化与智能传感器章节中，结合大家熟知的电影形象《指环王》中的“咕噜” ，介绍智能运动传感器在电影制作中的应用；结合《机械战警》中的形象，介绍脑机接口传感器在脑神经科学研究及帕金森症等疾病治疗中的应用。在传感器与智能交通章节中，介绍汽车中种类繁多的传感器在未来无人驾驶汽车的作用。在传感器与智能家居章节中，介绍 iphone手机中集成的多种传感器，及其功能扩展。在传感器与现代国防章节中，结合南斯拉夫亚炸馆事件，介绍控制炸弹穿透多层建筑后再爆炸的加速度传感器，以及给炮弹装上“眼睛”的惯性传感器组合。在传感器的形成艺术章节中，介绍防尘保护到只露出眼睛的技术人员在超净工厂中制造集成传感器的方法等等。此外，学生还将参观清华大学微纳加工平台，直观了解生产智能传感器和集成电路的设备和工艺。

*** 固体量子计算和量子相干器件简介

i.e. Introduction to Solid-state Quantum Computing and Quantum Coherence Devices

2 学分 32 学时

作为量子力学和信息学的交叉，量子信息学是最近二十多年迅速发展起来的新兴学科，量子信息处理技术能够完成许多经典信息技术无法实现的任务。比如，一旦基于量子信息学的量子计算机得以实现，其在几分钟内就可解决数字计算机几千年才能解决的问题，那么用它就可及时地破解基于某些数学问题复杂性假定之上的传统保密通信的密钥，从而对建立于经典保密系统行业的信息安全构成根本性的威胁。这种新兴技术的实现可以直接地应用于国防，政治，经济和日常生活。本课程在此大的学术背景下展开，主要介绍最有希望成为量子比特的固体量子相干器件的原理和目前的研究状况，以及如何用这些器件实现量子计算。

*** 石墨烯及二维纳电子技术

i.e. Graphene and Two-dimensional Nanoelectronic Technology

2 学分 32 学时

石墨烯及二维纳电子技术是近年来国际学术界公认的热门研究领域之一，该领域的研究带动了新材料、新工艺、新方法和新技术等领域的全面发展，并对当代信息科学技术和社会发展产生了革命性的影响。本课程系统总结了国内外石墨烯等二维纳米材料领域的最新进展和重要成果。课程内容主要包括：以石墨烯为代表的二维纳米材料的发现、结构、性质及表征方法；石墨烯等二维纳米材料的制备方法；石墨烯等二维纳电子材料和器件在微电子与集成电路技术、光电技术、新能源、生物医学、环境技术、智能传感等领域的研究和应用。

*** MEMS 与微系统

i.e. MEMS and Microsystems

2 学分 32 学时

MEMS 与微系统是一门前沿交叉学科，将对生物医学、汽车、仪器、化学能源、通讯、纳米科学、航空航天、等领域产生重大影响。本课程将在讲授 MEMS 多学科基础知识的基础上，系统讲述微机电系统的设计及加工技术，包括微电子机械系统原理、设计方法、体和表面微加工技术，以及微电子机械系统在生物医学、汽车、化学能源、通信等领域的应用。主要采用讲授的方式完成。重点内容包括微系统的基本力学和建模方法、表面微加工和体微加工技术、微型传感器原理及设计制造、微型执行器、RF MEMS 典型器件、光学 MEMS 的分析与设计、微流体与芯片实验室、BioMEMS 等。

*** 微电子工艺技术

i.e. Microelectronics Fabrication Technology

2 学分 32 学时

本课程主要讲授硅集成电路制造的工艺。首先，在介绍单晶硅的生长、晶园的制备以及集成电路制造污染控制方法和制造环境后，重点学习微电子制造工艺各单项工艺的基本原理（包括氧化、扩散、离子注入、薄膜淀积、快速退火、光刻、刻蚀、金属化工艺等），并了解常用的工艺检测方法、集成电路工艺集成技术和工艺技术的发展趋势等。其次，课外通过计算机模拟试验，学习氧化、扩散、离子注入等工艺设备的简单操作和模拟方法；学习版图的基本设计方法。第三，课外组织观看工艺录像，并到微电子学研究所微纳加工平台参观。

*** 固体物理学

i.e. Solid State Physics

3 学分 48 学时

固体物理学是固体材料和固体器件的基础。该课程主要研究晶体的结构及对称性，晶体中缺陷的形成及特征，晶格动力学，能带理论的基础知识以及晶体中的载流子输运现象等。是微纳电子专业的核心课。

*** 半导体物理学

i.e. Semiconductor Physics

3 学分 48 学时

主要讲授半导体材料的基本物理知识，半导体器件基本结构的工作原理。主要内容包括：半导体材料基本性质（能带结构），半导体中的电子态和平衡载流子统计，载流子的输运过程（非平衡载流子，过剩载流子的产生和复合，载流子的漂移、扩散，散射，热载流子效应，电流连续性方程），PN 同质和异质结、金属-半导体接触的电学特性，MOS 结构物理，半导体基本光电特性。

*** 微电子工艺技术（英）

i.e. Integrated Circuit Fabrication Processes

2 学分 32 学时

本课程授课目的是使学生掌握微电子制造的各单项工艺技术，以及亚微米 CMOS 集成电路的工艺集成技术。本课程讲授微电子制造工艺各单项工艺的基本原理（包括氧化、扩散、离子注入、薄膜淀积、光刻、刻蚀、金属化工艺等），并介绍常用的工艺检测方法和 MEMS 加工技术、集成电路工艺集成技术和工艺技术的发展趋势等问题。另通过计算机试验，可学习氧化、扩散、离子注入等工艺设备的简单操作和模拟。并简单介绍硅片制备，和芯片封装、测试技术。

*** 电子学基础

i.e. Fundamentals of Electronics

3 学分 48 学时

本课程主要内容：电路原理部分包括电路基础、电路分析方法、正弦量与频率分析、一阶二阶瞬态等内容。电子电路部分包括集成电路工艺流程与 MOS 晶体管的 IV 特性、共源放大器、共栅放大器和源级跟随器、电流镜和电流源、差分放大器、反馈分析与频率补偿、运算放大器与应用电路、双极型电路基础等内容。

*** 集成电路基础（1）

i.e. Foundations of Integrated Circuit（1）

3 学分 48 学时

本课程从晶体管和基本功能单元的层面介绍数字集成电路设计的基本概念和技巧，引导学生从逻辑设计概念进入 CMOS 电路设计。具体内容包括：数字电路布尔逻辑；MOSFET 电气特性；CMOS反相器和逻辑门电子学分析（直流特性、开关特性、功耗等）；高速 CMOS 逻辑电路设计及 CMOS逻辑的高级技术；时序单元电路；加法器设计；CMOS 集成电路物理结构、工艺流程和物理设计简介。

*** 信号与系统

i.e. Signals and Systems

3 学分 51 学时

一、信号与系统的时域描述

#+BEGIN_EXAMPLE
1、连续时间和离散时间信号与系统的数学表示
2、连续时间与离散时间线性时不变系统的时域特性
#+END_EXAMPLE

二、连续时间信号的频域分析

#+BEGIN_EXAMPLE
1、连续时间周期信号的傅里叶级数，包括定义、收敛要求和数学性质；
2、连续时间非周期信号的傅里叶变换，包括定义、收敛、数学性质、卷积；
3、连续时间信号的拉普拉斯变换，包括数学定义、收敛、数学性质，对线性时不变系统的分析，系统函数。
#+END_EXAMPLE

三、离散时间信号的频域分析

#+BEGIN_EXAMPLE
1、采样，包括采样定理、采用类型、重建与混叠等；
2、周期与非周期离散时间信号的傅里叶变换，在线性时不变系统分析中的应用；
3、z 变换，包括数学描述、数学性质，离散系统的数学描述和系统函数分析。
#+END_EXAMPLE

四、线性时不变系统分析

#+BEGIN_EXAMPLE
1、连续与离散线性时不变系统的频率响应分析；
2、反馈与稳定性分析，包括线性反馈系统的数学定义和稳定性分析判据；
3、常见电路与系统分析。
#+END_EXAMPLE

*** 集成电路基础（1）（英）

i.e. Foundations of Integrated Circuit（1）

3 学分 48 学时

本课程旨在讲授数字电路和晶体管级数字集成电路的分析与设计方法。以 CMOS 数字集成电路为主，首先介绍数字集成电路的设计方法和流程，然后介绍数字电路布尔逻辑、PN 结二极管与 MOS 晶体管、CMOS 反相器、组合电路与时序电路，最后介绍加法器与移位器。重点分析和讲授数字集成电路的基本单元电路、逻辑设计与电路设计方法、面积-速度-功耗的折中优化策略等。

*** 集成电路基础实验

i.e. IC Fundamental Laboratory

2 学分 54 学时

课程内容由知识与技能培训（教学）、六个实验组成。

知识与技能培训部分以讲课与练习为主，包括：基于 FPGA 和硬件描述语言的数字电路设计，基于印刷电路板的电路设计与制作。课程安排 6 个实验，为三个板块。

板块一：数字集成电路的测试与应用，包括基本逻辑单元的测试（实验 1）、基于基本逻辑单元的数字电路设计（实验 2）、基于可编程逻辑的数字电路设计（实验 3）；

板块二：模拟集成电路的测试与应用，包括：运算放大器芯片的测试（实验 4）、实用模拟电路设计（实验5）；

板块三：较复杂数字、模拟混合系统的设计：血氧饱和计的设计实现（实验 6）。

*** 半导体物理与器件（1）

i.e. Semiconductor Physics and Devices（1） -- Basic Principle

4 学分 64 学时

本课程是微电子技术专业必修的一门专业主干课，是研究集成电路设计和微电子技术的基础课程。通过本课程的学习，掌握半导体物理基础、半导体器件基本原理和基本设计技能，为学习后续的集成电路原理、CMOS 模拟集成电路设计等课程以及为从事与本专业有关的集成电路设计、制造等工作打下一定的基础。

*** 集成电路基础（2）

i.e. Fundamental Integrated Circuits（2）

3 学分 60 学时

课程教学内容与国外著名大学的同类课程内容接轨，并根据清华大学学生所具有的电路基础和特点进行设置。本课程以集成放大器为主线，讲授模拟集成电路基本单元的分析和设计方法，使学生初步具有从事模拟集成电路分析和设计的能力，并培养学生初步的模拟集成电路设计经验。

通过课程学习，（1）培养学生完整的模拟集成电路分析能力，包括大信号分析、小信号分析、频率响应分析、噪声分析、反馈系统分析、稳定性与频率补偿分析；（2）培养学生的模拟集成电路设计能力，锻炼学生的工程性思维，通过引入目前工业界广泛使用的设计方法、设计流程（Gm/ID 设计方法等）以及 EDA 设计工具（Hspice、Cadence 等）并辅之以工程设计型作业和课程设计，要求学生掌握常用的基本集成放大器的设计方法及调试手段，培养学生初步的工程设计经验；（3）培养学生对基础模拟集成电路单元的拓扑结构及基本性能特性的认识，使学生具有初步的电路拓扑结构的选择能力，这些电路单元包括各种单管放大器、差转单放大器、两级跨导放大器、电流镜、能隙基准源等。

*** 量子信息学引论

i.e. Introduction to Quantum Information Science

2 学分 32 学时

量子信息学是运用量子力学基本原理进行信息的编码、通信与处理的新兴交叉学科。本课程深入浅出地介绍量子信息科学领域的主要思想与方法，一方面提供理解量子信息学所需的物理、数学、计算机科学的知识背景，另一方面使大家理解并掌握本领域的基本工具与结果。具体内容分为六章。第一章介绍量子信息学的历史发展和基本概念，突出一些重要的待解决的问题。第二章深入介绍量子信息学所需的量子力学的基本概念和量子信息学所需的计算机科学的基本概念。第三章描述量子计算所需的基本元件和许多基本操作。第四章讲解简单的量子算法，量子富立叶变换及其在因数分解与离散对数问题中的应用，并解释这些结果对于密码学的重要性。第五章采用实验中已经成功实现的例子，讲解量子计算机的一般设计原则与物理实现的满意判据。第六章讲解量子信息学的最新进展。

*** 模拟集成电路分析与设计

i.e. Analysis and Design of Analog Integrated Circuits

3 学分 48 学时

（1）培养学生完整的模拟集成电路分析能力，包括大信号分析、小信号分析、频率响应分析、噪声分析、反馈系统分析、稳定性与频率补偿分析；

（2）培养学生的模拟集成电路设计能力，锻炼学生的工程性思维，通过引入目前工业界广泛使用的设计方法、设计流程（Gm/ID 设计方法等）以及 EDA 设计工具（Hspice、Cadence 等）并辅之以工程设计型作业和课程设计，要求学生掌握常用的模拟集成电路单元（如能隙基准源、两级全差分跨导放大器、Telescopic、折叠 Cascode 放大器等）的设计方法及调试手段，培养学生初步的工程设计经验；

（3）培养学生对各模拟集成电路单元的拓扑结构及基本性能特性的认识，使学生具有初步的电路拓扑结构的选择能力，这些电路单元包括各种单管放大器、 Cascode 放大器与差分放大器、电流镜、自偏置电流源、能隙基准源、两级跨导放大器、高性能跨导放大器（Telescopic、折叠 Cascode、有源 Cascode等）等。

课程教学内容与国外著名大学的同类课程内容接轨，并根据清华大学学生所具有的电路基础和特点进行了调整。调整后，本课程以集成放大器为主线，讲授模拟集成电路基本单元的分析和设计方法，使学生初步具有从事模拟集成电路分析和设计的能力，并培养学生初步的模拟集成电路设计经验。

*** 超大规模集成电路 CAD

i.e. Very Large Scale Integrated Circuit CAD

3 学分 48 学时

课程内容主要为集成电路计算机辅助设计技术，要求掌握原理和 EDA 设计方法。具体内容包括：VLSI CAD基本算法；仿真方法；高层次综合；逻辑综合；形式验证；测试方法；物理设计-版图分割、布局布线、压缩。课程安排 5 项算法实验。用计算机语言实现课上和课外获得的算法知识。通过对这门课程的学习，学生可以掌握 VLSI 计算机辅助设计工具的基本原理和方法。

*** 集成电路课程设计

i.e. Project on Integrated Circuits Design

3 学分 48 学时

本课程为加强学生的电路设计与分析能力、掌握集成电路的设计流程而设立的，主要内容包括：集成电路的基本概念；集成电路的工艺与版图流程；集成电路中的元件；版图设计规则；版图识别和提取电路；全定制设计流程的介绍；全定制设计流程中的电路设计、电路仿真、版图编辑、版图验证、寄生参数提取、后仿真等内容；基于单元综合的设计流程的介绍；基于单元综合设计流程中的代码设计、仿真、综合、布局布线、验证等内容。课程项目设计一个 10-bit 循环式模数转换器的电路设计、仿真和版图设计，要求最后提交整个转换器的版图，并提交标准的项目设计报告。

*** 专业英语

i.e. Speciality-reading in English

2 学分 32 学时

“微电子学专业英语”课程是面向本科高年级学生开设的一门旨在提高学生在微电子与集成电路专业领域英语阅读、翻译及写作水平的任选课程。根据微电子学专业的具体要求，本课程选用最新英文原版教科书的相关章节、和相关的英语读物做教材，其中包括不同风格的英文研究论文，并辅以相应的音像资料、以及英语演讲等，力求使学生在微电子学专业英语的听、说、写等方面有所提高。

*** 数字集成电路分析与设计

i.e. Digital Integrated Circuit Design

3 学分 48 学时

本课程讲授数字集成电路的分析与设计，以 CMOS 集成电路为主，在回顾集成电路器件的基础上讲授 CMOS反相器、组合逻辑电路和时序逻辑电路的工作原理，互连线的寄生参数和延时模型，算术运算逻辑功能单元以及半导体存储器的结构与实现，并介绍数字集成电路与系统的分析方法和设计流程。针对数字集成电路的各种类型和基本单元，通过课堂授课、答疑讨论、作业、模拟实验和课程设计等环节，培养学生分析和设计数字集成电路与系统以及优化电路结构、面积、速度和功耗等方面的能力。

*** 纳电子学导论

i.e. Introduction to Nanelectronics

2 学分 32 学时

本课程为微纳电子学系本科专业课程。通过本课程学习，掌握纳电子学的基本概念、原理、方法与技术，了解微电子向纳电子发展的学科与技术前沿。课程的主要教学内容包括纳米 CMOS 技术、共振隧道现象与器件、单电子器件、碳纳米管电子学、自旋电子学、超导电子学、分子电子学、纳电子机械系统、纳电子工艺等方面的基本知识，以及纳电子相关领域的前沿进展。

*** 综合论文训练

i.e. Diploma Project（Thesis）

15 学分 600 学时

综合论文训练是本科生按照培养方案达到培养目标的重要环节，也是训练学生解决实际问题的基本能力、培养创新意识和创新能力的综合环节。该环节要求学生在教师指导下综合运用所学知识，完成一项课题研究或相应的综合训练任务，并独立完成一篇论文，作为学生的“学士学位论文”。

*** 微纳电子实验 A

i.e. Lab. Work of Microelectronics and Nanolectronics A

1 学分 32 学时

1） 集成电路测试（包括功能，及各种直流参数测试）
2） 计算机模拟实验：包括集成电路工艺模拟、器件模拟、Spice 模型参数提取等；
3） 半导体器件实验：测 MOSFET 的三类 I-V 特性以获取：阈值电压 VT、衬偏调制系数（体因子）γ 、亚阈值斜率、反型层载流子迁移率。

*** 微纳电子实验 B

i.e. Lab. Work of Microelectronics and Nanoelectronic B

1 学分 32 学时

本课程有如下几个实验：

1. 半导体物理实验

#+BEGIN_EXAMPLE

1）.MOS 高频 C-V 特性测量（计算二氧化硅中的固定电荷和可动电荷）
2）.霍尔效应实验
#+END_EXAMPLE

2. 纳电子教学实验

量子点红外探测器实验

*** 微纳电子材料器件分析技术

i.e. The Characterization of Micro & Nano-electric Materials and Devices

2 学分 32 学时

本课程将介绍微纳电子材料等的表面形貌微观结构成分的分析测试方法，具体包括：

第一部分：X 射线分析技术：利用 X 射线衍射（XRD）技术对物质的晶体结构、物相信息、取向度以及微观应力等进行分析，并简要介绍 X 射线荧光技术（XRF）进行成分分析的方法

第二部分：电子显微分析技术：介绍电子显微分析方法，如：扫描电子显微分析技术（SEM）和透射电镜显微分析技术（TEM）；并对扫描隧道显微技术（STM）以及原子力显微镜（AFM）分析技术进行介绍。

第三部分：表面分析技术：对表面分析技术及其分析方法进行介绍，重点介绍俄歇电子能谱（AES）分析及应用，X 射线光电子能谱（XPS）以及二次离子质谱（MI）等分析技术

第四部分：光谱分析技术：介绍光谱分析的基本方法，主要包括：红外光谱分析技术、拉曼光谱分析技术及紫外-可见光谱分析技术，重点介绍这些分析方法在微电子技术中的应用

第五部分：新型微纳电子器件简介：：介绍新型微纳电子器件及其分析方法的综合应用，并对本课程中涉及到的各种分析方法进行总结

每一种分析技术中又介绍相关原理、分析方法、能达到的性能指标以及在微纳器件方面的具体应用，这对于微电子、纳电子、光电子以及材料、物理、化学等学科都非常重要。

*** 数字集成电路分析与设计（英）

i.e. Digital Integrated Circuit Analysis and Design（English）

3 学分 48 学时

数字集成电路的分析与设计，包括：CMOS 反相器、组合和时序逻辑电路分析与设计、算术运算逻辑功能部件、半导体存储器的结构与实现、互连线模型与寄生效应的分析。并介绍常用数字集成电路的设计方法和流程。

*** 专业实践

i.e. Professional Practive

5 学分 200 学时

专业实践是一个重要的实践性教学环节，是培养学生综合素质、创新意识和实践能力的重要途径。目的是让学生接触实际，了解社会，学习生产技术知识。它要求学生理论联系实际，从生产和工程技术的实践中获得知识、接收基本工程技术训练，培养初步的实际工作能力和专业技能。

*** 半导体器件电子学

i.e. Semiconductor Devices

3 学分 48 学时

本课程系统介绍现代集成电路中半导体器件的工作原理，首先学习半导体物理和集成电路工艺的基本知识，然后介绍金属-半导体接触和 PN 结理论，最后重点讨论双极型晶体管和 MOS 场效应晶体管的工作原理与特性。

*** 通信系统与电路（英）

i.e. Communication Systems and Circuits

3 学分 48 学时

本课程内容涵盖了通信系统的基础理论知识及通信系统和电路结构，对模拟/数字通信系统，特别是其硬件设计进行了深入浅出的介绍。课程主要分为三大部分。第一部分介绍通信系统的基础知识。第二部分讨论有线和无线通信系统。第三部分介绍通信电路模块，包括数据转换器、放大器和振荡器等。具体内容分为六章。

*** 计算机原理与设计

i.e. Computer Organization and Design

3 学分 48 学时

本课程是为微纳电子系的本科生开设的，是微纳电子系学生，在掌握了数字电路的设计方法及集成电路工艺后，深刻理解数字电路设计的在集成电路中的体验。本课程讲述微处理器的内容如下：

微处理器的现状，发展和组成；微处理器指令设计；微处理器的性能评测；微处理器的基本运算电路（加法器和乘法器）；微处理器结构设计及数据通路设计；

控制单元状态机的硬件实现；流水线技术；存储管理与 Cache 设计；微处理器多核关键技术与最新进展。基于微电子所的 EDA 工具平台，进行实验，完成一个简单的 5 级流水线的微处理器的设计和验证，能够运行一段简单的累加程序。

*** 数字信号处理

i.e. Digital Signal Processing

3 学分 48 学时

本课程系统讲授数字信号处理的基本理论（时域、频域分析理论，抽样定理，谱估计理论等）、基本知识和基本方法（包括离散时间信号与系统的数字化分析方法，滤波器设计方法，快速算法等），该课程也结合微电子专业特色，密切联系数字信号处理在集成电路设计中的一些实际问题，以大作业报告与设计的形式，加强学生对所学知识物理意义的真正掌握。

*** 微纳电子工艺实验

i.e. Micro/Nano Fabrication Experiments

1 学分 24 学时

本门课程提供了学生动手制备微电子器件的机会，是微电子工艺课程的实验课程。通过本门课程的教学和实验，学生有机会学习 MOSFET 三极管， PN 结二极管，霍尔器件，接触电阻，电容等测试器件的基本原理，工艺流程和测试方法。学生将有机会在超净间里面自己动手，操作各种工艺设备，最后将器件制备出来，并进行完整的电学测试。涉及到的工艺包括光刻，湿法刻蚀，干法刻蚀，氧化，LPCVD，PECVD，扩散，溅射等。

*** 量子信息学引论（英）

i.e. Introduction to Quantum Information Science

2 学分 32 学时

本课程的目的就是深入浅出地介绍量子信息科学领域的主要思想与方法。是一方面提供理解量子信息学所需的物理、数学、计算机科学的知识背景，另一方面使大家理解并掌握本领域的基本工具与结果， 并介绍量子信息处理的最新成果与应用。

*** 纳米科学实验技术基础与前沿进展

i.e. Expermental Techniques and Progress of Nano-technology

2 学分 32 学时

本课程是为微纳电子系、自动化系、电子工程系、精仪系、物理系等理工科院系的本科生开设的，面向对纳米科学技术感兴趣的同学。在本课程中，我们将讲授纳米科技的前沿进展，例如量子信息学、纳米电子学、量子控制等；实验技术基础，包括真空技术、低温技术、超精细加工和量子反馈控制等；还将带学生在一线科研实验室中现场授课，讲授实验技术与设备原理。最终的考核形式包括一篇前沿纳米科技的调研报告（占总分 30%）和一个实验类的大作业（占总分 70%）。

*** MEMS 实验

i.e. Laboratory for MEMS

2 学分 52 学时

随着微米纳米技术的高速发展和物联网及可穿戴等应用领域的飞速发展，对作为这些领域重要组成部分的微纳传感器、MEMS、微纳器件等提出了迫切的要求。学术方面，上述相关的领域近年来处于高速发展期，多学科交叉的特点使相关领域产生了众多突破性的进展；产业方面，以微型传感器和 MEMS 为代表的产业进入高速增长期，世界著名的工业企业不断加大产品和研发的投入，国内的企业也进入主流产品领域。微纳加工技术和 MEMS 制造技术是实现微型传感器、MEMS 等最重要的核心技术。学术和工业界的高速发展也对相关领域的人才培养提出了迫切的需求。由于微型传感器和 MEMS 等具有依赖于制造技术的特点，任何一个产品和新器件的实现都必须对制造技术有深入的了解和充分掌握制造技术的知识。本课程作为以实验为主的课程，目的是在微纳加工和 MEMS 的制造技术相关知识的基础上，通过较多的实验环节，让学生亲手完成典型制造工艺和典型 MEMS 器件的制造，使学生在实际工艺中掌握微纳加工和MEMS 制造技术，为学生奠定科学研究和产品开发的基础。

*** 微纳电子导引

i.e. Intoduction to Microelectronics and Nanolectronics

1 学分 16 学时

结合微纳电子学科的前沿研究方向，介绍微纳电子学科的知识体系、发展历程、主要研究方向和未来发展趋势，让学生对微纳电子学科的知识体系和核心概念有总体的认识和了解，扩展学生的知识面。

** 自动化系

*** 智能交通系统

i.e. Intelligent Transportation System

1 学分 16 学时

本课程以智能交通系统的主要特征、技术发展和应用需求出发，以北京和兰州等城市的实际系统和系统设计为例，简要介绍智能交通系统的基本概念、基础理论、关键技术和典型应用系统，并结合简化的实际应用，探讨和分析计算机、控制、通讯和信息处理技术在智能交通系统中的应用，同时结合最新技术的发展，展望未来智能交通系统的发展趋势。希望通过本课程学习、讨论和调研，建立起对交通真实系统的宏观认识，以及系统控制、信息处理和系统集成在交通系统中的应用。

*** 漫话滤波

i.e. Roaming Over Filtering

2 学分 32 学时

滤波是一种从看似杂乱无章的测量数据中提取能够为我们服务的信息的方法，其应用涉及到自动控制系统设计、通信信号处理、图象处理、地质勘探、经济预测等多个工程领域。本课程结合具体工程事例，介绍滤波理论在实际应用问题的刺激下，从原始的最小二乘估计发展到 Wiener 维纳滤波器、Kalman 滤波器、鲁棒滤波器、粒子滤波器的过程；着重讨论如何从工程要求出发凝炼理论问题，并以恰当的数学工具加以解决；充分体现工程技术中蕴含大量实际的数学问题，而数学的进步又为技术发展铺平道路的绚丽景象。

*** 企业信息化概论

i.e. Introduction of Enterprise Information Systems

1 学分 16 学时

简要介绍信息与信息技术的定义、功能和内涵，介绍在互联网环境下企业运作管理面临的新挑战和机遇，介绍企业信息化的基本内涵和典型的企业信息化系统功能组成，重点介绍企业管理信息系统、办公自动化系统的功能与组成，介绍沃尔玛、通用电气、DELL、海尔等公司的信息化应用案例，介绍电子商务的发展历程和电子商务系统的主要功能（网上购物、电子银行、网上审批、网上拍卖），介绍电子商务技术在企业应用的案例，以及电子商务网站的基本组成结构，指导同学们用创新的思路为企业设计信息化应用系统或电子商务网站方案，并构建具有基本功能的企业信息化应用系统或者电子商务网站，在此基础上，指导同学们编写相关报告和论文。

*** 视觉信息获取与显示

i.e. Capture and Display of Visual Information

1 学分 16 学时

视觉信号是日常生活中承载和传递信息的最主要的通道之一，学术界对此相关研究具有较长的研究历史，且在工业界有广泛的应用。然而，传统视频信息采集、处理及显示方面均存在诸多局限性，因此国际诸多科研机构在视频信息的采集及显示等方面提出了诸多新兴的理论与技术，包括计算摄像学、光场理论、立体视频采集与显示等。 本课程以课程讲授为主，共开设 16 学时，一方面讲授视觉信息采集和显示方面的新兴理论，另一方面介绍该领域的国际学术前沿热点以及知名研究结构，开拓学生的视野，激发学生对科研工作的兴趣，增强起对基础课的学习动力，并引导其学以致用，为未来从事相关的研究工作奠定基础。

*** 交叉项目综合训练 A

i.e. Interdisciplinary Research and Practice in Dept.of Automation A

4 学分 64 学时

自动化系结合学科自身的发展特点，依托本系在生物信息、机器人以及无人机等，具有交叉特点的科研方向的积累，现设立“交叉方向”课程。该课程通过上述几个方向在国际和国内有影响的赛事吸引学生，使学生从低年级开始关注并参与该课程，尽早进入交叉方向的研究。该课程作为培养创新能力的环节，意在：鼓励交叉方向的发展，为教师提供更多的支持；为学生开阔眼界，寻找感兴趣的方向提供更多选择；引导学生感受科研精神，体验科研过程，进行科研训练。

*** 太赫兹技术概论

i.e. Intoduction of Terahertz Technology

1 学分 16 学时

太赫兹是近 20 年涌现的一门新兴技术，美国、欧盟和日本均将其列为改变未来世界的十大高新技术之一，也是世界主要大国竞相追赶的技术高地。本课程主要介绍太赫兹在探测、成像和通信领域的技术先进性及其系统，具有基础性、广泛性和趣味性特点；内容还涉及其在军事国防、安全检测、诊断医学等探测领域的巨大应用前景。课程旨在开拓学生的视野，激发学生对科研工作和对新兴技术的兴趣，增强其学习动力，并引导其学以致用，为未来从事相关的理论研究和应用开发奠定基础。

*** 太空机器人技术研讨

i.e. Space Robotics Research Communication

1 学分 16 学时

随着空间技术的发展，人类空间活动日益频繁，为了提高工作效率和降低宇航员的风险，空间机器人将在未来的在轨服务中扮演越来越重要的角色。作为空间技术的研究前沿，空间机器人技术的发展非常迅速，目前已进入工程实现阶段。本课程从空间机器人应用的背景出发，介绍和讨论其最新发展趋势。本课程将对空间机器人及其在轨服务中若干问题进行分析，使学生对这些问题的来龙去脉，已有的积累和今后的可能发展有一个比较全面的认识，并在研讨的过程中培养科研的兴趣与方法。本课程研讨的问题包括空间机器人发展简史、空间机器人国内外发展现状与趋势、空间机器人非完整约束特性、动力学奇异、协调控制、遥操作等。

*** 智能机器人初探

i.e. A preliminary Study on Intelligent Robot

1 学分 16 学时

《智能机器人初探》课程将分成三个部分进行讲解。首先关于智能机器人的基本概念，包括：机器人发展历史、机器人基本模型、控制原理等。然后是机器人其他相关基础理论知识，如机器人感知、机器人智能等。最后是对各类机器人特点进行讲解，包括：移动机器人、拟人机器人、服务机器人、空中机器人、水下机器人等。本课程还将开设相关实践体验环节，提高学生对智能机器人的实际动手能力。

*** 模拟电子技术基础

i.e. Fundamentals of Analog Electronics

4 学分 64 学时

本课程是电气、电子信息类和部分非电类专业本科生在电子技术方面入门性质的技术基础课。课程主要内容包括半导体器件，放大电路及其应用；电子系统的组成，信号的产生和转换电路，信号的运算和处理电路，功率放大电路，直流电源等。在深入分析半导体器件的结构、工作原理及外部特性的基础上，系统讲述基本放大电路、多级放大电路、集成运算放大电路、负反馈放大电路、功率放大电路、直流电源的组成、工作原理和分析方法。本课程通过对常用电子器件、模拟电路及其系统的分析和设计的学习，使学生获得模拟电子技术方面的基本知识、基本理论和基本技能，为深入学习电子技术及其在专业领域中的应用打下基础。

*** 数字电子技术基础

i.e. Digital Electronics

3 学分 48 学时

本课程是电子技术基础的两大分支之一，属于入门性质的技术基础课。课程的主要内容为电子器件、电子电路的基本原理、数字电路的分析和设计方法，以及在实际中的典型应用等。课程的知识点包括逻辑代数基础、门电路、组合逻辑电路、时序逻辑电路、脉冲波形的产生与整形、半导体存储器、可编程逻辑器件，以及数/模和模/数间的转换电路等。课程的基本要求是熟练掌握电子技术方面的基本理论、基本知识和基本技能，培养具有分析问题和解决问题的能力，为深入学习电子技术及其在专业领域中的应用打好基础。选修本课程的同时还应选修《电子技术实验》系列课。

*** 现在电子系统设计

i.e. Contemporary Electronic System Design

3 学分 64 学时

本课程主要围绕现代电子系统的设计开展实验教学。通过介绍新技术、新器件和新方法，结合典型的现代测量和控制系统的应用需求，讨论如何为实际物理系统设计相应电子系统的方法和软硬件实现的方法。实验内容以实用电子系统的设计与实现为目的，根据发展方向确定所用器件。目前主要包括基于现场可编程门阵列 FPGA 的数字系统设计实验，基于 ARM CortexM、PSoC、SOPC 的片上系统设计实验。根据系统设计的复杂程度，实验分为四个层次：基本实验，提高实验，综合实验，创新实验；以便因材施教。

*** 电子技术课程设计

i.e. Design Projects in Electronic Technology

1 学分 32 学时

本课程是在《数字电子技术基础》和《电子电路实验》课程基础上的综合性实践训练环节。目的是学习利用 EDA 工具和可编程器件完成数字电路系统的设计方法。要求学生根据任务要求，独立完成 2~3 个典型数字系统的方案设计、硬件描述语言编程、仿真分析、调试及下载验证等。

*** 数字电子技术基础 B

i.e. Fundamentals of Digital ELectronics

3 学分 48 学时

本课程为计算机科学与技术专业基础必修课，为《计算机组成与系统结构》等后续课程的学习提供必要的基础知识。课程的主要内容包括信息与编码、逻辑代数基础、门电路、组合逻辑电路、时序逻辑电路、脉冲波形的产生与整形、半导体存储器、可编程逻辑器件，以及数/模和模/数转换电路等。课程的基本要求是熟悉数字电路的基础理论、理解常用数字电路模块的基本工作原理、掌握基本的数字电路逻辑分析和设计方法，并初步具备运用所学知识解决实际数字逻辑问题的能力。

*** 数字电子技术基础 C

i.e. Fundamentals of Digital ELectronics

3 学分 48 学时

本课程是电子技术基础的两大分支之一，属于入门性质的技术基础课。课程的主要内容为电子器件、电子电路的基本原理、数字电路的分析和设计方法，以及在实际中的典型应用等。课程的知识点包括逻辑代数基础、门电路、组合逻辑电路、时序逻辑电路、半导体存储器、可编程逻辑器件等。课程的基本要求是熟练掌握电子技术方面的基本理论、基本知识和基本技能，培养具有分析问题和解决问题的能力，为深入学习电子技术及其在专业领域中的应用打好基础。

*** 数字电子技术基础

i.e. Digital Electronics

3 学分 48 学时

本课程是电子技术基础的两大分支之一，属于入门性质的技术基础课。课程的主要内容为电子器件、电子电路的基本原理、数字电路的分析和设计方法，以及在实际中的典型应用等。课程的知识点包括逻辑代数基础、门电路、组合逻辑电路、时序逻辑电路、脉冲波形的产生与整形、半导体存储器、可编程逻辑器件，以及数/模和模/数间的转换电路等。课程的基本要求是熟练掌握电子技术方面的基本理论、基本知识和基本技能，培养具有分析问题和解决问题的能力，为深入学习电子技术及其在专业领域中的应用打好基础。选修本课程的同时还应选修《电子技术实验》系列课。

*** 运筹学

i.e. Operations Research

3 学分 48 学时

本课程系统介绍线性规划、整数线性规划、非线性规划、动态规划以及网络优化问题的数学描述及求解方法。重点讨论线性规划的单纯型算法和对偶单纯型算法，整数线性规划的割平面算法和分枝定界算法，非线性规划的最优性条件和可行下降算法，动态规划的多阶段递推算法、值迭代算法和策略迭代算法，以及上述基本算法针对特定问题的改进算法，如单纯型算法在求解运输问题、指派问题及各种网络优化问题中的改进算法等。本课程采用理论与实践相结合的教学方法，利用典型实例导出优化问题的数学模型，进而分析建模条件和模型特点，并研究其最优解的性质和基本求解方法，最后通过课程研究实践深入理解课程的相关知识点。

*** 计算机语言与程序设计

i.e. Computer Languages and Programming

3 学分 48 学时

《计算机语言及程序设计》是信息学科所属各个专业的一门公共基础课程。本课程以结构化编程为思想，以 C 语言为对象，课程基本知识点包括计算机编程的 C 语言环境、简单数据结构、程序控制结构、数组、函数、指针、结构体等基本概念，以及递归、排序、查找、索引等常用算法。课程注重编程能力的培养，强化动手实践，强调对基本概念和基本方法的理解和灵活应用，课程采用 Visual C 界面编程，强调 DEBUG工具的使用和实际问题的编程实现，要求实际上机编程能力的训练。课程 8 次作业均为上机编程，考试也采用上机编程的方式。课程提倡在课程中融入科学的世界观和方法论，要求学生养成良好的编程习惯，在实践环节培养协同工作的能力，对有余力的学生引入因材施教，开展研究性学习。

*** 计算机原理与应用

i.e. Computer Principles and Applications

4 学分 64 学时

课程首先介绍了计算机中的数制和编码，然后以 80X86 系列为主，介绍了 CPU 的结构、指令系统及汇编语言程序设计，再介绍了以 IBM PC/XT 为代表的微型机系统工作原理、DOS 及 BIOS 功能调用，以及对构成微型机的主要 I/O 接口及 I/O 设备，如中断（Intel 8259A）、计数/定时（Intel 8253）、并行 I/O（Intel 8255A）、串行 I/O（Ins 8250）、直接存储器存取 DMA（Intel 8237）及模拟量 I/O（DAC1210、AD1674）等器件原理及应用， 并为覆盖和充实授课讲解内容的实践环节，提高学生的综合应用能力设置了实验课时。

*** 计算机仿真

i.e. Computer Simulation

3 学分 48 学时

本课程全面、系统地讲授系统仿真原理、理论、技术等，主要内容：（1）连续系统仿真，包括连续系统仿真模型描述，基于数值积分原理的连续系统建模方法——数值积分原理、单步法仿真建模、线性多步法仿真建模，时域离散相似法，频域离散法、采样控制系统仿真、非线性系统仿真，病态系统与间断点仿真技术等，并以 MATLAB 为工具讨论仿真实现技术。（2）离散事件系统仿真，包括基本概念，随机变量的模型确定和产生，仿真建模方法——时间调度法、活动扫描法、进程交互法、三阶段法，仿真输出分析技术——终止型仿真输出分析技术、稳态型仿真输出分析技术、多系统比较技术，方差减少技术等，并介绍典型的离散事件系统仿真软件的实现技术。此外，本课程还将结合仿真技术的最新发展，对“基于高层体系结构的仿真”和“虚拟现实技术”进行必要的介绍。

*** 计算机网络及应用

i.e. Computer Networks and Applications

3 学分 48 学时

本课程是计算机网络技术的基础入门课程，课程内容以互联网络为核心，介绍 Internet 发展、各种应用及应用层协议设计、传输层 TCP/UDP 协议和拥塞控制、网络层 IP 协议及路由选择算法、数据链路层及以太网技术、无线局域网技术及控制网络、多媒体网络、企业网络结构设计及网络安全等专题。在教学方法上，采用讲授、自学、讨论、实验、大作业相结合的方法；讲授中主要介绍基本概念和原理，梳理技术发展脉络；鼓励学生组成学习团队，探索网络中的新问题、新应用。

*** 应用随机过程

i.e. Applied Stochastic Processes

3 学分 48 学时

本课程内容包括六部分：

（1）概率论基础与随机过程一般概念：概率和概率空间，特征函数和母函数，收敛性和极限定理，条件分布与条件期望，随机过程的一般概念；

（2）离散时间马尔可夫链：定义和性质，状态空间的分解，常返态与瞬时态，平稳分布和极限分布，分支过程及案例分析；

（3）连续时间马尔可夫链：定义和性质，矩阵与向前、向后微分方程，泊凇过程，更新过程，生灭过程；

（4）布朗运动：定义、马尔科夫性和正态过程，布朗运动轨道的性质，首达时间的分布及过零点概率的反正弦定理，布朗桥的定义与性质；

（5）鞅与停时：上鞅（下鞅）及分解定理，停时与停时定理，鞅收敛定理；（6）马尔可夫决策规划：MDP 的数学描述，策略类与目标函数，有限阶段模型，折扣模型等。

*** C++ 程序设计与训练

i.e. C++ Programme Design and Training

2 学分 64 学时

本课程是以实践为主的高级语言程序设计课程，在掌握 C 程序设计的基础上，拓展到面向对象的 C++编程。本课程采用课堂授课、课上实验和课后大作业三部分紧密结合的方法，目标是使学生通过本课程的学习，掌握面向对象程序设计的基本概念和方法，C++的语法和编程方法，巩固提高程序调试方法，了解 C++模板的使用方法，了解基于 MFC 的可视化编程方法，掌握以面向对象的编程思想进行程序分析与设计的能力。课程主要内容包括 C++语言的基本介绍、面向对象程序设计的基本概念、C++类与对象、继承与重载、C++的 I/O 流、C++模板、C++异常处理方法、VC 的集成开发环境和调试方法。

*** 数据结构

i.e. Data Structures

3 学分 48 学时

本课程介绍如何组织各种数据在计算机中的存储、传递和转换，主要内容包括数组、链表、栈和队列、递归、本课程重点讲解各类数据结构的特性、实现和基本算法，了解各类数据结构的应用环境，根据问题灵活地选用各类算法及对应的数据结构。课程主要内容包括：数据结构基本概念介绍、算法复杂性分析方法、顺序和链式结构、栈与队列、串的模式匹配算法、树的概念及特性、几类典型的树及应用、图的基本概念及算法、拓扑排序与关键路径算法、最小生成树、最短路径算法、典型的查找及排序算法等。课程将从数据结构的设计者和使用者两个不同的角度深入探讨各种数据结构的设计与应用，各种算法的复杂性分析。在教学过程中，将随时补充具有前沿特色的相关理论和方法，补充实际问题中的应用，引入科研及工程实践案例，并拓广计算机及数学知识，使该课程呈现基础性、前沿性和时代性的特点。

*** 电力电子技术基础

i.e. Fundamentals of Power Electronics

2 学分 32 学时

本课程包括常用的电力电子半导体器件和功率集成模块，以及相关元器件或电路的工作原理、特性、参数与使用要求；各种电能变换基本电路的电路结构、工作原理、应用条件和分析方法；电路中强弱电接口；电力电子器件的驱动和保护；基于脉宽调制（PWM）技术的控制方法；基本电力电子电路的分析、设计、调试、故障判断及 MATLAB 仿真；一般电力电子装置及控制系统的技术要求、性能特点及分析设计方法；电力电子技术的应用现状及其发展趋势。

*** 数字视频基础与应用

i.e. Bases and Application of Digital Video

3 学分 48 学时

系统地介绍了数字视频信号处理的基本理论和技术，包括如下内容：概括介绍视频技术和视频信号分析基本方法；介绍数字视频信号处理的基本技术包括采样、建模和运动估计；讨论视频编码；介绍各种视频压缩标准；立体视频与多视点视频基础，以及最新视频研究进展中全光/光场视频基础；同时介绍了数字视频技术的前沿课题介绍。

*** 线性控制系统工程

i.e. Linear Control Systems Engineering

3 学分 48 学时

本课程是经典控制理论的后续课程，以案例教学和实践贯穿始终。

1）采用循序渐进的方法展开移动机器人案例的分析与设计，将控制系统的理论分析与工程设计通过此案例完整展示。鼓励学生通过质疑和讨论加深对现代控制理论的和控制工程的基本内容的理解；

2） 重点指导学生分组进行案例设计实践，系统掌握线性控制系统设计的方法。与系统分析有关的内容包括控制系统的状态空间描述，线性变换和特征值规范型，线性系统状态方程的解，预解矩阵和矩阵指数，状态的能控性和能观性，能控性及能观性的判据和规范型，系统的标准结构分解，状态方程控制器的设计与实现，状态空间观测器的设计及线性二次型最优控制等。与系统工程设计有关的内容包括控制系统的组成，控制系统设计的基本步骤，系统建模与仿真的方法，常用控制方案，闭环系统的稳定性分析，基于模型的控制器设计方法，控制器设计的实验验证等。

*** 模拟电子技术基础 B

i.e. Fundamentals of Analog Electronics B

4 学分 64 学时

本课程是电气、电子信息类和部分非电类专业本科生在电子技术方面入门性质的技术基础课。课程主要内容包括半导体器件，放大电路及其应用，电子系统的组成，信号的产生和转换电路，信号的运算和处理电路，功率放大电路，直流电源等。在深入分析半导体器件的结构、工作原理及外部特性的基础上，系统讲述基本放大电路、多级放大电路、集成运算放大电路、负反馈放大电路、功率放大电路、直流电源的组成、工作原理和分析方法。本课程通过对常用电子器件、模拟电路及其系统的分析和设计的学习，使学生获得模拟电子技术方面的基本知识、基本理论和基本技能，为深入学习电子技术及其在专业领域中的应用打下基础。

*** 模拟电子技术基础

i.e. Fundamentals of Analog Electronics

4 学分 64 学时

本课程是电子技术基础的一个重要分支，是电气、电子信息类和部分非电类专业本科生在电子技术方面入门性质的技术基础课。课程主要内容包括半导体基础知识、放大电路基础、多级放大电路、集成运算放大电路、放大电路的频率响应、放大电路的反馈、信号的运算和处理、波形的产生和信号的转换、功率放大电路、直流稳压电源和模拟电子电路的读图等。本课程通过对常用电子器件、模拟电路及其系统的分析和设计学习，使学生获得模拟电子技术方面的基本知识、基本理论和基本技能，为深入学习电子技术及其在专业领域中的应用打下基础。

选修本课程的同时还应选修《电子电路实验》系列课。

*** 自动控制理论

i.e. Theory of Automatic Control

5 学分 80 学时

反馈机制普遍存在于自然和人类社会当中。反馈控制已成为进行复杂工程系统设计中常用的一条基本原理。课程以系统阐明反馈机制的控制理论为核心，主要内容包括经典控制理论和现代控制理论两个部分。

经典控制理论部分，系统地介绍基于输入输出描述的系统分析和反馈综合方法，主要内容包括动态系统的传递函数模型，控制系统的设计指标（稳定性、暂态指标、稳态误差），伯德图和奈奎斯特图及其特性，根轨迹及其特性，串联校正的基本原理及设计方法，非线性系统分析方法以及采样系统分析方法。

现代控制理论部分，系统介绍基于状态空间描述的控制系统的分析和综合方法。主要内容包括控制系统的状态空间描述，线性变换，线性系统状态方程的解，状态的能控性和能观性，系统的标准结构分解，状态反馈和极点配置，基于状态重构的状态反馈控制与分离设计原理，抗干扰控制，调节器问题和李雅普诺夫稳定性等。

*** 自动控制理论（1）

i.e. Automatic Control Theory（1）

4 学分 64 学时

本课程系统地介绍基于输入输出描述的系统分析和综合方法，课程主要内容包括简单物理系统的微分方程和传递函数列写及计算，代数稳定判据及其应用，框图和信号流图的变换与化简，闭环传递函数的推导和计算，二阶系统的运动特征和分析，稳态误差的分析和计算，伯德图和奈奎斯特图的绘制，奈奎斯特稳定性判据及其应用，由开环频率特性分析系统的主要动态和静态特性，根轨迹的基本特性及典型根轨迹的绘制，串联校正的基本原理及设计方法，非线性系统的相平面分析方法，非线性系统的描述函数分析方法，采样系统的稳定性分析等。

*** 信号与系统分析

i.e. Signals and System Analysis

4 学分 64 学时

本课程讲授确定性信号经线性时不变系统传输和处理的基本概念和分析方法，内容主要包括连续时间信号与系统，离散时间信号与系统的时域分析和变换域分析，同时融合了“数字信号处理”课程的部分内容，如离散 Fourier 变换、快速 Fourier 变换、数字滤波器等。

*** 人工智能导论

i.e. Introduction to Artificial Intelligence

2 学分 32 学时

本课程主要讲授人工智能的基本原理和基本方法，通过最新的一些研究成果的介绍，以及一些应用问题的探讨，激发学生的兴趣和培养学生的创新精神和创新能力。课程的主要内容分三部分：

（1）搜索，包括状态空间搜索、与或图搜索、博弈树搜索和计算复杂性理论等；

（2）推理，包括谓词逻辑、归结原理、基于规则的推理等；

（3）机器学习，包括概念学习，决策树，深度学习等。搜索和推理是人工智能的基础部分，机器学习是目前人工智能领域发展最为迅速的一个领域，是人工智能研究的一个前沿方向。此外，课程还介绍与人工智能关系密切的一些研究方向和研究动态，如计算机视觉等。

*** 系统工程导论

Introduction to Systems Engineering

2 学分 32 学时

本课程包含以下主要内容：

#+BEGIN_EXAMPLE
（1）系统工程理论和方法概述；
（2）系统定性建模方法，主要讲授解释性结构建模方法；
（3）系统定量建模方法：主要讲授黑箱建模方法、介绍多项式模型和神经网络模型的基本原理；
（4）系统分析方法：主要讲授一元与多元回归分析方法、病态线性回归分析、主成分分析、因子分析和聚类分析等系列方法，并扩展性介绍 SOM、MARS、STARMA、RPCA、深度学习等内容；
（5）系统决策分析方法，主要讲授风险决策分析方法、多目标决策方法、层次分析法和群决策方法；
（6）现代优化方法概述：结合实例介绍几种常用的现代优化方法，包括遗传算法、模拟退化、粒子群和蚂蚁算法等。
#+END_EXAMPLE

*** 系统辨识基础

i.e. Fundamentals of System Identification

3 学分 48 学时

数学模型在现代科学与工程技术研究中起着不可或缺的重要作用。对于很多复杂的实际系统，由于很难建立其准确的机理模型，因此只能根据其观测数据来建立数学模型。系统辨识就是研究如何利用含有干扰与噪声的观测数据来建立系统的数学模型的一种理论和方法。本课程在有明显的应用背景和清晰的物理概念的前提下，结合相关分析法和最小二乘法两种经典的辨识方法，重点讲授系统辨识的基本概念、基础理论和基本方法，包括系统和数学模型的概念、辨识建模的问题描述、辨识的三要素与基本原理、辨识优化问题的求解、批处理与递推辨识、辨识算法的统计特性分析及可辨识性条件、阶次与结构辨识、辨识输入信号的设计以及辨识建模的完整步骤等。针对本课程的需要，还将简单介绍随机过程的基本知识，包括随机过程的基本概念和统计特征，白噪声及其产生方法，M 序列及其性质。课程还设置了仿真和物理辨识建模实验。

*** 计算机控制系统

i.e. Computer Control Systems

3 学分 48 学时

该课程是连续系统和离散系统，是连续控制、数字控制与工业过程相结合，从工程实际应用出发讲授：计算机控制系统组成、微型机接口技术和过程通道、开关量控制系统、计算机控制器和微型机控制系统、DOS系统、DDC、DCS、PLC 和 FCS 系统及计算机控制领域的发展等内容。

*** 生产系统计划与控制

i.e. Planning and Control of Production System

2 学分 32 学时

本课程主要介绍企业生产管理方面的一些基本概念、方法和系统，以扩大知识面，增加理论与实际结合的应用背景。课程内容包括企业生产系统的基本活动，库存系统计划与控制，主生产计划的制定，物料需求计划的制定，工程项目计划与控制，作业排序与操作计划，生产系统计划与控制的其他方法，如准时制、优化生产技术、计算机集成制造等。

*** 数字图象处理

i.e. Digital Image Proessing

3 学分 48 学时

本课程主要讲授数字图像处理的基本概念、主要理论、典型方法以及应用举例。有别于一般的图像处理课，本课程避免使用过多的数学和公式，而用大量的图来说明原理、解释算法和显示效果。课程针对图像处理涉及数据量大、占用资源多的特点，尽量介绍快速算法和一些非常实用但一般教科书中没有的图像处理方法，如特殊的数据结构和算法。课程也会介绍一些图像处理方法的最新进展，偶尔也讲述一些和图像处理有关的历史、典故、趣闻、巧妙的算法、特殊的图像等，以便引起听课者的兴趣。

本课程的教学特色：重视基本概念，并尽量用图来解释；注意课堂讲授和课外作业的关系，通过作业，不但复习课堂讲授的知识，还注重加强学生知识结构中的薄弱环节，比如信号处理理论的应用、计算机语言和程序设计，文献查阅，提高学生利用图像处理知识解决实际问题的能力。

*** 机器人智能控制

i.e. Intelligent Control of Robots

3 学分 48 学时

课程内容包括空间描述与空间变换、机器人运动学和逆运动学、运动雅克比、机器人动力学、轨迹规划、机器人运动控制、职能机器人系统的基本结构和组成等。并配合讲课内容设置了示教再现实验、6DOF 机器人运动学/逆运动学实验、6DOF 动力学仿真、和开放性综合实验等，实验环节与讲课内容紧密配合，旨在培养学生运用所学知识解决实际问题的能力和创新能力。

*** 多媒体技术及应用

i.e. Multimedia Technology and Its Applications

2 学分 32 学时

本课程包含以下主要内容：（1）多媒体技术基础，主要讲授媒体、多媒体的定义及媒体数据的特点；（2）音频信息处理技术，主要讲授声音三要素，音频卡的工作原理，音频的编码，音频信息处理方法和语音识别技术，音频处理软件，最新音频信息处理技术知识扩展；（3）视觉信息处理技术，主要讲授彩色三要素与彩色空间，图形与图像，图像格式及其转换方法，图像处理技术，视频信息处理技术，最新视频信息处理技术知识扩展；（4）压缩编码技术：主要讲授数据冗余的原理，以及量化、无损编码、预测编码、变换编码等编码技术；（5）多媒体输入输出技术；（6）多媒体数据库技术；（7）多媒体网络通信技术；（8）实验：多媒体音频编辑、视频编辑、Flash 动画和网页制作等。

*** 数值分析与算法

i.e. Numberical Analysis and Algorithms

3 学分 48 学时

本课程主要讲授常见数学问题的计算机求解方法，内容包括多项式插值、一致逼近、平方逼近、数值积分、数值微分、常微分方程的数值解、线性方程组数值解以及矩阵特征值和特征向量的计算等。课程的重点内容：（1）误差分析，包括收敛性与稳定性分析；（2）数值计算的基本原理和方法等。课程讲授注重基本原理和概念，结合课程将布置 3 个大作业，以锻炼学生理论联系实践和解决实际问题的能力，课程还将安排1~2 个相关研究内容的讲座，以加深选课学生对数值计算原理的理解，了解数值计算在科学研究中的应用。

*** 控制专题

i.e. Topic on Control

2 学分 32 学时

本课程包含两个控制专题， 各 16 学时：第 1 部分非线性系统分析与控制，主要介绍与非线性系统分析与控制相关的知识点，包括轨道、暂态与定态，稳定性，振荡与极限环，混沌与奇怪吸引子，分形，结构稳定性与分岔，耗散结构与协同学等；第 2 部分为微纳系统控制，主要介绍纳米操作系统控制，量子力学系统控制等控制学科发展的新的前沿方向。

*** 非线性控制理论

i.e. Nonlinear Control Theory

2 学分 32 学时

本课程主要讲授非线性控制中以反馈线性化为主线的设计理论与方法，同时介绍非反馈线性化方法方面的一些进展。在反馈线性化方面，以多变量非线性控制的逆系统方法为主，包括非线性系统的基本特性，模型的机理推导、表示与变换，逆系统方法原理，可逆性理论，多变量系统解耦，镇定设计方法，非线性状态观测等，同时包括基于微分几何方法的状态方程线性化的内容。在非反馈线性化方面，简要介绍 Liapunov方法、变结构方法、逆推方法等。最后，通过一组应用研究案例分析，以加强用所学理论分析解决实际控制问题的能力。

*** 智能优化算法及其应用

i.e. Intelligent Optimization Algorithms and Its Applications

2 学分 32 学时

本课程围绕基于计算智能的优化算法设计与应用，简明而系统地介绍模拟退火、遗传算法、禁忌搜索、微粒群优化、差分进化、分布估计算法、神经优化、混合优化等热点智能优化算法。内容涉及优化机制、理论、流程、设计、应用、推广等多个层面，结合实例分析算法的特点，进而指导算法的设计与应用，突出智能优化算法的实用技术性和结构统一性。同时，随堂介绍国内外最近研究进展，引导学生自学学术界最新提出的智能优化方法，并开展相应的设计与应用研究。

*** CIM 系统导论

i.e. Introduction to Contemporary Integrated Manufaturing System

2 学分 32 学时

本课程首先介绍企业管理的基本原理和方法，介绍信息化对企业创新管理和产品开发等的重要意义、方法和案例，从企业发展战略和信息化应用实施的整体解决方案出发，阐述企业信息化战略管理基本原理和方法。课程的主要内容包括企业管理的理论和方法，信息与信息技术概念、功能和发展历程，云计算、物联网、大数据等在企业信息化中的应用原理及案例，CIM 系统的概念、系统的构成、系统集成的思想和基本方法，信息技术支持下的企业管理模式创新方法与实践，组织与流程创新方法与实践，产品与服务创新方法与实践，企业资源计划管理系统方法与实践，制造执行系统与产品设计系统介绍，企业信息化战略管理框架和信息化整体解决方案。

*** 综合论文训练

i.e. Diploma Projects（Thesis）

15 学分 480 学时

严格执行“清华大学本科生综合论文训练教学管理办法”中的各项条款，课题设计控制理论与控制工程、模式识别与智能系统、检测技术与自动化装置、系统工程、导航制导与控制、企业信息化系统与工程、生物信息学等学科，均为实际课题，保证 1 人 1 题。

*** 自动控制理论（2）

i.e. Automatic Control Theory（2）

3 学分 48 学时

本课程是经典控制理论的后续课程，讲授现代控制理论的基本内容，系统介绍基于状态空间描述的控制系统的分析和综合方法。与系统分析有关的内容包括控制系统的状态空间描述，线性变换和特征值规范型，线性系统状态方程的解，预解矩阵和矩阵指数，状态的能控性和能观性，能控性及能观性的判据和规范型，系统的标准结构分解，由状态方程导出传递函数阵，传递函数阵和能控能观性的关系，传递函数阵的实现和最小实现，状态反馈和输出反馈，反馈对能控性和能观性的影响等。与系统综合有关的内容包括单变量和多变量系统的极点配置，状态的全维和降维观测器，输入输出的动态解耦控制和静态解耦控制，状态对外扰的完全不变性问题，输出对外扰的静态不变性问题，用变分法/极大值原理求解最优控制问题，线性系统二次型指标最优控制问题，李雅普诺夫稳定性概念，李雅普诺夫间接法和直接法等。

*** 检测技术系列实验（1）

i.e. Series of Experiments for Measurement Technology（1）

1 学分 16 学时

本课程是专门的实验课程，共提供 6 个实验组合模块，分为基础性实验、综合性实验和研究性实验三大类。其中包括：（1）开关量传感器特性实验（4 学时，基础性实验）；（2）模拟量传感器特性实验（4 学时，基础性实验）； （3）AS-i 总线系统研究实验1（4 学时，研究性实验）； （4）AS-i 总线系统研究实验2（4 学时，研究性实验）； （5）基于嵌入式系统的无线传感器实验（课外 10 学时，选做实验）。

*** 模式识别基础

i.e. Fundamental Pattern Recognition

2 学分 32 学时

本课程主要介绍模式识别的基本概念和基本体系，统计模式识别的基本理论和典型方法，模式识别的应用举例，以及模式识别与机器学习的学科发展现状和一些前沿课题。

*** 检测技术系列实验（2）

i.e. Series Experiments for Measurement Technology（2）

1 学分 16 学时

本课程是专门的实验课程，共提供 6 个实验组合模块，分为基础性实验、综合性实验和研究性实验三大类。其中包括：（1）开关量传感器特性实验（4 学时，基础性实验）；（2）模拟量传感器特性实验（4 学时，基础性实验）； （3）AS-i 总线系统研究实验1（4 学时，研究性实验）； （4）AS-i 总线系统研究实验2（4 学时，研究性实验）；（5）基于嵌入式系统的无线传感器实验（课外 10 学时，选做实验）。

*** 专业实践

i.e. Practice of Speciality

5 学分 200 学时

实践诸如计算机控制软件硬件系统、单片机应用、信息处理、生物信息处理、电子线路设计、计算机仿真、计算机管理信息与决策支持系统、计算机网络以及自动化仪表与检测系统等的运行以及设计、安装、检验、维护等。

*** 过程控制

i.e. Process Control

4 学分 64 学时

本课程讲授流程工业控制系统的相关知识与技术，课程包括两部分内容：（1）化学工程基础——过程单元操作原理，典型设备的结构原理及操作性能，其中重点讲述流体的流动与输送、传热过程与设备，以及精馏过程等；（2）过程控制——过程对象特性及描述方法，简单控制系统的构成、分析与整定，调节阀的基本结构与特性分析，复杂控制系统，以及先进控制系统等，其中复杂控制系统包括串级控制系统、前馈控制系统、解耦控制系统，先进控制系统包括预测控制与推理控制系统。本课程还以精馏过程为例，综合讲述一个实际生产过程的工艺过程分析、机理建模，及其常规控制系统和先进控制系统的应用设计。课程在讲授相关知识与技术的同时，安排了相应的物理与计算机仿真实验，包括验证性实验与创新性实验，以培养学生解决问题的能力。

*** 检测原理

i.e. Measurement Principle

2 学分 32 学时

本课程主要讲授传感器与检测技术的基础知识，包括检测和传感器的基本原理、工程信号变换、检测系统性能分析、测量误差分析和测量不确定度评价，各种主要工业参数的测量原理和方法，如位移、距离、速度、加速度等机械量检测，温度、压力、物位和流量等过程量检测，并结合在科研和工业实例，分析检测方法的应用条件与抗干扰措施。

*** 电力拖动与运动控制

i.e. Electrical Driver and Motion Control System

4 学分 64 学时

本课程内容可分为两条主线：一是作为机电能量变换装置的直/交流电动机原理和外特性，一是基于电机的运动控制系统原理及设计。

主要内容包括（1）机电能量转换基本原理； （2）直流、交流电机基本原理、外特性及建模； （3）电机拖动基本原理以及典型负载特性；（4）典型直流、交流电机控制系统的原理、分析和设计方法。课程力图通过理论分析、多媒体动画展示、综合例题和实验、典型系统分析以及应用实例分析等，使学生掌握系统的物理本质、与基础知识的关系、了解典型工程实际应用。

*** 数据库系统原理

i.e. The Theory of Database System

2 学分 32 学时

数据库技术在计算机学科体系中占有重要的地位，数据库管理系统是除操作系统之外的另一个重要的系统软件。本课程面向计算机应用类专业，目的是使学生在掌握数据库系统原理的基础上，具备数据库应用系统的设计、开发能力。主要内容包括数据库的基本理论、数据库应用设计技术、常用的数据库系统（如 Oracle和 SQL Server）使用等。本课程注重基本知识的教学，包括关系数据库的基本概念、规范化理论、信息模型设计方法等，要求上机操作、做实验，并强调理论与实践相结合，完成教学管理系统的信息模型设计报告。

*** 过程控制专题实验（1）

i.e. Process Control Experiments of Special Topics（1）

1 学分 16 学时

本课程以过程控制经典实验为基本内容，主要包括对象动态特性测试、调节器控制规律测试、单回路控制系统整定、调节器参数对控制过程影响、串级控制系统整定、前馈和前馈-反馈控制系统整定等。实验以小型多参数过程控制实验台（物理模型）为被控对象，实验过程中既有实际操作环节，又有演示讲解、课堂讨论等环节。

*** 过程控制专题实验（2）

i.e. Process Control Experiments of Special Topics（2）

1 学分 16 学时

本课程依据自动化系过程控制实验室的现有条件，以培养学生的自学能力、动手能力和严谨科学作风、团结协作意识、求实创新精神，调动学生的积极性和设计、研究潜能，鼓励学生综合运用所学知识，发掘自主思维潜力，提高学生的分析问题、解决问题能力为目的。面向全系本科生、兼顾全校对自动化技术与科学有浓厚兴趣的学生。以综合型、设计型、研究型实验为主，基本型经典实验和自主型个性化实验为辅。实验的设置既保持了专业特点，又强化了与相关学科的融汇结合，突出了实验的先进性和实用性。学生可以根据自身条件和兴趣，选做实验项目中列出的某些内容，获得相应学分。

*** 运动控制专题实验（1）

i.e. Motion Control Experiments on Special topics（1）

1 学分 16 学时

本课程以实验研究为主，通过构建由控制器、驱动器和对象模型组成的控制系统，学习并掌握常见运动控制系统的组成和调试方法，提高动手能力和解决问题的能力。本课程分直流调速控制系统实验和基于设备网的交流调速系统实验和仿真实验（选做）三部分内容：

（1）直流调速系统实验包括 PWM 变换器实验、直流电动机系统参数和环节特性测定实验、PWM 转速电流双闭环负反馈调速系统实验；

（2）基于设备网的交流调速系统实验，包括交流调速系统的搭建、基于设备网的控制参数传输、交流变频器的使用、利用现场总线的交流驱动控制等；

（3）基于 Matlab 和 Simulink 仿真软件的直流电机双闭环系统调节器整定和电流环与转矩环发生故障对调速系统特性的影响。

*** 运动控制专题实验（2）

i.e. Motion Control Experiments on Special topics（2）

1 学分 16 学时

本课程为专题实验课，目的是通过具体实验项目，学习典型运动控制系统的设计、测试和调试方法，以及基于工业交流变频器的异步电机控制系统的设计和调试方法。本课程分为两个个专题：（1）双闭环直流调速系统设计、实验、以及性能仿真；（2）基于交流变频器的异步电动机调速系统测试和实验。

*** 控制理论专题实验（1）

i.e. Control Theory Experiments on Special topics（1）

1 学分 16 学时

本课程以实验研究为主，通过实验研究掌握控制理论与系统的一般设计方法和一些先进的控制方法，使控制理论与实际系统相结合，为进一步进行科学研究奠定理论与实践基础。目前开设四个实验项目，任选其一。

（1）倒立摆建模与控制实验：基于物理原理建模，推导传递函数和状态空间方程，进行系统可控性、可观性及稳定性研究；用根轨迹、频域响应、极点配置等控制方法设计控制器，完成倒立摆系统的仿真与实时控制。

（2）旋转运动系统实验：以旋转运动伺服装置为基础，组合球杆、旋转机架等模块为实验装置，基于物理原理完成系统建模，用速度反馈、极点配置等方法设计控制器，完成旋转运动系统仿真与实时控制。

（3）控制理论模拟实验与 Matlab 仿真研究：使用模拟电路搭建多种控制系统，对控制理论中的一些基本理论进行实验研究，如控制系统稳定性分析、非线性系统性能分析、状态反馈与状态观测器等。

（4）基于 LabVIEW 的多种被控对象实验：软件平台为 NI（美国国家仪器）公司的 LabVIEW，硬件平台为NI ELVIS II（NI 设计与原型平台）、直流电机控制模块、倒立摆模块、飞行重力模块，用多种控制方法完成电机速度与位置控制、倒立摆稳定控制、重力模块稳定控制。

*** 控制理论专题实验（2）

i.e. Control Theory Experiments on Special theory（2）

1 学分 16 学时

本课程以实验研究为主，通过实验研究掌握控制理论与系统的一般设计方法和一些先进的控制方法，使控制理论与实际系统相结合，为进一步进行科学研究奠定理论与实践基础。目前开设四个实验项目，任选其一。

（1）倒立摆建模与控制实验：基于物理原理建模，推导传递函数和状态空间方程，进行系统可控性、可观性及稳定性研究；用根轨迹、频域响应、极点配置等控制方法设计控制器，完成倒立摆系统的仿真与实时控制。

（2）旋转运动系统实验：以旋转运动伺服装置为基础，组合球杆、旋转机架等模块为实验装置，基于物理原理完成系统建模，用速度反馈、极点配置等方法设计控制器，完成旋转运动系统仿真与实时控制。

（3）控制理论模拟实验与 Matlab 仿真研究：使用模拟电路搭建多种控制系统，对控制理论中的一些基本理论进行实验研究，如控制系统稳定性分析、非线性系统性能分析、状态反馈与状态观测器等。

（4）基于 LabVIEW 的多种被控对象实验：软件平台为 NI（美国国家仪器）公司的 LabVIEW，硬件平台为NI ELVIS II（NI 设计与原型平台）、直流电机控制模块、倒立摆模块、飞行重力模块，用多种控制方法完成电机速度与位置控制、倒立摆稳定控制、重力模块稳定控制。

*** 企业与信息系统建模分析

i.e. Enterprise and Information System Modeling and analysis

2 学分 32 学时

Enterprise and Information System Modeling and analysisEnterprise engineering and information system modeling and analysis techniques are introduced in this course.These techniques are basic methods of system design/realization， industrial engineering， management and ITconsulting for graduated students from industrial engineering， management engineering， and informationengineering department.

*** 生物信息学概论

i.e. A Survey of Bioinformatics

2 学分 32 学时

生物信息学是信息科技、生命科学、医学和药学等多学科领域相交叉的新兴学科，是新世纪科学的前沿和热点，也是当今和今后相当长时期内人类科学探索最活跃的研究领域之一。本课程主要内容介绍生物信息学基本知识，描述生物信息学中基因组学、蛋白质组学、系统生物学等新兴领域的概况与进展，讲授基因组序列的获取和分析、基因组表达及芯片数据分析、基因调控网络、蛋白质相互作用网络，以及生物网络在医学、药学、中医药中的应用等研究内容和代表案例，着重介绍生物信息学在医学生命科学领域中的一些应用与发展，包括生物医学中的生物信息分析、系统生物学与中医药现代化等。本课程旨在拓宽同学们的研究视野，了解生物信息学的基本知识、基本技能以及有关前沿研究进展，培养同学们对生物信息学这一新兴交叉学科的研究兴趣。

*** 企业信息化系统与工程导论

i.e. Introduction to Enterprise Information System and Engineering

2 学分 32 学时

本课程简明扼要地介绍企业信息化系统的基本概念、内涵和关键技术，同时分别围绕企业经营管理过程和产品形成过程两条主线介绍经营管理信息化和产品研发信息化的主要方法、技术与系统，并结合具体应用案例介绍企业信息化系统解决实际工程问题的方法与效果。

主要内容为：企业信息化系统概论，包括其基本概念、发展沿革、知识体构成、研究进展；企业经营管理信息化系统与工程，包括 MRP、MRPII、ERP、ERPII 的概念与发展关系，制造模式与管理模式，经营管理信息化工程实施方法及工程案例；产品设计开发信息化系统与工程，包括产品研发信息化的沿革、CAx 和 DFx技术与系统、CAx 集成与产品开发管理，产品研发信息化工程实施方法及工程案例；基于虚拟制造（VM）技术的产品研发逆向创新和正向创新；制造执行系统（MES）及其对管理信息化与设备自动化的集成；生产计划与控制方法及其在实际工程中的应用；网络化制造及其相关技术以及我国的工程应用探索。此外，还探讨了作为企业信息化领军人才的首席信息官（CIO）的素质修炼，包括 CIO 的基本素质、知识结构、职业资格、评价体系等，并介绍了 CIO 的成长案例。

*** 网络安全基础

i.e. Network Security Essentials

2 学分 32 学时

网络安全的基本问题

#+BEGIN_EXAMPLE
● 网络安全的应用背景
● 网络安全的研究内容
● 网络安全的主要技术
● 网络安全的热点问题
#+END_EXAMPLE

防火墙的基本知识

#+BEGIN_EXAMPLE
● 防火墙的起源和作用
● 防火墙的类型与发展
● 防火墙的程序与实例
● 防火墙的开发与未来
#+END_EXAMPLE

准入控制的基本知识

#+BEGIN_EXAMPLE
● 准入控制的范围和作用
● 准入控制的技术与发展
● 准入控制的研发与未来
#+END_EXAMPLE

入侵防范基本知识

#+BEGIN_EXAMPLE
● 入侵防范的起源和作用
● 入侵防范的类型与发展
● 入侵防范的程序与研发
#+END_EXAMPLE

防范病毒、垃圾等的基本知识

#+BEGIN_EXAMPLE
● 防病毒技术与应用
● 防蠕虫技术与应用
● 防垃圾技术与应用
● 防钓鱼、防间谍等技术与应用
#+END_EXAMPLE

信息泄漏防范的基本知识

#+BEGIN_EXAMPLE
● 信息泄漏防范的目的和意义
● 信息泄漏防范的技术与应用
● 信息泄漏防范的研发与未来
#+END_EXAMPLE

虚拟私网的基本知识

#+BEGIN_EXAMPLE
● 虚拟私网的发展和应用
● 虚拟私网的类型与技术
● 虚拟私网的实例与使用
#+END_EXAMPLE

数据中心网络（DCN）安全

#+BEGIN_EXAMPLE
● 云计算与数据中心网络 DCN
● SDN、NFV 与 DCN 架构与安全
● DCN 安全核心技术及其应用
#+END_EXAMPLE
