#+SETUPFILE: ../theme-rose.setup
#+DATE: <2020-01-17 Fri 22:10>
#+TITLE: Diary

* 日记

#+BEGIN_QUOTE
时间像头野驴，跑的飞快。生活需要计划、思考和沉淀。时空无限，人生终有尽时，想在这无限的时空中，舞动璀璨人生，就不能若无根的浮萍，随着光阴的长河漫无目的地漂流。
#+END_QUOTE

** [2020-06-05 Fri]

社会是很复杂的。社会上有形形色色的人有你看的惯的有你看不惯的。社会上也有许多形形色色的事，有你看的惯的，也有你看不惯的。其实你能控制的，只是你自己，你能控制你的思想，你能控制你的感受，你对自己的控制力越强，你就会变得越加强大。

保持自己的强大是很有必要的，它会在一定的条件下保证你受到公正公平的对待。你可以不去欺负别人，但是你也必须有足够的能力来确保自己安全无忧。有能力而不想去做的事，那是你的自由。想做却没有能力去做的事，那是一种无奈。多一点自由，少一点无奈，这就是惬意的人生。

人的一生其实是很短暂的，人活一辈子总要给以后留下点什么。滚滚历史的洪流上下几千年甚至几万年，究竟有多少人在历史的大潮中留下了他的身影？命运是很奇特的，光怪陆离，充满了无限的可能性。命运的小舟啊，你将要驶向何方？时代的巨轮啊，你将要形象何处？

继续力量成就自己的人生。

** [2020-06-04 Thu]

昨天的日记忘记写了……

看这就是习惯，习惯的事情你基本上会很少忘记，还没有形成习惯的就很容易忘记了。所以说，每一件事情都有两面性，有好的一面，也有坏的一面，幸运地是你可以利用这件事物好的一面，记住要辩证的看问题。那昨天忘了写日记，有没有它好的一面呢？好，或者不好，这是一个问题。

以后还是不要太放纵的好。就像这一次工作上的事情，中间“浪费”了好多时间。其实有很多事情是事先难于预料的，所以必须留够充足的时间去应对它们。

有付出才有收获，没有人能够随随便便成功，你必须积蓄足够的力量才可以。正所谓不经历风雨，怎能见彩虹？千里之行，始于足下。合抱之木，始于毫末。加油！

** [2020-06-02 Tue]

最近不知道怎么了，对工作的事总是不是很上心。项目进度总是一拖再拖，我这是怎么了？我难道不喜欢前端开发了吗？确实有一点吧！其实前端的技术站明明也有很多的，但是我总是感觉前端的东西好多都是浮于表面，大概是因为前端做的本来就是界面。另外还有一个重要的原因，我认为一个人如果只是沉浸在前端开发那么就失去了编程的真正意义，它就真正只成了一件谋生的工作了。如果现在你对前端开发真的没有兴趣了，那你就更应该抓紧时间去学学习后端知识，尽快的完善自己的技术栈，让自己成为一名合格的后端开发人员。我并不讨厌前端，但是如果只研究前端的话，并不能让你成为一个更好的前端开发人员。

有一种说法是程序员的鄙视链。但其实呢，你学习什么没有人去限制你，无论你现在从事的是哪一个方向，你都拥有自由的选择去在业余的时间学习你想要学习的知识。学习是一种思维方式，是一种能力。在这个过程中，你必须思考如何能更快、更好、更牢固地掌握你正在学习的东西。在学习一种东西的时候，知道这件事物现在的状况以及它的发展历程是非常非常重要的。尤其是发展的历程，因为每一件事物的出现都是有其原因的，而这些背后的原因才是真正推动这件事物不断发展的原动力。如果你不了解你现在所做的这些是为了什么，那么你就很难有动力去坚持下去。

唉，不管怎么说？我必须检讨一下，现在的工作态度了，毕竟现在领着公司的薪水，就应该把项目和工作做好。在做好完善自身工作的闲暇时间去最大程度的做自己喜欢的事，一方面可以对得起自己的良心，一方面可以对得起自己的兴趣。当然，最好的结果就是通过自己的努力，可以达到一定的程度，进而去创造自己喜欢的条件，去做自己最喜欢做的事情。我们活着就要为这个社会创造一定的价值，只有通过这种方式，我们才能实现人生的价值。对，是这样的，只有通过自身努力，你才能改变现状，你才能去主动地创造那些有利于你的条件，你才能享受你自己创造的条件进而去做你自己最喜欢做的事情，这样的话就是一个良性的循环。去做创造性的工作，远远要比做重复性的工作要来的让人兴奋和惬意。我们把繁杂的事物进行标准化流程化程序化不就是为了这样的目的吗？不就是为了把人们从繁杂重复造的劳动中解脱出来吗？那些劳动是有价值的，但是完全可以去做价值更高的事情，来让那些也具有价值的劳动变得不那么枯燥。对于工作这件事情需给自己定下几点原则，不给自己立个规矩也是不行的，这样每一天都沉浸在做自己的市场，而把公司的事情放在一边的话，是不太好的。工作的时间就用来做公司的事情，如果是工作的时间有所闲暇的话，那你要和做项目相关的事情，要去想着优化项目里面的某些点。因为在工作的时候，如果其余的一些时间你去做自己喜欢做的一些方面的话，那你很容易调整不过来自己的状态，从而把工作的时间过多地分给了自己喜欢的那些事。只有充分、优质地完成了本职的工作，你才会有心情去做自己喜欢的事，不然，你的心情并不如你自己想象的那么欣喜。

以此为证，工作的时间只做与工作相关的事情。下了班之后，你愿意做什么就做什么。Okay！

** [2020-06-01 Mon]

今天是六一童节，我决定从今年的下半年开始，每天都要写日记。尽管我可能写的是一些废话，但是还是要保持这个习惯吧。写日记的形式主要是通过语音输入，毕竟是日记嘛，对格式什么的也没有太大的要求。也许在第二天的时候我会进行一些修改，当然，也许不会修改。

时间过得真是太快了，不知不觉已经又半年过去了，从去年开始到今年真的是发生了很多事情，从中美贸易战到新型冠状肺炎，世界形势也变化的是很快，我感觉自己的思想也发生了很大的改变。

人们是应该做自己喜欢的事情的，兴趣是最好的老师，这一点是真的。在你做自己感兴趣的事情的时候，你会以这个为中心往外不断的扩展。万物是相通的，举一反三源于对于本质的思考。再次强调一下，人的精力和时间，真的是有限的，我们应该把时间和精力用在最应该用的地方。保持经历的最好办法还是要遵循极简主义生活方式。

你的目标也许很宏大，但是总还是要分阶段来做的。你不可能在一天之内就把所有的事情做完，正如矛盾分为主要矛盾和次要矛盾，事情也是分轻重缓急的，你应该做最重要，而且紧急的事情。至于那些不重要，且不紧急的应该放在稍后的位置。有时候我们应该认真思考一下自己先前的一些观念，到底是不是正确的？也许好多时候我们自以为正确的事情往往错的离谱。

抓紧时间提高自己摆脱债务陷阱是一件非常非常非常重要的事情。不要给自己设限，要让自己的精神和身体，形成一种良性的循环。你知道的，有些事当你懂了，你自然就懂了。你知道的，自欺欺人是很简单的，我们在很多时候都可以给自己找一个理由。

今天是儿童节，是一个不错的开始。从今天开始，加强滋养自己的精神锻炼自己的身体，保持精神的富足，保证身体的强健，进而拥有更多的经济和时间去做你想要做的事情。在2020年5月的最后一天，申请了一个自己也比较满意的域名，这个域名我会一直使用下去。它是浪漫的，有意义的。给自己一个新的开始，给生活一个新的开始。对，有开始，就有希望。

加油，自己。加油，生活。

乱糟糟的语言也没有组织就说这些吧。

** [2020-05-01 Fri]

白天写日记，这不算是头一遭，不过也是不多……

五一长假来了，有五天的集中时间可以做一此事情，读完放在角落吃灰的书，学习新的语言，写几篇博客，录制几段视频，学习一下视频剪辑的软件…… 会发现要做的事很多，而你的时间和精力是有限的，所以当务之急还是要把琐碎的知识管理规范起来。如何去做呢？

以 GTD 为主架构，各个阶段中采用最佳管理方法，GTD 最大的优势就是它应收尽收的能力和思想，它如同一个平台，给了其它方法合适的嵌入点。

** [2020-03-16 Mon]

生活中，许多习以为常的概念，自以为明白，尝试去详细描述的时候，头脑中却往往是一片空白，生活因而显得繁杂无序，没了条理。思之不明，故述之不详，然大道至理常存于这看似的平淡无奇之中。

** [2020-02-28 Fri]

为什么会拖延呢？已经安好了计划，也知道事情是必须要处理的，但是为什么迟迟没有动手呢？不感兴趣，且短时间内无法完成，也有 _担心是否可以顺利完成_ 而心中存在疑虑的因素！焦虑便是这样产生的！

#+BEGIN_QUOTE
焦虑是由于缺乏控制力，组织管理、准备和行动不足所造成的。
#+END_QUOTE

控制力，本质上来说是一种习惯，而习惯都是可以培养的。而且培养一种好习惯，收效是很客观的，养成一种好习惯的同时，不仅仅意味着拥有了更好的生活方式，同时标志着减少了该方面原本存在的恶习。好习惯的培养带来的回报是指数级增长的，一个好习惯会全方位地带动其他方面的提升。

执行力！再光辉的思想无法应用于实践过程中，也不过是屠龙之术。说破了天，还是要做！做！做！

孔夫子说，“学而不思则罔，思而不学则殆”。世间诸般事，不外如是啊。 GTD ，目前算是只学了一些皮毛，初窥门径而已，当务之急，是先要用起来，认真仔细地思考一下其运行规则。执行！执行！执行！

** [2020-02-26 Wed]

#+BEGIN_QUOTE
我们曾如此渴望命运的波澜，到最后才发现：人生最曼妙的风景，竟是内心的淡定与从容。我们曾如此期盼外界的认可，到最后才知道：世界是自己的，与他人毫无关系。 -- 杨绛
#+END_QUOTE

人的一生，有多少个阶段？一个人，直面审视自己的内心，需要多大的勇气？

这十年，塔内塔外各半，酸甜苦辣皆含。时至今日，袖裳空空，脑海乏乏，唯余二三烦扰事于心。诸事不遂，皆有因果，竹篮打水，更如梦幻泡影。掖着藏着，文过饰非，羞于心，愧对己，不得潇洒，反而若鼹鼠无目，不见终日而惶惶。无私为私，彼心不古，乃势，所谓势不可挡，局中求破局而功者，知造势、顺势，假于人物也。

过往的十年，可以称为假寐岁月，成长的波澜淙淙，流淌着无知、愚昧，唯美、善真。也是随波逐流的十年，没有风帆的舵手，顺流而下，或触礁跌宕，或风暴骤降。命运的光怪陆离，幸运的矫揉造作，无妄、无名。少年登楼望月赋怨愁，月依旧，那份安然、刻意在心头。

生活啊，是乱成了一团麻，需要有意识地去管理，需要克制，需要自律，这是一件苦差事，得失总归在平衡，平衡却又不同。忘却自己，模糊了前路，便容易变成真的糊涂，浪费了青春和岁月。心灵的刚强与脆弱，得意的春风，老树和昏鸦。

十年不知措，施于何为？心智苦矣，筋骨劳矣，体肤饿矣，大任乎？也可能只是徒然四壁，夜雨屋漏而已。由内而外，反求诸己，方是正道，所谓自助者天助，君子当自强不息，不外如是。反思、咀嚼那些苦楚，不可名，不可道，唯有心知。

十年来，恶习不绝，知而不改，掘墓无数，终须大毅力补之。时间一分一秒，本无不同，那些有意义的刻钟，定格凝固，皆心使之异众。记忆是一个复杂的结构，记起、忘记，片段支离。读书和工作，书读的浅浅薄薄，事做的马马虎虎。幸哉处，几本佳作以筑，稍宽慰心胸，免于俗不可耐，浑身恶臭。

探索事物的本质和原理是一种乐趣，大道本一，殊途同归。稻盛和夫，《活着》精进，精进是核心，绝非是一味机械的重复。事物的对立面不是相距千里，往往只在一念之间。史蒂芬·柯维，《七个习惯》相辅相成，积极主动、以终为始、要事第一，从依赖到独立；双赢思维、知彼解己、综合综效，又从独立到依赖；不断更新，平衡自我。朗达·拜恩，揭露《秘密》，宇宙无限，频率共振，身心合一，量子吸引。大卫·艾伦，《无压力生活》，心如止水，循环集成。《易》以盖之，天地定位，山泽通气，雷风相薄，水火不相射。《道德经》注，无中生有，有生万物，道法自然，大象无形。极简生活，少即是多，求质清心。

何以成就？

难得糊涂？中国文化的妙处就在这里，同一个词语，多重含义，不同层级，不容意义，有时甚至是截然相反的。或许，司空见惯的事，耳熟能详的话，所理解的和它们真正要表达的南辕北辙。就拿“糊涂”一词作比，天然就裹挟着真糊涂和假糊涂两个意思，每种又同时包含褒贬二义。倒不是，引经据典的人闲来无事，故意掉书袋，实则事实如此，诸事不一而同。《老子》说，“道生一，一生二，二生三，三生万物。”以这个假定为基础，不难看出，万物同宗同源，皆生于道。何为道？《老子》曰，“道可道，非常道。”认为道是玄而又玄，不可名状的，任何具象化的道都不是道的本质，正所谓大象无形。道之为道，上善若水，利万物滋众生，在于浩瀚星数，处于毫微有间，无所不容，无处不存。

四书五经。四书，《大学》、《中庸》、《论语》、《孟子》。五经，《诗经》、《尚书》、《礼记》、《周易》、《春秋》。

《大学》开篇有云，“知止而后有定；定而后能静；静而后能安；安而后能虑；虑而后能得。物有本末；事有终始。知所先后，则近道矣。”故须格物致知，“致知在格物，物格而后知至；知至而后意诚；意诚而后正；心正而后身修”，身修继而齐家治国平天下。

愈读之，愈度之，愈叹服。

观当下国内的教育系统有感，四字可盖之，“急功近利”！止时不教定，定时不明静，静时不能安，安时不思虑，而又苦其不能得。置正途而不顾，百思其捷，欲速欲达，竭泽而渔。何以至于此？本末倒置使然。何以成就？当固本清源，因时而动。

用现代的思考来说，无论是极简主义思潮，还是 GTD 安排，最终的目的，都是理清事物的脉络，知止求定利静益虑而得。我们呢？端着金碗要饭。这些先辈圣贤千年前就想明白的道理，却被我们束之高阁，装点门面，而失之精华。应该从自身出发，由内而外，反求诸己。应该发现并思考事物之间的联系，应该循环往复，使之生生不息，不塞滞。深思熟虑，上通下达，水到渠成，何以不得？何以不就？！

** [2020-02-22 Sat]

哎呀，这恼人的拖延症！

#+BEGIN_QUOTE
拖延 → 焦虑
#+END_QUOTE

为什么会拖延呢？浮躁。拖延，可以让你不用面对，是一种潜在的懦弱。有许多，心知肚明应该要做的事情没有去做，而坏习惯带来的无用之事却占据了大部分的精力和时间，要么紧迫，要么事倍功半，总之是一种恶性循环的得不偿失。

如何解决拖延呢？由内而外，反求诸己。简，精神极简，物质极简。思，诚意正心，剔糟除粕。行，贵不自欺。

** [2020-02-17 Mon]

内化，持续。

#+BEGIN_QUOTE
不积跬步，无以至千里；不积小流，无以成江海。
#+END_QUOTE

一日之时有限，诸事巨细，多则非一日一时可全之。一事之道，穷根溯理，亦非须臾可得之。故恒，要也。

很多年以前，便有写一本小说的想法，也有过开头，多数都是止步千字，便无疾而终了。凡事，谋定而后动，但多数时候，是不可能万事俱备的，很多事情本来就是运行时，只有先动起来，才会达到成熟的时机。每天的时间和精力都是有限的，所以合理的分配使用便很重要。

如上诸般，归根到底，还是要 _恒_ 。

要有目标，否则，便容易迷失，必不可持久。所谓，立志当高远，非让人好高骛远、不切实际、浮躁不实。高远者，始为混沌，欲觅之，必拨云开雾，于人，则是察己之道、观世之道。高远者，虽云遮雾绕，弥于目却不盖于心，以心视之，如中天之日，若当空皓月。所谓，路漫漫其修远兮，途中难免风餐露宿，虚心空腹，以锻其志，增益其心。

#+BEGIN_QUOTE
人生数十载，不觉而立年。须臾思过弥，念至简非繁。
#+END_QUOTE

高远者，终生之志也。凡人，自非先知之辈，世间又几多先知之士。我们无法看到生前身后事，却可活在当下。凡事，预则立，不预则废。预者，思之在前，贯同始末。

#+BEGIN_QUOTE
道生一，一生二，二生三，三生万物。
#+END_QUOTE

万物有道，象繁质简，简而非易，为有序也。故思，存道于心，萃之炼之，以修身性。

思考的重要性，其实不必言说，每个人都会有所思、有所悟。可以思考，是一件多么幸运的事情，它是整个精神世界革新的驱动力。要有所成就，便不能怠思倦考，像鸵鸟一样，把脑袋埋于土沙下，是没有什么益处的。

** [2020-01-30 Thu]

#+BEGIN_QUOTE
逝者如斯夫，不舍昼夜。
#+END_QUOTE

不知不觉间，一月份已经快要过完了。意诚、心正、身修。

** [2020-01-25 Sat]

能屈能伸，方为大丈夫也。

** [2020-01-24 Fri]

火车站差点摔了跤，汽车站差点碰了头，回家之后为三只小二哈和团团狗仔服务了一个半小时，嗯，除夕快乐 ^_-||

** [2020-01-21 Tue]

家事，琐事，天下事，事事关心。

爱情，友情，人间情，情情留意。

** [2020-01-20 Mon]

一切不过“数、理、象” 。

** [2020-01-19 Sun]

解析几何 → 数、理、象？易经，无处不在！

** [2020-01-18 Sat]

#+BEGIN_QUOTE
合抱之木，生于毫末；九层之台，起于累土；千里之行，始于足下。
#+END_QUOTE

** [2020-01-17 Fri]

#+BEGIN_QUOTE
劝君莫惜金缕衣，劝君须惜少年时。\\
有花堪折直须折，莫待无花空折枝。
#+END_QUOTE

** [2020-01-16 Thu]

今日，心神有些不宁，源自何起，奈何？奈何？

** [2020-01-14 Tue]

模块化和组件化在软件工程中是不可或缺的。编程语言和各种架构，工具性大于思想性。编程的本质到底是什么呢？是对现实生活系统的抽象。生活给人的印象往往是杂乱无章的，其实不然，生活是“乱”中有 _序_ 的。编程要实现对于生活的复刻，就必须抓住其中的序。如何做呢？漫无目的，从头踩坑无疑是极度愚蠢的做法，毕竟站在巨人的肩膀上才能看的更远。什么是 _编程中的序_ 呢？路漫漫其修远兮，吾将上下而求索。

** [2020-01-13 Mon]

知识的深度和广度。

** [2020-01-12 Sun]

我这一生，到底能达成什么成就呢？人生路漫漫，前途几何？这已经成为了一个迫在眉睫的事情，容不得我不认真思考了。

有一种力量，是每个人都与生俱来的，它需要正确地引导，否则必不可持久。如何牵引这股力量呢？如何呢？如何呢？

#+BEGIN_QUOTE
大学之道，在明明德，在亲民，在止于至善。知止后有定，定而后能静，静而后能安，安而后能虑，虑而后能得。物有本末，事有终始，知所先后，则近道矣。古之欲明明德于天下者，先治其国，欲治其国者，先齐其家；欲齐其家者，先修其身；欲修其身者，先正其心；欲正其心者，先诚其意；欲诚其意者，先致其知，致知在格物。物格而后知至，知至而后意诚，意诚而后心正，心正而后身修，身修而后家齐，家齐而后国治，国治而后天下平。自天子以至于庶人，壹是皆以修身为本。其本乱而末治者，否矣。其所厚者薄，而其所薄者厚，未之有也。此谓知本，此为知之至也。所谓诚其意者， _毋自欺也_ 。如恶恶臭，如好好色，此之谓自谦。故君子必慎其独也。小人闲居为不善，无所不至，见君子而后厌然，拼其不善，而著其善。人之视己，如见其肝肺然，则何益矣。此谓诚于中形于外。故君子必慎其独也。
#+END_QUOTE

** [2020-01-11 Sat]

尝试，勇敢地去尝试。

** [2020-01-10 Fri]

#+BEGIN_QUOTE
红藕香残玉簟秋。轻解罗裳，独上兰舟。\\
云中谁寄锦书来？雁子回时，月满西楼。\\
花自飘零水自流。一种相思，两处闲愁。\\
此情无计可消除，才下眉头，却上心头。

-- 宋代·李清照《一剪梅》
#+END_QUOTE

#+BEGIN_QUOTE
明月多情应笑我，笑我如今。辜负春心，独自闲行独自吟。\\
近来怕说当时事，结遍兰襟。月浅灯深，梦里云归何处寻。

-- 清代·纳兰性德《采桑子》
#+END_QUOTE

#+BEGIN_QUOTE
风絮飘残已化萍，泥莲刚倩藕丝萦。珍重别拈香一瓣，记前生。\\
人道情多情转薄，而今真个不多情。又到断肠回首处，泪偷零。

-- 清代·纳兰性德《山花子》
#+END_QUOTE

** [2020-01-09 Thu]

对事物的认知是一个渐进的过程，在迷惑和解惑的循环中逐渐了解事物的本质。一个人，无论是笨蛋，还是天才，都必须经过这个过程。相对而言，天才只是可能走的更快些，笨蛋则会慢一些。但是不是快了就一定好呢？慢了就一定不好呢？这些东西都是相对的。宇宙的一切事物都是平衡的，每个人都会在生命的历程中收获属于他自己的精彩。

** [2020-01-08 Wed]

《易经》，神奇的经典。

** [2020-01-07 Tue]

2020 年的第七天，感冒中……

我这身体啊，都快锈掉了…… 再不锻炼，估计要提前迈入中年危机了。天人合一，精神和物质的融合，生命便是两者的载体。请爱惜身体，敬畏生命。

** [2020-01-06 Mon]

凡事，预则立，不预则废。满招损，谦受益。了解自己，保持清醒，且不可得意忘形，忘乎所以。

** [2020-01-05 Sun]

前几天，那么多的废话，也逃不出 _变易、简易、不易_ 。人傻就要多读书，先辈诚不欺我也。

** [2020-01-04 Sat]

计划！为什么需要计划？时间有限，光阴不可逆，高效地利用时间去做合理的事情就显得十分迫切和重要。

知行合一，何为知，何为行？从某个角度而言，知和行其实是理论和实践的一种平衡。重理论，轻实践，便不能很好地检验理论地正确性，仿若把自身置于空中楼阁。重实践，轻理论，也会有南辕北辙撞南墙的下场。知行的平衡便在于，两者的的作用是相互的。

工作中，不能一味地沉浸在解决边角料，那样不利于自身理论体系的建立，也不能抵触排斥，因为它本身也是对理论体系的补充和验证。理论体系的建立，不是主观臆想而来的，它是我们自身的实践，和观察别人的实践过程，所获取的直接、间接的认识内化形成的。

为什么需要计划呢？人生苦短。这一生，要实现什么？这大概是一个人的终极目标了。空泛地追求无限是没有意义的，了解局限是实际的做法，有时候甚至需要人为的去设置边界。拿计划来说，日计划、月计划、季计划、年计划、三年计划、五年计划、十年计划等，用时间来做边界。不做限制，没有边界，是很空洞的。如同给你一张大若天际的白纸，你反而不知道如何涂抹了。反而不若裁剪开来，反而容易成其全貌。

不能闭门造车，多读书，多读经典，没有错的。

** [2020-01-03 Fri]

一般都是八点四十起床，偶尔六点醒一次，一天就朦胧过去了……

习惯的力量！所谓，君子生非异也，善假于物也。也许意识是无限的，但躯壳是受限的。观察现象，探寻规律，顺势而为，用无形的手，引导动的弦。不以物喜，不以己悲。哎，古人的智慧，浩瀚如沧海。历史，反复而曲折，今朝的落日，千年之前的夕阳。既有道，生于忧患，死于安乐。又谓，闲看落花，不着风云动，卷舒随心。

愿静思、冥想，得一二，砥砺前行，不负韶华。这个周末，好好地规划一下 2020 ，千里之行，由足下始。光阴似箭，时不我待，一万年太久，只争朝夕。

** [2020-01-02 Thu]

羞于笔触，腹内空空。生了锈的指尖敲击，脑海中的混沌。非得无处着手，奈何点墨不足于胸。

想来，事物的本质，往往是简而有理的，许多常态化的细枝末节往往是后来人释注而已。古语云，读万卷书，行万里路，私以为，便是应了那句“纸上得来终觉浅，绝知此事要躬行”。做学问，一味地道听途说，不可取。求索真理的漫漫长途中，不求甚解更要不得。细想来，书中多有谬误，曾阅一事，说是诸葛孔明读书只了了数观，便弃之高阁，不求甚解。用来表达的是，读书不要那么认真，不要寻根究底。每每思起，莫不要让人笑掉大牙了。思来，应是丞相腹有经纶，对于一些斧凿之作，略睹便知其意罢了。

** [2020-01-01 Wed]

2020 的第一天。

