#+SETUPFILE: ../theme-rose.setup
#+DATE: <2020-01-20 Mon 20:48>
#+TITLE: Idea

* 闪念

#+BEGIN_QUOTE
舍，得，是一种生活的艺术。
#+END_QUOTE

** [2020-07-13 Mon 16:32]

必须明白事物是在不断发展的，故要了解一种事物，最简单的办法就是追本逐末，并尝试用一种明了清晰的方式去描述本末之间的过程。PS. 现在许多朋友在学习一门新的知识的时候，往往是采用一种啃字典式的方法，这是难以坚持的，也是不符合学习事物的规律的。字典式的著作是用来参考和查询的，切不可乱了顺序，导致事倍功半。

** [2020-07-12 Sun 23:59]

反求诸已内中寻，莫道人间不值得。

** [2020-07-01 Wed 21:20]

生活，不应该只是萝卜白菜，也不应该皆为山珍海味，要兼容并包，自然和谐。

** [2020-06-24 Wed 15:22]

案前灯下，皓首穷经。

** [2020-06-15 Mon 15:31]

标准、流程、可扩展……

** [2020-06-01 Mon 09:29]

事实证明，过度的安逸不会给你带来任何的快乐，人是要认真劳动的，只有在创造价值的过程中才会享受到真正的愉悦。

** [2020-05-30 Sat 15:51]

我们的人民是朴实的、是可爱的，越是生活在底层的人民，这一点多数时候越是更加地突出。但我们没有任何理由和借口认为他们就应该过贫困的生活，要尽自己的一份力量去帮助那些需要帮助的同胞，从精神上、物质上。

** [2020-05-29 Fri 10:48]

我愿用我的一生，送给祖国一份礼物。

** [2020-05-29 Fri 10:46]

能否用一种简单的方式去阐述一件事物的本质是衡量你是否透彻理解它的重要标准。

** [2020-05-29 Fri 10:45]

基础是很重要的，人们对于统一理论的研究是无止境的，按照老子的思想，统一理论的源头就是道。

** [2020-05-28 Thu 14:05]

操作准确性！操作准确性是指操作运动结果达到操作运动的目标。

#+BEGIN_EXAMPLE
W = a + b * (D / T)

- W 运动终点分布的标准差
- D 运动距离
- T 运动时间
- a、b 常数
#+END_EXAMPLE

显然，操作的准确性与操作速度存在反比关系，即随着操作速度的提高而下降，随着操作速度的下降而上升。

要有意识的训练自己的操作准确性，“差不多”这个态度往往在关键时刻让你栽一个大大的跟头。还记得《三傻大闹宝莱坞》中，阿米尔汗说得那样，让优秀成为一种习惯，成功就会追求你。
** [2020-05-28 Thu 10:55]

 能否用简单易懂的方式描述一件事物的本质，是衡量你是否真正解透彻的重要标准。如果，你自己都感觉组织出来的语言是晦涩难懂的，那么，你就需要进一步地思考。
** [2020-05-26 Tue 09:11]

没有绝对的真理，但有些原则是历久弥新的，不用怀疑，极大概率下在你生活的这个时代，这些原则都是放之四海而皆准的。做事没有原则，便容易摇摆不定，徒增无用的损耗。记住，它的本质还是相对的，某些时候要懂得变通，变则通，通则达。看，许多论述也是相对的，想必古人也遇到过同样的困惑吧，《大学》中已经给出了解决方法 -- 不自欺。

** [2020-05-22 Fri 14:42]

人啊，就怕没有激情，做一件事情，感觉毫无乐趣，不是事情出了问题，就是这件事本来就是个问题，亦或是问题在于你自己本身，非外物之罪。

** [2020-05-18 Mon 00:47]

习惯的力量是巨大的，遵循客观和社会规律，养成良好的习惯是通向幸福生活的必经之路。什么是幸福？心之所向，力之所至，独善其身，兼济天下。

** [2020-05-11 Mon 16:17]

人傻就要多读书……

** [2020-05-09 Sat 12:41]

所谓“由易而难”，有时容易引起人们的误解。“易” 者，非是细枝末节，而是大观，即身在山外，览其全貌，以做到胸有成竹。

** [2020-05-06 Wed 09:56]

同样的软件，Linux 下的执行效率是 Windows 下的十几倍…… 这都是什么神操作？

** [2020-05-04 Mon 17:38]

多日不出，内心甚是烦躁，何事扰乎？心存不乐乎？呼……

** [2020-05-02 Sat 07:39]

人的生活是一个大循环，保持各个环节的有效衔接和顺畅是十分必要的。

** [2020-04-30 Thu 22:15]

期待 5G ，期待超高的网络速度，期待在此基础上可以有物美价廉的云主机（具备良好的性能和 GUI 界面），这就从很大程度上解决了环境迁移所耗费的时间和精力。

** [2020-04-30 Thu 21:05]

面对每天晚上的龟速网络，默默地开始本地模式，网速慢的日子就是如此的朴实无华而枯燥……

** [2020-04-29 Wed 16:50]

系统化、规范化、标准化，可以有效地减少时间和精力的浪费。

** [2020-04-24 Fri 14:27]

万物有序，序者，道之理也。道生一，一生二，二生三，三生万物。万物并作，井然而有序。序者，生活之本也。

** [2020-04-24 Fri 11:02]

我不愿意在不喜欢的事上花太多时间，无论如何都想过上只做自己喜欢的事的生活。 -- 高岛美里

** [2020-04-24 Fri 10:49]

生活在人类社会，怎么可以不考虑人性？这也是为什么一切要以人为本。

** [2020-04-22 Wed 16:15]

了解有什么，知道为什么，要去做什么。

** [2020-04-14 Tue 11:45]

思想是一切创造性活动的源头、所有现象的依托本质、最重要的价值载体。

** [2020-04-14 Tue 09:29]

秦始皇和毛主席，这两个分别开创和终结了封建王朝的男人，可谓是“前无古人，后无来者”，空前绝后！

** [2020-04-08 Wed 15:56]

自由是什么？自由是可以不在乎是否拥有，但想拥有的时候可以随时拥有。清心寡欲是没有错，可有可无才是大自在，不是吗？

** [2020-04-07 Tue 19:13]

所谓奇淫异巧不过是锦上添花的事物，基本原理才是最重要的，万变不离其踪。

** [2020-04-07 Tue 15:04]

当你自己亲手实现了，你就开始理解了，反之，深层次的理解，有助于更好的实现。

** [2020-04-07 Tue 13:36]

学而不思则罔，思而不学则殆。

** [2020-04-04 Sat 16:40]

凡事不可一时冲动，不可凭一己好恶。当每日三省己身，探寻真理。

** [2020-04-01 Wed 19:11]

这身体真的要锈掉了，心血来潮做个体操，好痛……

** [2020-04-01 Wed 09:50]

事有轻重缓急，若不能分主次先后，混乱为之，必得其咎。

** [2020-03-31 Tue 14:19]

思考应该是系统性或趋向于系统性的，不然它所花费的时间和精力多会事倍功半。

** [2020-03-30 Mon 19:47]

一切都是有迹可循的，只要你用心去发现，万物皆遵循其基本原理。

** [2020-03-27 Fri 09:21]

只要去探索，你会发现一切自有解决之道。

** [2020-03-27 Fri 05:45]

切身体会，可早起，不可晚睡，否则，得不偿失，不利身心。

** [2020-03-25 Wed 12:00]

韶华易逝，人生苦短。应该有意识地训练在状态不好的时候，也能保持一个不错的效率输出。状态好的时候，更应该集中精力办重要且紧急的事。

** [2020-03-24 Tue 16:33]

发现自己每隔一段时间，总会大批量删除一些博文……

** [2020-03-19 Thu 16:32]

| 学习 | →    | 了解 |
| ↑    | 思考 | ↓    |
| 实践 | ←    | 认识 |

** [2020-03-19 Thu 10:34]

所谓“走通基本流程”，其实就是一个“理清基本原理”或趋近于理清的过程。任何机制，一旦理解了其基本的运行原理，一切就变得有迹可循，许多问题就迎刃而解。学习的过程，本质上来说，不外乎也是掌握事物本质和原理的过程，精进就是基于这个大前提的再创造、再发挥。

** [2020-03-18 Wed 20:06]

不存在绝对安全的密码，充其量也就是最大限度的相对安全，而且还只是从技术上来说。放在现实生活中，总会有破解的捷径可供选取。

** [2020-03-18 Wed 09:11]

#+BEGIN_QUOTE
天下无难事，只要肯登攀。
#+END_QUOTE

这世上，司空见惯的事物，大多没有什么新鲜事儿，局限在规则之内的，就更难翻出什么风浪，当你懂了，你就自然而然地懂了。尊重生活，尊重自己。

** [2020-03-17 Tue 23:21]

尽自己最大的努力去做应该做的事情，就是对生活最大的尊重，也是对自己最好的交代。

** [2020-03-17 Tue 18:00]

大英帝国的“群体免疫” 是什么神奇的操作？是不是可以这样理解 -- “群体免疫”等于“群体感染” 。

** [2020-03-16 Mon 21:05]

一直以为欧洲很大，结果整个欧洲加起来也不过才 1016 万平方公里，欧盟所有成员国加起来总面积还略低于 440 万平方公里…… 同样的，还有印度（不过 298 万平方公里），想当然的感觉真的不靠谱。

** [2020-03-16 Mon 10:33]

似有万语肺腑转，若无一言笔墨干。-- 下笔有感

** [2020-03-13 Fri 09:31]

恩威并施。只恩不威，必生不屑 ；只威不恩，必遭祸患。是故，行有不得，反求诸己，方为大道也。万物有度，以心量之，严己宽人，始得自在。

** [2020-03-06 Fri 16:46]

要透过现象看本质！身临其境，以心观之；跳出樊笼，始得自在。

** [2020-03-04 Wed 14:35]

按照日程安排来进行当天的工作，你可能会感觉到很紧迫，因为会大大压缩你无所事事的时间，当你心知肚明有些重要的事情有待处理时，肆无忌惮的自欺欺人便会显得困难了许多。

** [2020-03-01 Sun 09:03]

减少无用信息的摄入和处理，是节约时间和精力的关键前提之一。随着时空条件的转换，各种信息的主次紧缓是在变动的，所以不能过于惯性和僵化。如此，如何准确地、快速地根据当时的状况迅速判断并采取行动是非常重要的，得了此道，便很大程度上从源头解放了身心，进而缓解精神、物质世界的无意义甚至负向作用的压力。大脑的运转速度，现在没有人能给出具体的数据，所有既定的标准不过是当前条件下的一种人类大众看法，实际上不值一提，应该自己去追寻和探索，精神世界绝对没有那么简单，绝不是几个数字就可以限定的。要注意冥想和思考，站在身外观己身，居于天上观天下。道是什么？是规则。天道，人道，大道，小道，都是规则。天道无情，大道无垠，放之四海而皆准。人道六欲，小道有拘，理清条理，时地制宜。正所谓，变则通，通则达。

** [2020-02-29 Sat 08:43]

熬夜？熬夜？熬夜？不熬夜！不熬夜！不熬夜！

** [2020-02-28 Fri 09:15]

视频内容的两种摄入方式，一种是漫无目的的随意浏览，随进随出，思考占比极少，可用于放松，但不可成为常态；一种是心索某个情节，探寻式浏览，大脑会根据情节进行一定程度的精力分配，略有效率，同样不可成为常态。通常来说，视频内容是一种被动摄入，是一种所有内容，无关轻重主次、时间均分的方式，这决定了它的低效率本质。同样，音频内容也存在同样的不足。阅读，则是主动式是摄入，是一种因人而异保证内容吸收，进而保持高效的方式。阅读，有利于思考、内化和沉淀。人生苦短，高效、合理地利用时间，去做一些有意义的事情。

** [2020-02-22 Sat 21:39]

哎，蜗牛网络，真的让人无语透顶，一切拖慢个人节奏的耗费都是昂贵无比的！

** [2020-02-19 Wed 22:05]

由内而外，反求诸己。

** [2020-02-06 Thu 23:18]

啊哈，这疯狂的一周，持之以恒的思考和练习是成功不可或缺的一部分。

** [2020-02-06 Thu 14:39]

厚积薄发，寻本溯源，自然而然，水到渠成。

** [2020-02-06 Thu 12:51]

如果，你懂了，那么，你自然就懂了。

** [2020-02-03 Mon 15:46]

#+BEGIN_QUOTE
“不尚贤，使民不为盗。”\\
“天下皆知美之为美，斯恶矣。”
#+END_QUOTE

** [2020-02-02 Sun 12:14]

只有来自灵魂的乐声，才会直击人的灵魂。

** [2020-01-29 Wed 23:50]

抓住本质，了解其真正的运行机制，一切都会变的一目了然。

** [2020-01-28 Tue 20:04]

#+BEGIN_QUOTE
苟利国家生死以，岂因祸福避趋之。
#+END_QUOTE

** [2020-01-28 Tue 13:36]

梳理好，控制度，明确分类。

** [2020-01-25 Sat 11:08]

没有什么比心灵的宁静更重要的了，剥繁去简，追寻精神的升华，和、谐。

** [2020-01-21 Tue 15:16]

追本溯源，理清脉络。剥繁去杂，明本见质。
