#+SETUPFILE: ../theme-rose.setup
#+DATE: <2020-01-14 Tue 20:28>
#+TITLE: 四书

#+BEGIN_QUOTE
南宋朱熹将《大学》、《中庸》、《论语》、《孟子》合编注释，称为《四书》。
#+END_QUOTE

** 大学

→ [[https://so.gushiwen.org/guwen/book_20.aspx][大学]]

#+BEGIN_QUOTE
《大学》原为《礼记》第四十二篇。宋朝程颢、程颐兄弟把它从《礼记》中抽出，编次章句。朱熹把《大学》重新编排整理，分为“经”一章，“传”十章。认为，“经一章孔子之言，而曾子述之；其传十章，则曾子之意而门人记之也。”
#+END_QUOTE

“大学”是对“小学”而言，是说它不是讲“详训诂，明句读”的“小学”，而是讲治国安邦的“大学”。“小学”即：“洒扫应对进退，礼乐射御书数”。“大学”是大人之学，古人十五岁入学，学习伦理、政治和哲学等“穷理正心，修理治人”的学问，实则是学习如何参与国家政治。

《大学》为“初学入德之门也”。经一章提出了 _明明德、亲民、止于至善_ 三条纲领，又提出了 _格物、致知、诚意、正心、修身、齐家、治国、平天下_ 八个条目。八个条目是实现三条纲领的途径。在八个条目中， _修身_ 是根本的一条，“自天子以至于庶人，壹是皆以修身为本”。十章分别解释：
- _明明德_ 是指弘扬光明正大的品德；
- _新民_ 是指让人们革旧图新；
- _止于至善_ 是指要达到最好的境界；
- _本末_ 是指做事要分清主次，抓住根本；
- _格物、致知_ 是指穷究事物的原理来获得知识；
- _诚意_ 就是“毋自欺”，不要“掩其不善而著其善”；
- _正心_ 就是端正自己的心思；
- _修身_ 就是加强自身修养，提高自身素质；
- _齐家_ 就是管理好自己的家庭、家族；
- _治国、平天下_ 是谈治理国家的事。

怎么样治理国家呢？首先要作表率；自己讨厌的，不加给别人；要得众、慎得、生财、举贤。“得众则得国，失众则失国”；“有德此有人，有人此有土，有土此有财”；见贤能举，举而能先。《大学》寄托了古人 _内圣外王_ 的理想。

*** 经

#+BEGIN_QUOTE
大学之道，在明明德，在亲民，在止于至善。

知止而后有定，定而后能静，静而后能安，安而后能虑，虑而后能得。物有本末，事有终始。知所先后，则近道矣。

古之欲明明德于天下者，先治其国；欲治其国者，先齐其家；欲齐其家者，先修其身；欲修其身者，先正其心；欲正其心者，先诚其意；欲诚其意者，先致其知。致知在格物。物格而后知至，知至而后意诚，意诚而后心正，心正而后身修，身修而后家齐，家齐而后国治，国治而后天下平。自天子以至于庶人，壹是皆以修身为本。

其本乱而末治者，否矣。其所厚者薄，而其所薄者厚，未之有也。此谓知本，此谓知之至也。
#+END_QUOTE

大学的道理，在于彰显人人本有，自身所具的光明德性，再推己及人，是人人都能去除污染而自新，而且精益求精，做到最完善的地步并且保持不变。

知道应达到的境界才能够志向坚定；志向坚定才能够镇静不躁；镇静不躁才能够心安理得；心安理得才能够思虑周详；思虑周详才能够有所收获。每样东西都有根本有枝末，每件事情都有开始有终结。明白了这本末始终的道理，就接近事物发展的规律了。
